import { DatabaseConnectionParams, createPostgres } from '@immich/sql-tools';
import { Kysely, sql } from 'kysely';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { gunzipSync } from 'node:zlib';
import { DB } from 'src/schema/index.js';
import { alignCertifiedGeodataCatalog } from 'test/medium/specs/fork-schema/certified-geodata-fixture.js';

/** Replace the test database's schemas with the exact public schema and ledger of official v3.1.0. */
export const restoreOfficialPublicSchema = async (db: Kysely<DB>) => {
  const database = await sql<{ name: string }>`SELECT current_database() AS name`.execute(db);
  const url = process.env.IMMICH_TEST_POSTGRES_URL!.replace('/mich', () => `/${database.rows[0]!.name}`);
  const connection = { connectionType: 'url', url } as DatabaseConnectionParams;
  const postgres = createPostgres({ connection, maxConnections: 1 });
  // Generated by pg_dump from exact tag v3.1.0 (v3.1.0). The extensions are
  // supplied by the same PostgreSQL image and are intentionally not in pg_dump.
  const fixture = gunzipSync(
    Buffer.from(readFileSync(resolve('test/medium/fixtures/v3.1.0-public-schema.sql.gz.base64'), 'utf8'), 'base64'),
  )
    .toString()
    .replace('CREATE SCHEMA public;', '');
  try {
    await postgres.unsafe(`
      DROP EXTENSION IF EXISTS earthdistance CASCADE;
      DROP EXTENSION IF EXISTS cube CASCADE;
      DROP EXTENSION IF EXISTS unaccent CASCADE;
      DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;
      DROP EXTENSION IF EXISTS vchord CASCADE;
      DROP EXTENSION IF EXISTS vector CASCADE;
      DROP EXTENSION IF EXISTS pg_trgm CASCADE;
      DROP SCHEMA IF EXISTS immich_fork CASCADE;
      DROP SCHEMA public CASCADE;
      CREATE SCHEMA public;
      CREATE EXTENSION cube WITH SCHEMA public;
      CREATE EXTENSION earthdistance WITH SCHEMA public;
      CREATE EXTENSION pg_trgm WITH SCHEMA public;
      CREATE EXTENSION unaccent WITH SCHEMA public;
      CREATE EXTENSION "uuid-ossp" WITH SCHEMA public;
      CREATE EXTENSION vector WITH SCHEMA public;
      CREATE EXTENSION vchord WITH SCHEMA public;
      ${fixture}
    `);
    await alignCertifiedGeodataCatalog(db);
  } finally {
    await postgres.end();
  }
};
