-- NOTE: This file is auto generated by ./sql-generator

-- AlbumUserRepository.getRecipientGroups
SELECT
  id::text AS id,
  "ownerId"::text AS "ownerId",
  name,
  "userIds"::text[] AS "userIds",
  "createdAt",
  "updatedAt"
FROM
  immich_fork.recipient_group
WHERE
  "ownerId" = $1::uuid
ORDER BY
  lower(name),
  id

-- AlbumUserRepository.getRecipientGroup
SELECT
  id::text AS id,
  "ownerId"::text AS "ownerId",
  name,
  "userIds"::text[] AS "userIds",
  "createdAt",
  "updatedAt"
FROM
  immich_fork.recipient_group
WHERE
  id = $1::uuid
  AND "ownerId" = $2::uuid

-- AlbumUserRepository.create
insert into
  "album_user" ("userId", "albumId")
values
  ($1, $2)
returning
  "userId",
  "albumId",
  "role"

-- AlbumUserRepository.update
update "album_user"
set
  "role" = $1
where
  "userId" = $2
  and "albumId" = $3

-- AlbumUserRepository.delete
delete from "album_user"
where
  "userId" = $1
  and "albumId" = $2
