-- NOTE: This file is auto generated by ./sql-generator

-- AssetEditRepository.replaceAll
begin
SELECT
  phase
FROM
  immich_fork.state
WHERE
  id = 1
FOR SHARE
rollback

-- AssetEditRepository.getAll
select
  "id",
  "action",
  "parameters"
from
  "asset_edit"
where
  "assetId" = $1
order by
  "sequence" asc

-- AssetEditRepository.getWithSyncInfo
select
  "asset_edit"."id",
  "asset_edit"."assetId",
  "asset_edit"."sequence",
  "asset_edit"."action",
  "asset_edit"."parameters"
from
  "asset_edit"
where
  "assetId" = $1
order by
  "sequence" asc
