-- NOTE: This file is auto generated by ./sql-generator

-- BestPhotosRepository.getScore
select
  *
from
  "public"."asset_best_photo_score"
where
  "assetId" = $1::uuid

-- BestPhotosRepository.upsertScore
begin
select
  "ownerId"
from
  "asset"
where
  "id" = $1
for update
rollback

-- BestPhotosRepository.getBestPhotos
select
  count(*) as "count"
from
  "public"."asset_best_photo_score" as "asset_best_photo_score"
  inner join "public"."asset" as "asset" on "asset"."id" = "asset_best_photo_score"."assetId"
where
  "asset_best_photo_score"."ownerId" = $1::uuid
  and "asset"."ownerId" = $2::uuid
  and "asset"."deletedAt" is null
  and "asset"."status" = 'active'
  and "asset"."visibility" in ('timeline')
  and not exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  )
  and "asset"."type" in ('IMAGE', 'VIDEO')
  and "asset_best_photo_score"."score" >= $3
select
  "asset".*,
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked",
  "asset_best_photo_score"."score" as "bestPhotoScore",
  "asset_best_photo_score"."aestheticScore" as "bestPhotoAestheticScore",
  "asset_best_photo_score"."technicalScore" as "bestPhotoTechnicalScore",
  "asset_best_photo_score"."subjectScore" as "bestPhotoSubjectScore",
  "asset_best_photo_score"."diversityScore" as "bestPhotoDiversityScore",
  "asset_best_photo_score"."scoreVersion" as "bestPhotoScoreVersion",
  "asset_best_photo_score"."computedAt" as "bestPhotoComputedAt",
  "asset_best_photo_score"."metadata" as "bestPhotoMetadata",
  "asset_best_photo_score"."bestFrameTimestampMs" as "bestPhotoBestFrameTimestampMs",
  "asset_best_photo_score"."frameScore" as "bestPhotoFrameScore",
  "asset_best_photo_score"."frameMetadata" as "bestPhotoFrameMetadata"
from
  "public"."asset_best_photo_score" as "asset_best_photo_score"
  inner join "public"."asset" as "asset" on "asset"."id" = "asset_best_photo_score"."assetId"
where
  "asset_best_photo_score"."ownerId" = $1::uuid
  and "asset"."ownerId" = $2::uuid
  and "asset"."deletedAt" is null
  and "asset"."status" = 'active'
  and "asset"."visibility" in ('timeline')
  and not exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  )
  and "asset"."type" in ('IMAGE', 'VIDEO')
  and "asset_best_photo_score"."score" >= $3
order by
  "asset_best_photo_score"."score" desc,
  "asset"."fileCreatedAt" desc
limit
  $4
offset
  $5

-- BestPhotosRepository.deleteForAssets
begin
delete from "public"."asset_best_photo_score"
where
  "assetId" = any ($1::uuid[])
commit
