-- NOTE: This file is auto generated by ./sql-generator

-- CloudBackupIndexRepository.getExisting
select
  "sha256"
from
  "cloud_backup_object"
where
  "bucket" = $1
  and "sha256" in ($2)

-- CloudBackupIndexRepository.record
insert into
  "cloud_backup_object" ("bucket", "sha256", "size", "etag")
values
  ($1, $2, $3, $4)
on conflict ("bucket", "sha256") do update
set
  "size" = "excluded"."size",
  "etag" = coalesce(excluded."etag", "cloud_backup_object"."etag"),
  "lastSeenAt" = now()

-- CloudBackupIndexRepository.touch
update "cloud_backup_object"
set
  "lastSeenAt" = now()
where
  "bucket" = $1
  and "sha256" in ($2)

-- CloudBackupIndexRepository.deleteBucket
delete from "cloud_backup_object"
where
  "bucket" = $1

-- CloudBackupIndexRepository.currentTime
select
  to_json(now()) as "now"

-- CloudBackupIndexRepository.pruneUnseen
delete from "cloud_backup_object"
where
  "bucket" = $1
  and "lastSeenAt" < $2::timestamptz

-- CloudBackupIndexRepository.getUsage
select
  count(*) as "objects",
  coalesce(sum("size"), 0) as "bytes"
from
  "cloud_backup_object"
where
  "bucket" = $1

-- CloudBackupIndexRepository.createManifest
insert into
  "cloud_backup_manifest" ("bucket", "key", "operationId")
values
  ($1, $2, $3)
returning
  "id",
  "bucket",
  "key",
  "operationId",
  "status",
  "createdAt"

-- CloudBackupIndexRepository.getManifest
select
  "id",
  "bucket",
  "key",
  "operationId",
  "status",
  "createdAt"
from
  "cloud_backup_manifest"
where
  "id" = $1

-- CloudBackupIndexRepository.finishManifest
begin
select
  "status"
from
  "cloud_backup_manifest"
where
  "id" = $1
for update
commit

-- CloudBackupIndexRepository.recordObjectVerification
insert into
  "cloud_backup_object_verification" (
    "bucket",
    "sha256",
    "operationId",
    "method",
    "result"
  )
select
  $1 as "bucket",
  $2 as "sha256",
  "id" as "operationId",
  $3 as "method",
  $4 as "result"
from
  "media_operation"
where
  "id" = $5
  and "claimToken" = $6
  and "kind" = $7
  and "status" not in ($8, $9, $10)
  and snapshot ->> 'bucketRef' = $11
  and snapshot ->> 'task' = $12
  and COALESCE(snapshot ->> 'depth', 'sample') = $13
for share
on conflict ("bucket", "sha256", "operationId") do update
set
  "method" = $14,
  "result" = $15,
  "checkedAt" = clock_timestamp()

-- CloudBackupIndexRepository.getCompletedObjectVerifications
select
  "proof".*
from
  "cloud_backup_object_verification" as "proof"
  inner join "media_operation" as "operation" on "operation"."id" = "proof"."operationId"
where
  "proof"."bucket" = $1
  and "proof"."sha256" in ($2)
  and "operation"."kind" = $3
  and "operation"."status" = $4
  and operation.snapshot ->> 'bucketRef' = $5
  and operation.snapshot ->> 'task' = $6
  and operation.result ->> 'task' = $7
  and operation.result ->> 'done' = $8
  and operation.result ->> 'depth' = COALESCE(operation.snapshot ->> 'depth', 'sample')
  and proof.method = CASE
    WHEN operation.snapshot ->> 'depth' = 'full' THEN 'size-head'
    ELSE 'sha256-get'
  END
order by
  "proof"."checkedAt" desc

-- CloudBackupIndexRepository.setManifestDatabase
update "cloud_backup_manifest"
set
  "databaseKey" = $1
where
  "id" = $2

-- CloudBackupIndexRepository.getKeptDatabaseKeys
select
  "databaseKey"
from
  "cloud_backup_manifest"
where
  "bucket" = $1
  and "status" in ($2, $3)
  and "databaseKey" is not null

-- CloudBackupIndexRepository.getManifestKeys
select
  "key"
from
  "cloud_backup_manifest"
where
  "bucket" = $1
  and "key" in ($2)

-- CloudBackupIndexRepository.adoptManifests
select
  "key"
from
  "cloud_backup_manifest"
where
  "bucket" = $1
  and "key" in ($2)

-- CloudBackupIndexRepository.listKeptManifests
select
  "key",
  "status",
  "databaseKey",
  "createdAt",
  "finishedAt",
  "assetCount",
  "fileCount",
  "bytes"
from
  "cloud_backup_manifest"
where
  "bucket" = $1
  and "status" in ($2, $3)
order by
  "createdAt" desc

-- CloudBackupIndexRepository.markManifests
update "cloud_backup_manifest"
set
  "status" = $1
where
  "bucket" = $2
  and "key" in ($3)
  and "status" in ($4, $5)

-- CloudBackupIndexRepository.forget
delete from "cloud_backup_object"
where
  "bucket" = $1
  and "sha256" in ($2)

-- CloudBackupIndexRepository.getLibraryState
select
  "id",
  "status",
  "deletedAt",
  "originalFileName",
  "originalPath",
  "ownerId",
  "isExternal",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "locked"
from
  "asset"
where
  "id" = any ($1::uuid[])
  and "status" in ($2, $3)

-- CloudBackupIndexRepository.getOwnerNames
select
  "id",
  "name"
from
  "user"
where
  "id" in ($1)

-- CloudBackupIndexRepository.endAbandonedManifests
update "cloud_backup_manifest"
set
  "status" = $1,
  "finishedAt" = now()
where
  "status" = $2
  and not exists (
    select
      "media_operation"."id"
    from
      "media_operation"
    where
      "media_operation"."id" = "cloud_backup_manifest"."operationId"
      and "media_operation"."status" not in ($3, $4, $5)
  )
returning
  "id"
delete from "cloud_backup_manifest_entry"
where
  "manifestId" in ($1)

-- CloudBackupIndexRepository.upsertEntries
insert into
  "cloud_backup_manifest_entry" (
    "fileKey",
    "assetId",
    "ownerId",
    "role",
    "path",
    "sha256",
    "size",
    "mtime",
    "manifestId"
  )
values
  ($1, $2, $3, $4, $5, $6, $7, $8, $9)
on conflict ("manifestId", "fileKey") do update
set
  "assetId" = "excluded"."assetId",
  "ownerId" = "excluded"."ownerId",
  "role" = "excluded"."role",
  "path" = "excluded"."path",
  "sha256" = "excluded"."sha256",
  "size" = "excluded"."size",
  "mtime" = "excluded"."mtime"

-- CloudBackupIndexRepository.getEntriesPage
select
  "fileKey",
  "assetId",
  "ownerId",
  "role",
  "path",
  "sha256",
  "size",
  "mtime"
from
  "cloud_backup_manifest_entry"
where
  "manifestId" = $1
  and "fileKey" > $2
order by
  "fileKey"
limit
  $3

-- CloudBackupIndexRepository.deleteEntries
delete from "cloud_backup_manifest_entry"
where
  "manifestId" = $1

-- CloudBackupIndexRepository.countAssets
select
  count(*) as "count"
from
  "asset"
where
  "status" in ($1, $2)
  and "isExternal" = $3

-- CloudBackupIndexRepository.listAssets
select
  "id",
  "ownerId",
  "originalPath"
from
  "asset"
where
  "status" in ($1, $2)
  and "isExternal" = $3
  and "id" > $4
order by
  "id"
limit
  $5

-- CloudBackupIndexRepository.listProfileImages
select
  "id",
  "profileImagePath"
from
  "user"
where
  "profileImagePath" != $1
  and "deletedAt" is null
order by
  "id"
