-- NOTE: This file is auto generated by ./sql-generator

-- CloudBackupIndexRepository.getExisting
select
  "sha256"
from
  "cloud_backup_object"
where
  "bucket" = $1
  and "sha256" in ($2)

-- CloudBackupIndexRepository.record
insert into
  "cloud_backup_object" ("bucket", "sha256", "size", "etag")
values
  ($1, $2, $3, $4)
on conflict ("bucket", "sha256") do update
set
  "size" = "excluded"."size",
  "etag" = coalesce(excluded."etag", "cloud_backup_object"."etag"),
  "lastSeenAt" = now()

-- CloudBackupIndexRepository.touch
update "cloud_backup_object"
set
  "lastSeenAt" = now()
where
  "bucket" = $1
  and "sha256" in ($2)

-- CloudBackupIndexRepository.deleteBucket
delete from "cloud_backup_object"
where
  "bucket" = $1

-- CloudBackupIndexRepository.currentTime
select
  now() as "now"

-- CloudBackupIndexRepository.pruneUnseen
delete from "cloud_backup_object"
where
  "bucket" = $1
  and "lastSeenAt" < $2

-- CloudBackupIndexRepository.getUsage
select
  count(*) as "objects",
  coalesce(sum("size"), 0) as "bytes"
from
  "cloud_backup_object"
where
  "bucket" = $1

-- CloudBackupIndexRepository.createManifest
insert into
  "cloud_backup_manifest" ("bucket", "key", "operationId")
values
  ($1, $2, $3)
returning
  "id",
  "bucket",
  "key",
  "operationId",
  "status",
  "createdAt"

-- CloudBackupIndexRepository.getManifest
select
  "id",
  "bucket",
  "key",
  "operationId",
  "status",
  "createdAt"
from
  "cloud_backup_manifest"
where
  "id" = $1

-- CloudBackupIndexRepository.finishManifest
update "cloud_backup_manifest"
set
  "status" = $1,
  "assetCount" = $2,
  "fileCount" = $3,
  "bytes" = $4,
  "finishedAt" = now()
where
  "id" = $5

-- CloudBackupIndexRepository.setManifestDatabase
update "cloud_backup_manifest"
set
  "databaseKey" = $1
where
  "id" = $2

-- CloudBackupIndexRepository.getLatestManifestDatabaseKey
select
  "databaseKey"
from
  "cloud_backup_manifest"
where
  "bucket" = $1
  and "status" = $2
  and "databaseKey" is not null
order by
  "createdAt" desc
limit
  $3

-- CloudBackupIndexRepository.endAbandonedManifests
update "cloud_backup_manifest"
set
  "status" = $1,
  "finishedAt" = now()
where
  "status" = $2
  and not exists (
    select
      "media_operation"."id"
    from
      "media_operation"
    where
      "media_operation"."id" = "cloud_backup_manifest"."operationId"
      and "media_operation"."status" not in ($3, $4, $5)
  )
returning
  "id"
delete from "cloud_backup_manifest_entry"
where
  "manifestId" in ($1)

-- CloudBackupIndexRepository.upsertEntries
insert into
  "cloud_backup_manifest_entry" (
    "fileKey",
    "assetId",
    "ownerId",
    "role",
    "path",
    "sha256",
    "size",
    "mtime",
    "manifestId"
  )
values
  ($1, $2, $3, $4, $5, $6, $7, $8, $9)
on conflict ("manifestId", "fileKey") do update
set
  "assetId" = "excluded"."assetId",
  "ownerId" = "excluded"."ownerId",
  "role" = "excluded"."role",
  "path" = "excluded"."path",
  "sha256" = "excluded"."sha256",
  "size" = "excluded"."size",
  "mtime" = "excluded"."mtime"

-- CloudBackupIndexRepository.getEntriesPage
select
  "fileKey",
  "assetId",
  "ownerId",
  "role",
  "path",
  "sha256",
  "size",
  "mtime"
from
  "cloud_backup_manifest_entry"
where
  "manifestId" = $1
  and "fileKey" > $2
order by
  "fileKey"
limit
  $3

-- CloudBackupIndexRepository.deleteEntries
delete from "cloud_backup_manifest_entry"
where
  "manifestId" = $1

-- CloudBackupIndexRepository.countAssets
select
  count(*) as "count"
from
  "asset"
where
  "status" in ($1, $2)
  and "isExternal" = $3

-- CloudBackupIndexRepository.listAssets
select
  "id",
  "ownerId",
  "originalPath"
from
  "asset"
where
  "status" in ($1, $2)
  and "isExternal" = $3
  and "id" > $4
order by
  "id"
limit
  $5

-- CloudBackupIndexRepository.listProfileImages
select
  "id",
  "profileImagePath"
from
  "user"
where
  "profileImagePath" != $1
  and "deletedAt" is null
order by
  "id"
