-- NOTE: This file is auto generated by ./sql-generator

-- FrameleafAccountRepository.getLinkByUser
SELECT
  *
FROM
  public.frameleaf_account_link
WHERE
  "userId" = $1::uuid

-- FrameleafAccountRepository.getLinkBySub
SELECT
  *
FROM
  public.frameleaf_account_link
WHERE
  sub = $1

-- FrameleafAccountRepository.countLinks
SELECT
  count(*)::text AS count
FROM
  public.frameleaf_account_link

-- FrameleafAccountRepository.getSession
SELECT
  *
FROM
  public.frameleaf_session
WHERE
  "sessionId" = $1::uuid
