-- NOTE: This file is auto generated by ./sql-generator

-- FrameleafUserLicenseRepository.get
SELECT
  *
FROM
  public.frameleaf_user_license
WHERE
  "userId" = $1::uuid

-- FrameleafUserLicenseRepository.getByKeyHash
SELECT
  *
FROM
  public.frameleaf_user_license
WHERE
  "keySha256" = $1
