-- NOTE: This file is auto generated by ./sql-generator

-- FrameleafAccountRepository.getLinkByUser
SELECT
  *
FROM
  immich_fork.frameleaf_account_link
WHERE
  "userId" = $1::uuid

-- FrameleafAccountRepository.getLinkBySub
SELECT
  *
FROM
  immich_fork.frameleaf_account_link
WHERE
  sub = $1

-- FrameleafAccountRepository.getAccess
SELECT
  access
FROM
  immich_fork.frameleaf_account_link
WHERE
  "userId" = $1::uuid

-- FrameleafAccountRepository.getUserIdsByAccess
SELECT
  link."userId"
FROM
  immich_fork.frameleaf_account_link link
  INNER JOIN public."user" u ON u.id = link."userId"
  AND u."deletedAt" IS NULL
WHERE
  link.access = $1
ORDER BY
  link."linkedAt",
  link."userId"

-- FrameleafAccountRepository.countLinks
SELECT
  count(*)::text AS count
FROM
  immich_fork.frameleaf_account_link

-- FrameleafAccountRepository.getSession
SELECT
  *
FROM
  immich_fork.frameleaf_session
WHERE
  "sessionId" = $1::uuid
