-- NOTE: This file is auto generated by ./sql-generator

-- FrameleafConsentRepository.getCurrent
SELECT
  *
FROM
  immich_fork.frameleaf_consent
WHERE
  "destinationId" = $1::uuid
  AND "revokedAt" IS NULL
ORDER BY
  "acceptedAt" DESC,
  id DESC
LIMIT
  1

-- FrameleafConsentRepository.getHistory
SELECT
  *
FROM
  immich_fork.frameleaf_consent
WHERE
  "destinationId" = $1::uuid
ORDER BY
  "acceptedAt" DESC,
  id DESC
LIMIT
  50
