-- NOTE: This file is auto generated by ./sql-generator

-- MemoryRepository.statistics
select
  count(*) as "total"
from
  "memory"
where
  "deletedAt" is null
  and "ownerId" = $1
  and exists (
    select
      "memory_asset"."memoriesId"
    from
      "memory_asset"
      inner join "asset" on "asset"."id" = "memory_asset"."assetId"
    where
      "memory_asset"."memoriesId" = "memory"."id"
      and (
        "asset"."visibility" = 'timeline'
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
      )
      and "asset"."deletedAt" is null
      and not (
        exists (
          select
            1
          from
            public.asset as nsfw_asset
          where
            nsfw_asset.id = "asset"."id"
            and nsfw_asset.is_nsfw = true
        )
      )
      and not exists (
        select
          $2 as "one"
        from
          "asset_face"
          inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
          and "person"."ownerId" = "asset"."ownerId"
        where
          "asset_face"."assetId" = "asset"."id"
          and "person"."isHidden" = $3
      )
      and not exists (
        select
          "pet_observation"."assetId"
        from
          "pet_observation"
          inner join "pet" on "pet"."id" = "pet_observation"."petId"
          and "pet"."ownerId" = "asset"."ownerId"
        where
          "pet_observation"."assetId" = "asset"."id"
          and "pet_observation"."state" = 'confirmed'
          and "pet"."isHidden" is true
      )
      and (
        "memory"."type" not in ('birthday', 'person_recap')
        or (
          "memory"."data" ->> 'subject' = 'person'
          and exists (
            select
            from
              "asset_face"
            where
              "asset_face"."assetId" = "asset"."id"
              and "asset_face"."deletedAt" is null
              and "asset_face"."isVisible" = true
              and "asset_face"."personGroupId"::text = "memory"."data" ->> 'subjectId'
          )
        )
        or (
          "memory"."data" ->> 'subject' = 'pet'
          and exists (
            select
            from
              "pet_observation"
            where
              "pet_observation"."assetId" = "asset"."id"
              and "pet_observation"."state" = 'confirmed'
              and "pet_observation"."petId"::text = "memory"."data" ->> 'subjectId'
          )
        )
      )
  )
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
        and (
          "asset"."visibility" = 'timeline'
          and not exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          )
        )
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "asset"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
    )
  )
  and not exists (
    select
      1
    from
      memory_asset as hidden_memory_asset
      inner join asset as hidden_memory_item on hidden_memory_item.id = hidden_memory_asset."assetId"
    where
      hidden_memory_asset."memoriesId" = "memory"."id"
      and (
        not not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "hidden_memory_item"."id"
        )
        or (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "hidden_memory_item"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
      )
  )

-- MemoryRepository.statistics (date filter)
select
  count(*) as "total"
from
  "memory"
where
  (
    "showAt" is null
    or "showAt" <= $1
  )
  and (
    "hideAt" is null
    or "hideAt" >= $2
  )
  and "deletedAt" is null
  and "ownerId" = $3
  and exists (
    select
      "memory_asset"."memoriesId"
    from
      "memory_asset"
      inner join "asset" on "asset"."id" = "memory_asset"."assetId"
    where
      "memory_asset"."memoriesId" = "memory"."id"
      and (
        "asset"."visibility" = 'timeline'
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
      )
      and "asset"."deletedAt" is null
      and not (
        exists (
          select
            1
          from
            public.asset as nsfw_asset
          where
            nsfw_asset.id = "asset"."id"
            and nsfw_asset.is_nsfw = true
        )
      )
      and not exists (
        select
          $4 as "one"
        from
          "asset_face"
          inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
          and "person"."ownerId" = "asset"."ownerId"
        where
          "asset_face"."assetId" = "asset"."id"
          and "person"."isHidden" = $5
      )
      and not exists (
        select
          "pet_observation"."assetId"
        from
          "pet_observation"
          inner join "pet" on "pet"."id" = "pet_observation"."petId"
          and "pet"."ownerId" = "asset"."ownerId"
        where
          "pet_observation"."assetId" = "asset"."id"
          and "pet_observation"."state" = 'confirmed'
          and "pet"."isHidden" is true
      )
      and (
        "memory"."type" not in ('birthday', 'person_recap')
        or (
          "memory"."data" ->> 'subject' = 'person'
          and exists (
            select
            from
              "asset_face"
            where
              "asset_face"."assetId" = "asset"."id"
              and "asset_face"."deletedAt" is null
              and "asset_face"."isVisible" = true
              and "asset_face"."personGroupId"::text = "memory"."data" ->> 'subjectId'
          )
        )
        or (
          "memory"."data" ->> 'subject' = 'pet'
          and exists (
            select
            from
              "pet_observation"
            where
              "pet_observation"."assetId" = "asset"."id"
              and "pet_observation"."state" = 'confirmed'
              and "pet_observation"."petId"::text = "memory"."data" ->> 'subjectId'
          )
        )
      )
  )
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
        and (
          "asset"."visibility" = 'timeline'
          and not exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          )
        )
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "asset"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
    )
  )
  and not exists (
    select
      1
    from
      memory_asset as hidden_memory_asset
      inner join asset as hidden_memory_item on hidden_memory_item.id = hidden_memory_asset."assetId"
    where
      hidden_memory_asset."memoriesId" = "memory"."id"
      and (
        not not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "hidden_memory_item"."id"
        )
        or (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "hidden_memory_item"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
      )
  )

-- MemoryRepository.search
select
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and (
            "asset"."visibility" = 'timeline'
            and not exists (
              select
                1
              from
                asset_lock
              where
                asset_lock."assetId" = "asset"."id"
            )
          )
          and "asset"."deletedAt" is null
          and not (
            exists (
              select
                1
              from
                public.asset as nsfw_asset
              where
                nsfw_asset.id = "asset"."id"
                and nsfw_asset.is_nsfw = true
            )
          )
          and not exists (
            select
              $1 as "one"
            from
              "asset_face"
              inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
              and "person"."ownerId" = "asset"."ownerId"
            where
              "asset_face"."assetId" = "asset"."id"
              and "person"."isHidden" = $2
          )
          and not exists (
            select
              "pet_observation"."assetId"
            from
              "pet_observation"
              inner join "pet" on "pet"."id" = "pet_observation"."petId"
              and "pet"."ownerId" = "asset"."ownerId"
            where
              "pet_observation"."assetId" = "asset"."id"
              and "pet_observation"."state" = 'confirmed'
              and "pet"."isHidden" is true
          )
          and (
            "memory"."type" not in ('birthday', 'person_recap')
            or (
              "memory"."data" ->> 'subject' = 'person'
              and exists (
                select
                from
                  "asset_face"
                where
                  "asset_face"."assetId" = "asset"."id"
                  and "asset_face"."deletedAt" is null
                  and "asset_face"."isVisible" = true
                  and "asset_face"."personGroupId"::text = "memory"."data" ->> 'subjectId'
              )
            )
            or (
              "memory"."data" ->> 'subject' = 'pet'
              and exists (
                select
                from
                  "pet_observation"
                where
                  "pet_observation"."assetId" = "asset"."id"
                  and "pet_observation"."state" = 'confirmed'
                  and "pet_observation"."petId"::text = "memory"."data" ->> 'subjectId'
              )
            )
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets",
  "memory".*
from
  "memory"
where
  "deletedAt" is null
  and "ownerId" = $3
  and exists (
    select
      "memory_asset"."memoriesId"
    from
      "memory_asset"
      inner join "asset" on "asset"."id" = "memory_asset"."assetId"
    where
      "memory_asset"."memoriesId" = "memory"."id"
      and (
        "asset"."visibility" = 'timeline'
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
      )
      and "asset"."deletedAt" is null
      and not (
        exists (
          select
            1
          from
            public.asset as nsfw_asset
          where
            nsfw_asset.id = "asset"."id"
            and nsfw_asset.is_nsfw = true
        )
      )
      and not exists (
        select
          $4 as "one"
        from
          "asset_face"
          inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
          and "person"."ownerId" = "asset"."ownerId"
        where
          "asset_face"."assetId" = "asset"."id"
          and "person"."isHidden" = $5
      )
      and not exists (
        select
          "pet_observation"."assetId"
        from
          "pet_observation"
          inner join "pet" on "pet"."id" = "pet_observation"."petId"
          and "pet"."ownerId" = "asset"."ownerId"
        where
          "pet_observation"."assetId" = "asset"."id"
          and "pet_observation"."state" = 'confirmed'
          and "pet"."isHidden" is true
      )
      and (
        "memory"."type" not in ('birthday', 'person_recap')
        or (
          "memory"."data" ->> 'subject' = 'person'
          and exists (
            select
            from
              "asset_face"
            where
              "asset_face"."assetId" = "asset"."id"
              and "asset_face"."deletedAt" is null
              and "asset_face"."isVisible" = true
              and "asset_face"."personGroupId"::text = "memory"."data" ->> 'subjectId'
          )
        )
        or (
          "memory"."data" ->> 'subject' = 'pet'
          and exists (
            select
            from
              "pet_observation"
            where
              "pet_observation"."assetId" = "asset"."id"
              and "pet_observation"."state" = 'confirmed'
              and "pet_observation"."petId"::text = "memory"."data" ->> 'subjectId'
          )
        )
      )
  )
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
        and (
          "asset"."visibility" = 'timeline'
          and not exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          )
        )
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "asset"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
    )
  )
  and not exists (
    select
      1
    from
      memory_asset as hidden_memory_asset
      inner join asset as hidden_memory_item on hidden_memory_item.id = hidden_memory_asset."assetId"
    where
      hidden_memory_asset."memoriesId" = "memory"."id"
      and (
        not not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "hidden_memory_item"."id"
        )
        or (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "hidden_memory_item"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
      )
  )
order by
  "showAt" desc nulls last,
  "memoryAt" desc

-- MemoryRepository.search (date filter)
select
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and (
            "asset"."visibility" = 'timeline'
            and not exists (
              select
                1
              from
                asset_lock
              where
                asset_lock."assetId" = "asset"."id"
            )
          )
          and "asset"."deletedAt" is null
          and not (
            exists (
              select
                1
              from
                public.asset as nsfw_asset
              where
                nsfw_asset.id = "asset"."id"
                and nsfw_asset.is_nsfw = true
            )
          )
          and not exists (
            select
              $1 as "one"
            from
              "asset_face"
              inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
              and "person"."ownerId" = "asset"."ownerId"
            where
              "asset_face"."assetId" = "asset"."id"
              and "person"."isHidden" = $2
          )
          and not exists (
            select
              "pet_observation"."assetId"
            from
              "pet_observation"
              inner join "pet" on "pet"."id" = "pet_observation"."petId"
              and "pet"."ownerId" = "asset"."ownerId"
            where
              "pet_observation"."assetId" = "asset"."id"
              and "pet_observation"."state" = 'confirmed'
              and "pet"."isHidden" is true
          )
          and (
            "memory"."type" not in ('birthday', 'person_recap')
            or (
              "memory"."data" ->> 'subject' = 'person'
              and exists (
                select
                from
                  "asset_face"
                where
                  "asset_face"."assetId" = "asset"."id"
                  and "asset_face"."deletedAt" is null
                  and "asset_face"."isVisible" = true
                  and "asset_face"."personGroupId"::text = "memory"."data" ->> 'subjectId'
              )
            )
            or (
              "memory"."data" ->> 'subject' = 'pet'
              and exists (
                select
                from
                  "pet_observation"
                where
                  "pet_observation"."assetId" = "asset"."id"
                  and "pet_observation"."state" = 'confirmed'
                  and "pet_observation"."petId"::text = "memory"."data" ->> 'subjectId'
              )
            )
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets",
  "memory".*
from
  "memory"
where
  (
    "showAt" is null
    or "showAt" <= $3
  )
  and (
    "hideAt" is null
    or "hideAt" >= $4
  )
  and "deletedAt" is null
  and "ownerId" = $5
  and exists (
    select
      "memory_asset"."memoriesId"
    from
      "memory_asset"
      inner join "asset" on "asset"."id" = "memory_asset"."assetId"
    where
      "memory_asset"."memoriesId" = "memory"."id"
      and (
        "asset"."visibility" = 'timeline'
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
      )
      and "asset"."deletedAt" is null
      and not (
        exists (
          select
            1
          from
            public.asset as nsfw_asset
          where
            nsfw_asset.id = "asset"."id"
            and nsfw_asset.is_nsfw = true
        )
      )
      and not exists (
        select
          $6 as "one"
        from
          "asset_face"
          inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
          and "person"."ownerId" = "asset"."ownerId"
        where
          "asset_face"."assetId" = "asset"."id"
          and "person"."isHidden" = $7
      )
      and not exists (
        select
          "pet_observation"."assetId"
        from
          "pet_observation"
          inner join "pet" on "pet"."id" = "pet_observation"."petId"
          and "pet"."ownerId" = "asset"."ownerId"
        where
          "pet_observation"."assetId" = "asset"."id"
          and "pet_observation"."state" = 'confirmed'
          and "pet"."isHidden" is true
      )
      and (
        "memory"."type" not in ('birthday', 'person_recap')
        or (
          "memory"."data" ->> 'subject' = 'person'
          and exists (
            select
            from
              "asset_face"
            where
              "asset_face"."assetId" = "asset"."id"
              and "asset_face"."deletedAt" is null
              and "asset_face"."isVisible" = true
              and "asset_face"."personGroupId"::text = "memory"."data" ->> 'subjectId'
          )
        )
        or (
          "memory"."data" ->> 'subject' = 'pet'
          and exists (
            select
            from
              "pet_observation"
            where
              "pet_observation"."assetId" = "asset"."id"
              and "pet_observation"."state" = 'confirmed'
              and "pet_observation"."petId"::text = "memory"."data" ->> 'subjectId'
          )
        )
      )
  )
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
        and (
          "asset"."visibility" = 'timeline'
          and not exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          )
        )
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "asset"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
    )
  )
  and not exists (
    select
      1
    from
      memory_asset as hidden_memory_asset
      inner join asset as hidden_memory_item on hidden_memory_item.id = hidden_memory_asset."assetId"
    where
      hidden_memory_asset."memoriesId" = "memory"."id"
      and (
        not not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "hidden_memory_item"."id"
        )
        or (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "hidden_memory_item"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
      )
  )
order by
  "showAt" desc nulls last,
  "memoryAt" desc

-- MemoryRepository.search (upcoming filter)
select
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and (
            "asset"."visibility" = 'timeline'
            and not exists (
              select
                1
              from
                asset_lock
              where
                asset_lock."assetId" = "asset"."id"
            )
          )
          and "asset"."deletedAt" is null
          and not (
            exists (
              select
                1
              from
                public.asset as nsfw_asset
              where
                nsfw_asset.id = "asset"."id"
                and nsfw_asset.is_nsfw = true
            )
          )
          and not exists (
            select
              $1 as "one"
            from
              "asset_face"
              inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
              and "person"."ownerId" = "asset"."ownerId"
            where
              "asset_face"."assetId" = "asset"."id"
              and "person"."isHidden" = $2
          )
          and not exists (
            select
              "pet_observation"."assetId"
            from
              "pet_observation"
              inner join "pet" on "pet"."id" = "pet_observation"."petId"
              and "pet"."ownerId" = "asset"."ownerId"
            where
              "pet_observation"."assetId" = "asset"."id"
              and "pet_observation"."state" = 'confirmed'
              and "pet"."isHidden" is true
          )
          and (
            "memory"."type" not in ('birthday', 'person_recap')
            or (
              "memory"."data" ->> 'subject' = 'person'
              and exists (
                select
                from
                  "asset_face"
                where
                  "asset_face"."assetId" = "asset"."id"
                  and "asset_face"."deletedAt" is null
                  and "asset_face"."isVisible" = true
                  and "asset_face"."personGroupId"::text = "memory"."data" ->> 'subjectId'
              )
            )
            or (
              "memory"."data" ->> 'subject' = 'pet'
              and exists (
                select
                from
                  "pet_observation"
                where
                  "pet_observation"."assetId" = "asset"."id"
                  and "pet_observation"."state" = 'confirmed'
                  and "pet_observation"."petId"::text = "memory"."data" ->> 'subjectId'
              )
            )
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets",
  "memory".*
from
  "memory"
where
  "showAt" > $3
  and "deletedAt" is null
  and "ownerId" = $4
  and exists (
    select
      "memory_asset"."memoriesId"
    from
      "memory_asset"
      inner join "asset" on "asset"."id" = "memory_asset"."assetId"
    where
      "memory_asset"."memoriesId" = "memory"."id"
      and (
        "asset"."visibility" = 'timeline'
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
      )
      and "asset"."deletedAt" is null
      and not (
        exists (
          select
            1
          from
            public.asset as nsfw_asset
          where
            nsfw_asset.id = "asset"."id"
            and nsfw_asset.is_nsfw = true
        )
      )
      and not exists (
        select
          $5 as "one"
        from
          "asset_face"
          inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
          and "person"."ownerId" = "asset"."ownerId"
        where
          "asset_face"."assetId" = "asset"."id"
          and "person"."isHidden" = $6
      )
      and not exists (
        select
          "pet_observation"."assetId"
        from
          "pet_observation"
          inner join "pet" on "pet"."id" = "pet_observation"."petId"
          and "pet"."ownerId" = "asset"."ownerId"
        where
          "pet_observation"."assetId" = "asset"."id"
          and "pet_observation"."state" = 'confirmed'
          and "pet"."isHidden" is true
      )
      and (
        "memory"."type" not in ('birthday', 'person_recap')
        or (
          "memory"."data" ->> 'subject' = 'person'
          and exists (
            select
            from
              "asset_face"
            where
              "asset_face"."assetId" = "asset"."id"
              and "asset_face"."deletedAt" is null
              and "asset_face"."isVisible" = true
              and "asset_face"."personGroupId"::text = "memory"."data" ->> 'subjectId'
          )
        )
        or (
          "memory"."data" ->> 'subject' = 'pet'
          and exists (
            select
            from
              "pet_observation"
            where
              "pet_observation"."assetId" = "asset"."id"
              and "pet_observation"."state" = 'confirmed'
              and "pet_observation"."petId"::text = "memory"."data" ->> 'subjectId'
          )
        )
      )
  )
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
        and (
          "asset"."visibility" = 'timeline'
          and not exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          )
        )
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "asset"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
    )
  )
  and not exists (
    select
      1
    from
      memory_asset as hidden_memory_asset
      inner join asset as hidden_memory_item on hidden_memory_item.id = hidden_memory_asset."assetId"
    where
      hidden_memory_asset."memoriesId" = "memory"."id"
      and (
        not not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "hidden_memory_item"."id"
        )
        or (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "hidden_memory_item"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
      )
  )
order by
  "showAt" desc nulls last,
  "memoryAt" desc

-- MemoryRepository.search (not upcoming filter)
select
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and (
            "asset"."visibility" = 'timeline'
            and not exists (
              select
                1
              from
                asset_lock
              where
                asset_lock."assetId" = "asset"."id"
            )
          )
          and "asset"."deletedAt" is null
          and not (
            exists (
              select
                1
              from
                public.asset as nsfw_asset
              where
                nsfw_asset.id = "asset"."id"
                and nsfw_asset.is_nsfw = true
            )
          )
          and not exists (
            select
              $1 as "one"
            from
              "asset_face"
              inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
              and "person"."ownerId" = "asset"."ownerId"
            where
              "asset_face"."assetId" = "asset"."id"
              and "person"."isHidden" = $2
          )
          and not exists (
            select
              "pet_observation"."assetId"
            from
              "pet_observation"
              inner join "pet" on "pet"."id" = "pet_observation"."petId"
              and "pet"."ownerId" = "asset"."ownerId"
            where
              "pet_observation"."assetId" = "asset"."id"
              and "pet_observation"."state" = 'confirmed'
              and "pet"."isHidden" is true
          )
          and (
            "memory"."type" not in ('birthday', 'person_recap')
            or (
              "memory"."data" ->> 'subject' = 'person'
              and exists (
                select
                from
                  "asset_face"
                where
                  "asset_face"."assetId" = "asset"."id"
                  and "asset_face"."deletedAt" is null
                  and "asset_face"."isVisible" = true
                  and "asset_face"."personGroupId"::text = "memory"."data" ->> 'subjectId'
              )
            )
            or (
              "memory"."data" ->> 'subject' = 'pet'
              and exists (
                select
                from
                  "pet_observation"
                where
                  "pet_observation"."assetId" = "asset"."id"
                  and "pet_observation"."state" = 'confirmed'
                  and "pet_observation"."petId"::text = "memory"."data" ->> 'subjectId'
              )
            )
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets",
  "memory".*
from
  "memory"
where
  (
    "showAt" is null
    or "showAt" <= $3
  )
  and "deletedAt" is null
  and "ownerId" = $4
  and exists (
    select
      "memory_asset"."memoriesId"
    from
      "memory_asset"
      inner join "asset" on "asset"."id" = "memory_asset"."assetId"
    where
      "memory_asset"."memoriesId" = "memory"."id"
      and (
        "asset"."visibility" = 'timeline'
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
      )
      and "asset"."deletedAt" is null
      and not (
        exists (
          select
            1
          from
            public.asset as nsfw_asset
          where
            nsfw_asset.id = "asset"."id"
            and nsfw_asset.is_nsfw = true
        )
      )
      and not exists (
        select
          $5 as "one"
        from
          "asset_face"
          inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
          and "person"."ownerId" = "asset"."ownerId"
        where
          "asset_face"."assetId" = "asset"."id"
          and "person"."isHidden" = $6
      )
      and not exists (
        select
          "pet_observation"."assetId"
        from
          "pet_observation"
          inner join "pet" on "pet"."id" = "pet_observation"."petId"
          and "pet"."ownerId" = "asset"."ownerId"
        where
          "pet_observation"."assetId" = "asset"."id"
          and "pet_observation"."state" = 'confirmed'
          and "pet"."isHidden" is true
      )
      and (
        "memory"."type" not in ('birthday', 'person_recap')
        or (
          "memory"."data" ->> 'subject' = 'person'
          and exists (
            select
            from
              "asset_face"
            where
              "asset_face"."assetId" = "asset"."id"
              and "asset_face"."deletedAt" is null
              and "asset_face"."isVisible" = true
              and "asset_face"."personGroupId"::text = "memory"."data" ->> 'subjectId'
          )
        )
        or (
          "memory"."data" ->> 'subject' = 'pet'
          and exists (
            select
            from
              "pet_observation"
            where
              "pet_observation"."assetId" = "asset"."id"
              and "pet_observation"."state" = 'confirmed'
              and "pet_observation"."petId"::text = "memory"."data" ->> 'subjectId'
          )
        )
      )
  )
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
        and (
          "asset"."visibility" = 'timeline'
          and not exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          )
        )
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "asset"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
    )
  )
  and not exists (
    select
      1
    from
      memory_asset as hidden_memory_asset
      inner join asset as hidden_memory_item on hidden_memory_item.id = hidden_memory_asset."assetId"
    where
      hidden_memory_asset."memoriesId" = "memory"."id"
      and (
        not not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "hidden_memory_item"."id"
        )
        or (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "hidden_memory_item"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
      )
  )
order by
  "showAt" desc nulls last,
  "memoryAt" desc

-- MemoryRepository.get
select
  "memory".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and (
            "asset"."visibility" = 'timeline'
            and not exists (
              select
                1
              from
                asset_lock
              where
                asset_lock."assetId" = "asset"."id"
            )
          )
          and "asset"."deletedAt" is null
          and not (
            exists (
              select
                1
              from
                public.asset as nsfw_asset
              where
                nsfw_asset.id = "asset"."id"
                and nsfw_asset.is_nsfw = true
            )
          )
          and not exists (
            select
              $1 as "one"
            from
              "asset_face"
              inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
              and "person"."ownerId" = "asset"."ownerId"
            where
              "asset_face"."assetId" = "asset"."id"
              and "person"."isHidden" = $2
          )
          and not exists (
            select
              "pet_observation"."assetId"
            from
              "pet_observation"
              inner join "pet" on "pet"."id" = "pet_observation"."petId"
              and "pet"."ownerId" = "asset"."ownerId"
            where
              "pet_observation"."assetId" = "asset"."id"
              and "pet_observation"."state" = 'confirmed'
              and "pet"."isHidden" is true
          )
          and (
            "memory"."type" not in ('birthday', 'person_recap')
            or (
              "memory"."data" ->> 'subject' = 'person'
              and exists (
                select
                from
                  "asset_face"
                where
                  "asset_face"."assetId" = "asset"."id"
                  and "asset_face"."deletedAt" is null
                  and "asset_face"."isVisible" = true
                  and "asset_face"."personGroupId"::text = "memory"."data" ->> 'subjectId'
              )
            )
            or (
              "memory"."data" ->> 'subject' = 'pet'
              and exists (
                select
                from
                  "pet_observation"
                where
                  "pet_observation"."assetId" = "asset"."id"
                  and "pet_observation"."state" = 'confirmed'
                  and "pet_observation"."petId"::text = "memory"."data" ->> 'subjectId'
              )
            )
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets"
from
  "memory"
where
  "id" = $3
  and "deletedAt" is null
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
        and (
          "asset"."visibility" = 'timeline'
          and not exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          )
        )
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "asset"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
    )
  )
  and not exists (
    select
      1
    from
      memory_asset as hidden_memory_asset
      inner join asset as hidden_memory_item on hidden_memory_item.id = hidden_memory_asset."assetId"
    where
      hidden_memory_asset."memoriesId" = "memory"."id"
      and (
        not not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "hidden_memory_item"."id"
        )
        or (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "hidden_memory_item"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
      )
  )

-- MemoryRepository.update
update "memory"
set
  "ownerId" = $1,
  "isSaved" = $2
where
  "id" = $3
select
  "memory".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and (
            "asset"."visibility" = 'timeline'
            and not exists (
              select
                1
              from
                asset_lock
              where
                asset_lock."assetId" = "asset"."id"
            )
          )
          and "asset"."deletedAt" is null
          and not (
            exists (
              select
                1
              from
                public.asset as nsfw_asset
              where
                nsfw_asset.id = "asset"."id"
                and nsfw_asset.is_nsfw = true
            )
          )
          and not exists (
            select
              $1 as "one"
            from
              "asset_face"
              inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
              and "person"."ownerId" = "asset"."ownerId"
            where
              "asset_face"."assetId" = "asset"."id"
              and "person"."isHidden" = $2
          )
          and not exists (
            select
              "pet_observation"."assetId"
            from
              "pet_observation"
              inner join "pet" on "pet"."id" = "pet_observation"."petId"
              and "pet"."ownerId" = "asset"."ownerId"
            where
              "pet_observation"."assetId" = "asset"."id"
              and "pet_observation"."state" = 'confirmed'
              and "pet"."isHidden" is true
          )
          and (
            "memory"."type" not in ('birthday', 'person_recap')
            or (
              "memory"."data" ->> 'subject' = 'person'
              and exists (
                select
                from
                  "asset_face"
                where
                  "asset_face"."assetId" = "asset"."id"
                  and "asset_face"."deletedAt" is null
                  and "asset_face"."isVisible" = true
                  and "asset_face"."personGroupId"::text = "memory"."data" ->> 'subjectId'
              )
            )
            or (
              "memory"."data" ->> 'subject' = 'pet'
              and exists (
                select
                from
                  "pet_observation"
                where
                  "pet_observation"."assetId" = "asset"."id"
                  and "pet_observation"."state" = 'confirmed'
                  and "pet_observation"."petId"::text = "memory"."data" ->> 'subjectId'
              )
            )
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets"
from
  "memory"
where
  "id" = $3
  and "deletedAt" is null
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
        and (
          "asset"."visibility" = 'timeline'
          and not exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          )
        )
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "asset"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
    )
  )
  and not exists (
    select
      1
    from
      memory_asset as hidden_memory_asset
      inner join asset as hidden_memory_item on hidden_memory_item.id = hidden_memory_asset."assetId"
    where
      hidden_memory_asset."memoriesId" = "memory"."id"
      and (
        not not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "hidden_memory_item"."id"
        )
        or (
          exists (
            select
              1
            from
              public.asset as nsfw_asset
            where
              nsfw_asset.id = "hidden_memory_item"."id"
              and nsfw_asset.is_nsfw = true
          )
        )
      )
  )

-- MemoryRepository.delete
delete from "memory"
where
  "id" = $1

-- MemoryRepository.getAssetIds
select
  "assetId"
from
  "memory_asset"
where
  "memoriesId" = $1
  and "assetId" in ($2)

-- MemoryRepository.addAssetIds
insert into
  "memory_asset" ("memoriesId", "assetId")
values
  ($1, $2)

-- MemoryRepository.getHiddenItemIds
select
  "asset"."id"
from
  "asset"
where
  "asset"."id" in ($1)
  and (
    not not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or (
      exists (
        select
          1
        from
          public.asset as nsfw_asset
        where
          nsfw_asset.id = "asset"."id"
          and nsfw_asset.is_nsfw = true
      )
    )
  )
