-- NOTE: This file is auto generated by ./sql-generator

-- MlDestinationRepository.getAll
select
  *
from
  "ml_destination"
order by
  "kind" asc,
  "name" asc

-- MlDestinationRepository.getById
select
  *
from
  "ml_destination"
where
  "id" = $1

-- MlDestinationRepository.getByUrl
select
  *
from
  "ml_destination"
where
  "kind" = $1
  and "url" = $2

-- MlDestinationRepository.delete
delete from "ml_destination"
where
  "id" = $1

-- MlDestinationRepository.getRoutes
select
  *
from
  "ml_workload_route"
order by
  "workload" asc

-- MlDestinationRepository.getRoute
select
  *
from
  "ml_workload_route"
where
  "workload" = $1

-- MlDestinationRepository.clearRoute
delete from "ml_workload_route"
where
  "workload" = $1

-- MlDestinationRepository.getCloudModelChoices
select
  *
from
  "ml_cloud_model_choice"
order by
  "modelGroup" asc

-- MlDestinationRepository.getCloudModelChoice
select
  "modelId"
from
  "ml_cloud_model_choice"
where
  "modelGroup" = $1

-- MlDestinationRepository.clearCloudModelChoice
delete from "ml_cloud_model_choice"
where
  "modelGroup" = $1

-- MlDestinationRepository.getSettlements
select
  "cloudJobId",
  "workload",
  "jobName",
  "outcome",
  "costUsd",
  "credits",
  "startedAt",
  "finishedAt"
from
  "ml_workload_accounting"
where
  "destinationId" = $1
  and "cloudJobId" is not null
  and "costUsd" is not null
order by
  "finishedAt" desc
limit
  $2
