-- NOTE: This file is auto generated by ./sql-generator

-- MlDestinationRepository.getAll
select
  *
from
  "ml_destination"
order by
  "kind" asc,
  "name" asc

-- MlDestinationRepository.getById
select
  *
from
  "ml_destination"
where
  "id" = $1

-- MlDestinationRepository.getByUrl
select
  *
from
  "ml_destination"
where
  "kind" = $1
  and "url" = $2

-- MlDestinationRepository.delete
delete from "ml_destination"
where
  "id" = $1

-- MlDestinationRepository.getRoutes
select
  *
from
  "ml_workload_route"
order by
  "workload" asc

-- MlDestinationRepository.getRoute
select
  *
from
  "ml_workload_route"
where
  "workload" = $1

-- MlDestinationRepository.clearRoute
delete from "ml_workload_route"
where
  "workload" = $1
