-- NOTE: This file is auto generated by ./sql-generator

-- SearchRepository.searchMetadata
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  not exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  )
  and "asset"."fileCreatedAt" >= $1
  and "asset_exif"."lensModel" = $2
  and "asset"."ownerId" = any ($3::uuid[])
  and "asset"."isFavorite" = $4
  and "asset"."deletedAt" is null
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $5
offset
  $6

-- SearchRepository.searchStatistics
select
  count(*) as "total"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  not exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  )
  and "asset"."fileCreatedAt" >= $1
  and "asset_exif"."lensModel" = $2
  and "asset"."ownerId" = any ($3::uuid[])
  and "asset"."isFavorite" = $4
  and "asset"."deletedAt" is null

-- SearchRepository.searchRandom
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  not exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  )
  and "asset"."fileCreatedAt" >= $1
  and "asset_exif"."lensModel" = $2
  and "asset"."ownerId" = any ($3::uuid[])
  and "asset"."isFavorite" = $4
  and "asset"."deletedAt" is null
order by
  random()
limit
  $5

-- SearchRepository.searchLargeAssets
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked",
  to_json("asset_exif") as "exifInfo"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  not exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  )
  and "asset"."fileCreatedAt" >= $1
  and "asset_exif"."lensModel" = $2
  and "asset"."ownerId" = any ($3::uuid[])
  and "asset"."isFavorite" = $4
  and "asset"."deletedAt" is null
  and "asset_exif"."fileSizeInByte" > $5
order by
  "asset_exif"."fileSizeInByte" desc
limit
  $6

-- SearchRepository.searchSmart
begin
set
  local hnsw.ef_search = 100
select
  "asset".*,
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
  inner join "smart_search" on "asset"."id" = "smart_search"."assetId"
where
  not exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  )
  and "asset"."fileCreatedAt" >= $1
  and "asset_exif"."lensModel" = $2
  and "asset"."ownerId" = any ($3::uuid[])
  and "asset"."isFavorite" = $4
  and "asset"."deletedAt" is null
order by
  least(
    (smart_search.embedding <=> $5),
    coalesce(
      $6 * (
        select
          embedding <=> $7
        from
          smart_search_description
        where
          "assetId" = asset.id
      ),
      (smart_search.embedding <=> $8)
    )
  ),
  "asset"."id" asc
limit
  $9
offset
  $10
commit

-- SearchRepository.getEmbedding
select
  *
from
  "smart_search"
where
  "assetId" = $1

-- SearchRepository.searchFaces
begin
set
  local hnsw.ef_search = 100
with
  "cte" as (
    select
      "asset_face"."id",
      "asset_face"."personGroupId",
      face_search.embedding <=> $1 as "distance"
    from
      "asset_face"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
      inner join "face_search" on "face_search"."faceId" = "asset_face"."id"
    where
      "asset"."ownerId" in (
        select
          "user"."id"
        from
          "user"
        where
          "user"."clusterGroupId" = $2
      )
      and "asset"."deletedAt" is null
    order by
      "distance"
    limit
      $3
  )
select
  *
from
  "cte"
where
  "cte"."distance" <= $4
rollback

-- SearchRepository.searchPlaces
select
  *
from
  "geodata_places"
where
  f_unaccent (name) %>> f_unaccent ($1)
  or f_unaccent ("admin2Name") %>> f_unaccent ($2)
  or f_unaccent ("admin1Name") %>> f_unaccent ($3)
  or f_unaccent ("alternateNames") %>> f_unaccent ($4)
order by
  coalesce(f_unaccent (name) <->>> f_unaccent ($5), 0.1) + coalesce(
    f_unaccent ("admin2Name") <->>> f_unaccent ($6),
    0.1
  ) + coalesce(
    f_unaccent ("admin1Name") <->>> f_unaccent ($7),
    0.1
  ) + coalesce(
    f_unaccent ("alternateNames") <->>> f_unaccent ($8),
    0.1
  )
limit
  $9

-- SearchRepository.getAssetsByCity
with recursive
  "cte" as (
    (
      select
        "city",
        "assetId"
      from
        "asset_exif"
        inner join "asset" on "asset"."id" = "asset_exif"."assetId"
      where
        "asset"."ownerId" = any ($1::uuid[])
        and (
          "asset"."visibility" = 'timeline'
          and not exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          )
        )
        and "asset"."type" = $2
        and "asset"."deletedAt" is null
      order by
        "city"
      limit
        $3
    )
    union all
    (
      select
        "l"."city",
        "l"."assetId"
      from
        "cte"
        inner join lateral (
          select
            "city",
            "assetId"
          from
            "asset_exif"
            inner join "asset" on "asset"."id" = "asset_exif"."assetId"
          where
            "asset"."ownerId" = any ($4::uuid[])
            and (
              "asset"."visibility" = 'timeline'
              and not exists (
                select
                  1
                from
                  asset_lock
                where
                  asset_lock."assetId" = "asset"."id"
              )
            )
            and "asset"."type" = $5
            and "asset"."deletedAt" is null
            and "asset_exif"."city" > "cte"."city"
          order by
            "city"
          limit
            $6
        ) as "l" on true
    )
  )
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked",
  to_jsonb("asset_exif") as "exifInfo"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
  inner join "cte" on "asset"."id" = "cte"."assetId"
order by
  "asset_exif"."city"

-- SearchRepository.getCityAssetCounts
select
  "asset_exif"."city",
  count(*) as "count"
from
  "asset_exif"
  inner join "asset" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" = 'timeline'
    and not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
  )
  and "asset"."deletedAt" is null
  and "asset_exif"."city" is not null
group by
  "asset_exif"."city"
order by
  "asset_exif"."city"

-- SearchRepository.getVisitedLandmarks
with
  "matched" as (
    select
      "asset_landmark"."assetId",
      "asset_landmark"."landmarkId",
      row_number() over (
        partition by
          asset_landmark."assetId"
        order by
          (landmark."radiusM" > $1),
          landmark.rank desc,
          landmark."radiusM",
          landmark.id
      ) as "position"
    from
      "asset_landmark"
      inner join "landmark" on "landmark"."id" = "asset_landmark"."landmarkId"
      inner join "asset" on "asset"."id" = "asset_landmark"."assetId"
    where
      "asset"."ownerId" = any ($2::uuid[])
      and (
        "asset"."visibility" = 'timeline'
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
      )
      and "asset"."deletedAt" is null
  )
select
  "landmark"."id",
  "landmark"."name",
  "landmark"."kind",
  "landmark"."latitude",
  "landmark"."longitude",
  count(*) as "assetCount",
  min("asset"."localDateTime") as "firstTakenAt",
  max("asset"."localDateTime") as "lastTakenAt",
  (
    array_agg(
      asset.id
      order by
        asset."localDateTime" desc
    )
  ) [1] as "coverAssetId",
  mode() within group (
    order by
      asset_exif.city
  ) as "city",
  mode() within group (
    order by
      asset_exif.state
  ) as "state",
  mode() within group (
    order by
      asset_exif.country
  ) as "country"
from
  "matched"
  inner join "landmark" on "landmark"."id" = "matched"."landmarkId"
  inner join "asset" on "asset"."id" = "matched"."assetId"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
group by
  "landmark"."id"
having
  bool_or(matched.position = 1)
  or landmark."radiusM" > $3
order by
  "assetCount" desc,
  "landmark"."id"

-- SearchRepository.getAssetLandmarks
select
  "landmark"."id",
  "landmark"."name",
  "landmark"."kind"
from
  "asset_landmark"
  inner join "landmark" on "landmark"."id" = "asset_landmark"."landmarkId"
where
  "asset_landmark"."assetId" = $1
order by
  (landmark."radiusM" > $2),
  landmark.rank desc,
  landmark."radiusM",
  landmark.id

-- SearchRepository.getStates
select distinct
  on ("state") "state"
from
  "asset_exif"
  inner join "asset" on "asset"."id" = "asset_exif"."assetId"
where
  "ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" = 'timeline'
    and not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
  )
  and "deletedAt" is null
  and "state" is not null
  and "state" != $2

-- SearchRepository.getCities
select distinct
  on ("city") "city"
from
  "asset_exif"
  inner join "asset" on "asset"."id" = "asset_exif"."assetId"
where
  "ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" = 'timeline'
    and not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
  )
  and "deletedAt" is null
  and "city" is not null
  and "city" != $2

-- SearchRepository.getCameraMakes
select distinct
  on ("make") "make"
from
  "asset_exif"
  inner join "asset" on "asset"."id" = "asset_exif"."assetId"
where
  "ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" = 'timeline'
    and not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
  )
  and "deletedAt" is null
  and "make" is not null
  and "make" != $2

-- SearchRepository.getCameraModels
select distinct
  on ("model") "model"
from
  "asset_exif"
  inner join "asset" on "asset"."id" = "asset_exif"."assetId"
where
  "ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" = 'timeline'
    and not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
  )
  and "deletedAt" is null
  and "model" is not null
  and "model" != $2

-- SearchRepository.getCameraLensModels
select distinct
  on ("lensModel") "lensModel"
from
  "asset_exif"
  inner join "asset" on "asset"."id" = "asset_exif"."assetId"
where
  "ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" = 'timeline'
    and not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
  )
  and "deletedAt" is null
  and "lensModel" is not null
  and "lensModel" != $2

-- SearchRepository.searchMetadataV3 (baseline)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and true
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $5
offset
  $6

-- SearchRepository.searchMetadataV3 (or-mixed-scope)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $1::uuid
  )
  and (
    "asset"."ownerId" = $2::uuid
    or "asset"."deletedAt" is null
  )
  and (
    exists (
      select
      from
        "album_asset"
      where
        "album_asset"."assetId" = "asset"."id"
        and "album_asset"."albumId" = any ($3::uuid[])
    )
    or (
      "asset_exif"."city" = $4
      and (
        "asset"."ownerId" = any ($5::uuid[])
        and (
          "asset"."ownerId" = $6::uuid
          or (
            "asset"."deletedAt" is null
            and "asset"."visibility" in ('timeline', 'hidden')
          )
        )
      )
    )
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $7
offset
  $8

-- SearchRepository.searchMetadataV3 (or-exif-only)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and "asset_exif"."city" = $5
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $6
offset
  $7

-- SearchRepository.searchMetadataV3 (string-eq-null)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and "asset_exif"."city" is null
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $5
offset
  $6

-- SearchRepository.searchMetadataV3 (string-pattern-like)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and f_unaccent ("asset_exif"."description") ilike ('%' || f_unaccent ($5) || '%')
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $6
offset
  $7

-- SearchRepository.searchMetadataV3 (string-pattern-notLike)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and (
    "asset_exif"."description" is null
    or f_unaccent ("asset_exif"."description") not ilike ('%' || f_unaccent ($5) || '%')
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $6
offset
  $7

-- SearchRepository.searchMetadataV3 (string-pattern-startsWith)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and f_unaccent ("asset"."originalFileName") ilike (f_unaccent ($5) || '%')
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $6
offset
  $7

-- SearchRepository.searchMetadataV3 (string-pattern-camera)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and f_unaccent ("asset_exif"."make") ilike ('%' || f_unaccent ($5) || '%')
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $6
offset
  $7

-- SearchRepository.searchMetadataV3 (string-similarity-ocr)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and exists (
    select
    from
      "ocr_search"
    where
      "ocr_search"."assetId" = "asset"."id"
      and f_unaccent (ocr_search.text) %>> f_unaccent ($5)
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $6
offset
  $7

-- SearchRepository.searchMetadataV3 (ids-any)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $1::uuid
  )
  and (
    "asset"."ownerId" = $2::uuid
    or "asset"."deletedAt" is null
  )
  and exists (
    select
    from
      "album_asset"
    where
      "album_asset"."assetId" = "asset"."id"
      and "album_asset"."albumId" = any ($3::uuid[])
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $4
offset
  $5

-- SearchRepository.searchMetadataV3 (ids-all)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and exists (
    select
      "asset_face"."assetId"
    from
      "asset_face"
    where
      "asset_face"."assetId" = "asset"."id"
      and "asset_face"."deletedAt" is null
      and "asset_face"."isVisible" = $5
      and "asset_face"."personGroupId" = any ($6::uuid[])
    group by
      "asset_face"."assetId"
    having
      count(distinct "asset_face"."personGroupId") = $7
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $8
offset
  $9

-- SearchRepository.searchMetadataV3 (ids-all-single)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $1::uuid
  )
  and (
    "asset"."ownerId" = $2::uuid
    or "asset"."deletedAt" is null
  )
  and exists (
    select
    from
      "album_asset"
    where
      "album_asset"."assetId" = "asset"."id"
      and "album_asset"."albumId" = any ($3::uuid[])
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $4
offset
  $5

-- SearchRepository.searchMetadataV3 (ids-none)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and not exists (
    select
    from
      "tag_asset"
      inner join "tag_closure" on "tag_asset"."tagId" = "tag_closure"."id_descendant"
    where
      "tag_asset"."assetId" = "asset"."id"
      and "tag_closure"."id_ancestor" = any ($5::uuid[])
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $6
offset
  $7

-- SearchRepository.searchMetadataV3 (ids-tags-all)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and exists (
    select
      "tag_asset"."assetId"
    from
      "tag_asset"
      inner join "tag_closure" on "tag_asset"."tagId" = "tag_closure"."id_descendant"
    where
      "tag_asset"."assetId" = "asset"."id"
      and "tag_closure"."id_ancestor" = any ($5::uuid[])
    group by
      "tag_asset"."assetId"
    having
      count(distinct "tag_closure"."id_ancestor") = $6
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $7
offset
  $8

-- SearchRepository.searchMetadataV3 (ids-pets-any)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and exists (
    select
    from
      "pet_observation"
      inner join "pet" on "pet"."id" = "pet_observation"."petId"
    where
      "pet_observation"."assetId" = "asset"."id"
      and "pet_observation"."state" = $5
      and "pet"."ownerId" = $6
      and "pet_observation"."petId" = any ($7::uuid[])
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $8
offset
  $9

-- SearchRepository.searchMetadataV3 (ids-pets-all)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and exists (
    select
      "pet_observation"."assetId"
    from
      "pet_observation"
      inner join "pet" on "pet"."id" = "pet_observation"."petId"
    where
      "pet_observation"."assetId" = "asset"."id"
      and "pet_observation"."state" = $5
      and "pet"."ownerId" = $6
      and "pet_observation"."petId" = any ($7::uuid[])
    group by
      "pet_observation"."assetId"
    having
      count(distinct "pet_observation"."petId") = $8
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $9
offset
  $10

-- SearchRepository.searchMetadataV3 (has-albums-false)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and not exists (
    select
    from
      "album_asset"
    where
      "album_asset"."assetId" = "asset"."id"
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $5
offset
  $6

-- SearchRepository.searchMetadataV3 (is-encoded)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and exists (
    select
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $5
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $6
offset
  $7

-- SearchRepository.searchMetadataV3 (number-range)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and (
    "asset_exif"."fileSizeInByte" <= $5
    and "asset_exif"."fileSizeInByte" >= $6
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $7
offset
  $8

-- SearchRepository.searchMetadataV3 (date-eq)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and "asset"."fileCreatedAt" = $5
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $6
offset
  $7

-- SearchRepository.searchMetadataV3 (date-range)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and (
    "asset"."fileCreatedAt" < $5
    and "asset"."fileCreatedAt" >= $6
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $7
offset
  $8

-- SearchRepository.searchMetadataV3 (local-date-range)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and (
    "asset"."localDateTime" < $5
    and "asset"."localDateTime" >= $6
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $7
offset
  $8

-- SearchRepository.searchMetadataV3 (order-fileSize-noExif)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and true
order by
  "asset_exif"."fileSizeInByte" desc nulls last,
  "asset"."id" desc
limit
  $5
offset
  $6

-- SearchRepository.searchMetadataV3 (order-rating-withExif)
select
  to_json("asset_exif") as "exifInfo",
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and true
order by
  "asset_exif"."rating" asc nulls last,
  "asset"."id" asc
limit
  $5
offset
  $6

-- SearchRepository.searchMetadataV3 (or-branches)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and (
    "asset"."isFavorite" = $5
    or exists (
      select
      from
        "asset_face"
      where
        "asset_face"."assetId" = "asset"."id"
        and "asset_face"."deletedAt" is null
        and "asset_face"."isVisible" = $6
        and "asset_face"."personGroupId" = any ($7::uuid[])
    )
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $8
offset
  $9

-- SearchRepository.searchMetadataV3 (or-with-top-level)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $1::uuid
  )
  and (
    "asset"."ownerId" = $2::uuid
    or "asset"."deletedAt" is null
  )
  and (
    "asset"."fileCreatedAt" < $3
    and "asset"."fileCreatedAt" >= $4
    and (
      (
        "asset"."isFavorite" = $5
        and (
          "asset"."ownerId" = any ($6::uuid[])
          and (
            "asset"."ownerId" = $7::uuid
            or (
              "asset"."deletedAt" is null
              and "asset"."visibility" in ('timeline', 'hidden')
            )
          )
        )
      )
      or exists (
        select
        from
          "album_asset"
        where
          "album_asset"."assetId" = "asset"."id"
          and "album_asset"."albumId" = any ($8::uuid[])
      )
    )
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $9
offset
  $10

-- SearchRepository.searchMetadataV3 (cursor-offset)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and "asset"."isFavorite" = $5
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $6
offset
  $7

-- SearchRepository.searchRandomV3 (baseline)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and true
order by
  random()
limit
  $5

-- SearchRepository.searchRandomV3 (with-filter)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and "asset"."isFavorite" = $5
order by
  random()
limit
  $6

-- SearchRepository.searchSmartV3 (baseline)
begin
set
  local hnsw.ef_search = 100
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
  inner join "smart_search" on "asset"."id" = "smart_search"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and true
order by
  least(
    (smart_search.embedding <=> $5),
    coalesce(
      $6 * (
        select
          embedding <=> $7
        from
          smart_search_description
        where
          "assetId" = asset.id
      ),
      (smart_search.embedding <=> $8)
    )
  ),
  "asset"."id" asc
limit
  $9
offset
  $10
commit

-- SearchRepository.searchSmartV3 (with-filter)
begin
set
  local hnsw.ef_search = 100
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
  inner join "smart_search" on "asset"."id" = "smart_search"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and (
    "asset"."fileCreatedAt" < $5
    and "asset"."fileCreatedAt" >= $6
  )
order by
  least(
    (smart_search.embedding <=> $7),
    coalesce(
      $8 * (
        select
          embedding <=> $9
        from
          smart_search_description
        where
          "assetId" = asset.id
      ),
      (smart_search.embedding <=> $10)
    )
  ),
  "asset"."id" asc
limit
  $11
offset
  $12
commit

-- SearchRepository.searchSmartV3 (cursor-offset)
begin
set
  local hnsw.ef_search = 100
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isFavorite",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  ) as "isLocked"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
  inner join "smart_search" on "asset"."id" = "smart_search"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and true
order by
  least(
    (smart_search.embedding <=> $5),
    coalesce(
      $6 * (
        select
          embedding <=> $7
        from
          smart_search_description
        where
          "assetId" = asset.id
      ),
      (smart_search.embedding <=> $8)
    )
  ),
  "asset"."id" asc
limit
  $9
offset
  $10
commit

-- SearchRepository.searchStatisticsV3 (baseline)
select
  count(*) as "total"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and true

-- SearchRepository.searchStatisticsV3 (with-filter)
select
  count(*) as "total"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and (
    "asset_exif"."fileSizeInByte" >= $5
    and "asset"."fileCreatedAt" < $6
    and "asset"."fileCreatedAt" >= $7
  )

-- SearchRepository.searchStatisticsV3 (with-or)
select
  count(*) as "total"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = any ($1::uuid[])
    and (
      "asset"."ownerId" = $2::uuid
      or (
        "asset"."deletedAt" is null
        and "asset"."visibility" in ('timeline', 'hidden')
      )
    )
  )
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $3::uuid
  )
  and (
    "asset"."ownerId" = $4::uuid
    or "asset"."deletedAt" is null
  )
  and (
    "asset"."isFavorite" = $5
    or not exists (
      select
      from
        "album_asset"
      where
        "album_asset"."assetId" = "asset"."id"
    )
  )

-- SearchRepository.searchFacets
with
  matched as materialized (
    (
      select
        "asset"."id",
        "asset"."ownerId",
        "asset"."type",
        "asset"."isFavorite",
        "asset"."fileCreatedAt"
      from
        "asset"
      where
        (
          not exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          )
          or "asset"."ownerId" = $1::uuid
        )
        and "asset"."fileCreatedAt" >= $2
        and "asset"."ownerId" = any ($3::uuid[])
        and "asset"."deletedAt" is null
    )
  ),
  facet_rows as (
    select
      $4::text as field,
      m.type::text as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
    group by
      2
    union all
    select
      $5::text as field,
      (
        m."isFavorite"
        and m."ownerId" = $6::uuid
      )::text as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
    group by
      2
    union all
    select
      $7::text as field,
      case
        when e.rating between 1 and 5  then e.rating::text
        else 'unrated'
      end as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      left join asset_exif e on e."assetId" = m.id
    group by
      2
    union all
    select
      $8::text as field,
      nullif(trim("e"."city"), '') as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      inner join asset_exif e on e."assetId" = m.id
    where
      nullif(trim("e"."city"), '') is not null
      and not (m."ownerId" = any ($9::uuid[]))
    group by
      2
    union all
    select
      $10::text as field,
      nullif(trim("e"."country"), '') as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      inner join asset_exif e on e."assetId" = m.id
    where
      nullif(trim("e"."country"), '') is not null
      and not (m."ownerId" = any ($11::uuid[]))
    group by
      2
    union all
    select
      $12::text as field,
      nullif(trim("e"."make"), '') as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      inner join asset_exif e on e."assetId" = m.id
    where
      nullif(trim("e"."make"), '') is not null
      and true
    group by
      2
    union all
    select
      $13::text as field,
      nullif(trim("e"."model"), '') as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      inner join asset_exif e on e."assetId" = m.id
    where
      nullif(trim("e"."model"), '') is not null
      and true
    group by
      2
    union all
    select
      $14::text as field,
      nullif(trim("e"."lensModel"), '') as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      inner join asset_exif e on e."assetId" = m.id
    where
      nullif(trim("e"."lensModel"), '') is not null
      and true
    group by
      2
    union all
    select
      $15::text as field,
      f."personGroupId"::text as value,
      max(nullif(p.name, '')) as label,
      count(distinct m.id) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      inner join asset_face f on f."assetId" = m.id
      and f."deletedAt" is null
      and f."isVisible" is true
      inner join person p on p."personGroupId" = f."personGroupId"
      and p."ownerId" = $16::uuid
      and not p."isHidden"
    where
      not (f."personGroupId" = any ($17::uuid[]))
    group by
      f."personGroupId"
    union all
    select
      $18::text as field,
      t.id::text as value,
      max(t.value) as label,
      count(distinct m.id) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      inner join tag_asset ta on ta."assetId" = m.id
      inner join tag_closure tc on tc.id_descendant = ta."tagId"
      inner join tag t on t.id = tc.id_ancestor
      and t."userId" = $19::uuid
    where
      not exists (
        select
          1
        from
          tag_closure
        where
          tag_closure.id_descendant = "t"."id"
          and tag_closure.id_ancestor = any ($20::uuid[])
      )
    group by
      t.id
    union all
    select
      'total'::text as field,
      null::text as value,
      null::text as label,
      count(*) as count,
      null::text as cover
    from
      matched
  ),
  ranked as (
    select
      *,
      row_number() over (
        partition by
          field
        order by
          count desc,
          value asc
      ) as rank
    from
      facet_rows
  )
select
  field,
  value,
  label,
  count,
  cover
from
  ranked
where
  rank <= $21
order by
  field,
  rank

-- SearchRepository.searchFacetsV3
with
  matched as materialized (
    (
      select
        "asset"."id",
        "asset"."ownerId",
        "asset"."type",
        "asset"."isFavorite",
        "asset"."fileCreatedAt"
      from
        "asset"
        left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
      where
        (
          "asset"."ownerId" = any ($1::uuid[])
          and (
            "asset"."ownerId" = $2::uuid
            or (
              "asset"."deletedAt" is null
              and "asset"."visibility" in ('timeline', 'hidden')
            )
          )
        )
        and (
          not exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          )
          or "asset"."ownerId" = $3::uuid
        )
        and (
          "asset"."ownerId" = $4::uuid
          or "asset"."deletedAt" is null
        )
        and "asset"."isFavorite" = $5
    )
  ),
  facet_rows as (
    select
      $6::text as field,
      m.type::text as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
    group by
      2
    union all
    select
      $7::text as field,
      (
        m."isFavorite"
        and m."ownerId" = $8::uuid
      )::text as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
    group by
      2
    union all
    select
      $9::text as field,
      case
        when e.rating between 1 and 5  then e.rating::text
        else 'unrated'
      end as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      left join asset_exif e on e."assetId" = m.id
    group by
      2
    union all
    select
      $10::text as field,
      nullif(trim("e"."city"), '') as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      inner join asset_exif e on e."assetId" = m.id
    where
      nullif(trim("e"."city"), '') is not null
      and not (m."ownerId" = any ($11::uuid[]))
    group by
      2
    union all
    select
      $12::text as field,
      nullif(trim("e"."country"), '') as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      inner join asset_exif e on e."assetId" = m.id
    where
      nullif(trim("e"."country"), '') is not null
      and not (m."ownerId" = any ($13::uuid[]))
    group by
      2
    union all
    select
      $14::text as field,
      nullif(trim("e"."make"), '') as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      inner join asset_exif e on e."assetId" = m.id
    where
      nullif(trim("e"."make"), '') is not null
      and true
    group by
      2
    union all
    select
      $15::text as field,
      nullif(trim("e"."model"), '') as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      inner join asset_exif e on e."assetId" = m.id
    where
      nullif(trim("e"."model"), '') is not null
      and true
    group by
      2
    union all
    select
      $16::text as field,
      nullif(trim("e"."lensModel"), '') as value,
      null::text as label,
      count(*) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      inner join asset_exif e on e."assetId" = m.id
    where
      nullif(trim("e"."lensModel"), '') is not null
      and true
    group by
      2
    union all
    select
      $17::text as field,
      f."personGroupId"::text as value,
      max(nullif(p.name, '')) as label,
      count(distinct m.id) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      inner join asset_face f on f."assetId" = m.id
      and f."deletedAt" is null
      and f."isVisible" is true
      inner join person p on p."personGroupId" = f."personGroupId"
      and p."ownerId" = $18::uuid
      and not p."isHidden"
    where
      not (f."personGroupId" = any ($19::uuid[]))
    group by
      f."personGroupId"
    union all
    select
      $20::text as field,
      t.id::text as value,
      max(t.value) as label,
      count(distinct m.id) as count,
      (
        array_agg(
          m.id
          order by
            m."fileCreatedAt" desc,
            m.id desc
        )
      ) [1]::text as cover
    from
      matched m
      inner join tag_asset ta on ta."assetId" = m.id
      inner join tag_closure tc on tc.id_descendant = ta."tagId"
      inner join tag t on t.id = tc.id_ancestor
      and t."userId" = $21::uuid
    where
      not exists (
        select
          1
        from
          tag_closure
        where
          tag_closure.id_descendant = "t"."id"
          and tag_closure.id_ancestor = any ($22::uuid[])
      )
    group by
      t.id
    union all
    select
      'total'::text as field,
      null::text as value,
      null::text as label,
      count(*) as count,
      null::text as cover
    from
      matched
  ),
  ranked as (
    select
      *,
      row_number() over (
        partition by
          field
        order by
          count desc,
          value asc
      ) as rank
    from
      facet_rows
  )
select
  field,
  value,
  label,
  count,
  cover
from
  ranked
where
  rank <= $23
order by
  field,
  rank

-- SearchRepository.searchHistogram
with
  matched as (
    (
      select
        "asset"."localDateTime"
      from
        "asset"
      where
        (
          not exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          )
          or "asset"."ownerId" = $1::uuid
        )
        and "asset"."fileCreatedAt" >= $2
        and "asset"."ownerId" = any ($3::uuid[])
        and "asset"."deletedAt" is null
    )
  )
select
  to_char(
    date_trunc(
      'month',
      matched."localDateTime" at time zone 'UTC'
    ),
    'YYYY-MM-DD'
  ) as date,
  count(*) as count
from
  matched
group by
  1
order by
  1

-- SearchRepository.searchHistogramV3
with
  matched as (
    (
      select
        "asset"."localDateTime"
      from
        "asset"
        left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
      where
        (
          "asset"."ownerId" = any ($1::uuid[])
          and (
            "asset"."ownerId" = $2::uuid
            or (
              "asset"."deletedAt" is null
              and "asset"."visibility" in ('timeline', 'hidden')
            )
          )
        )
        and (
          not exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          )
          or "asset"."ownerId" = $3::uuid
        )
        and (
          "asset"."ownerId" = $4::uuid
          or "asset"."deletedAt" is null
        )
        and true
    )
  )
select
  to_char(
    date_trunc('day', matched."localDateTime" at time zone 'UTC'),
    'YYYY-MM-DD'
  ) as date,
  count(*) as count
from
  matched
group by
  1
order by
  1

-- SearchRepository.searchSmartCount
select
  count(*) as total
from
  (
    (
      select
        "asset"."id"
      from
        "asset"
        inner join "smart_search" on "asset"."id" = "smart_search"."assetId"
      where
        (
          not exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          )
          or "asset"."ownerId" = $1::uuid
        )
        and "asset"."fileCreatedAt" >= $2
        and "asset"."ownerId" = any ($3::uuid[])
        and "asset"."deletedAt" is null
      limit
        $4
    )
  ) capped

-- SearchRepository.searchSmartCountV3
select
  count(*) as total
from
  (
    (
      select
        "asset"."id"
      from
        "asset"
        left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
        inner join "smart_search" on "asset"."id" = "smart_search"."assetId"
      where
        (
          "asset"."ownerId" = any ($1::uuid[])
          and (
            "asset"."ownerId" = $2::uuid
            or (
              "asset"."deletedAt" is null
              and "asset"."visibility" in ('timeline', 'hidden')
            )
          )
        )
        and (
          not exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          )
          or "asset"."ownerId" = $3::uuid
        )
        and (
          "asset"."ownerId" = $4::uuid
          or "asset"."deletedAt" is null
        )
        and true
      limit
        $5
    )
  ) capped
