-- NOTE: This file is auto generated by ./sql-generator

-- StackRepository.search
select
  "stack".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*,
          exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          ) as "isLocked",
          to_json("exifInfo") as "exifInfo"
        from
          "asset"
          inner join lateral (
            select
              "asset_exif"."assetId",
              "asset_exif"."autoStackId",
              "asset_exif"."bitsPerSample",
              "asset_exif"."city",
              "asset_exif"."colorspace",
              "asset_exif"."country",
              "asset_exif"."dateTimeOriginal",
              "asset_exif"."description",
              "asset_exif"."exifImageHeight",
              "asset_exif"."exifImageWidth",
              "asset_exif"."exposureTime",
              "asset_exif"."fileSizeInByte",
              "asset_exif"."fNumber",
              "asset_exif"."focalLength",
              "asset_exif"."fps",
              "asset_exif"."iso",
              "asset_exif"."latitude",
              "asset_exif"."lensModel",
              "asset_exif"."livePhotoCID",
              "asset_exif"."longitude",
              "asset_exif"."make",
              "asset_exif"."model",
              "asset_exif"."modifyDate",
              "asset_exif"."orientation",
              "asset_exif"."profileDescription",
              "asset_exif"."projectionType",
              "asset_exif"."rating",
              "asset_exif"."state",
              "asset_exif"."tags",
              "asset_exif"."timeZone"
            from
              "asset_exif"
            where
              "asset_exif"."assetId" = "asset"."id"
          ) as "exifInfo" on true
        where
          "asset"."deletedAt" is null
          and "asset"."stackId" = "stack"."id"
          and (
            "asset"."visibility" in ('archive', 'timeline')
            and not exists (
              select
                1
              from
                asset_lock
              where
                asset_lock."assetId" = "asset"."id"
            )
          )
          and not (
            case
              when "asset"."id" is null then false
              when coalesce(
                (
                  select
                    phase
                  from
                    immich_fork.state
                  where
                    id = 1
                ),
                'inactive'
              ) in ('legacy', 'dual-write', 'ready') then exists (
                select
                  1
                from
                  asset as nsfw_asset
                where
                  nsfw_asset.id = "asset"."id"
                  and nsfw_asset.is_nsfw = true
              )
              when (
                select
                  phase
                from
                  immich_fork.state
                where
                  id = 1
              ) = 'active' then not exists (
                select
                  1
                from
                  immich_fork.asset_privacy as privacy_asset
                where
                  privacy_asset."assetId" = "asset"."id"
                  and privacy_asset."isNsfw" = false
              )
              else false
            end
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets"
from
  "stack"
  inner join "asset" as "primaryAsset" on "primaryAsset"."id" = "stack"."primaryAssetId"
where
  "stack"."ownerId" = $1
  and not exists (
    select
      1 as "exists"
    from
      "asset" as "lockedPrimary"
    where
      "lockedPrimary"."id" = "stack"."primaryAssetId"
      and exists (
        select
          1
        from
          asset_lock
        where
          asset_lock."assetId" = "lockedPrimary"."id"
      )
  )
  and "primaryAsset"."deletedAt" is null
  and not (
    case
      when "primaryAsset"."id" is null then false
      when coalesce(
        (
          select
            phase
          from
            immich_fork.state
          where
            id = 1
        ),
        'inactive'
      ) in ('legacy', 'dual-write', 'ready') then exists (
        select
          1
        from
          asset as nsfw_asset
        where
          nsfw_asset.id = "primaryAsset"."id"
          and nsfw_asset.is_nsfw = true
      )
      when (
        select
          phase
        from
          immich_fork.state
        where
          id = 1
      ) = 'active' then not exists (
        select
          1
        from
          immich_fork.asset_privacy as privacy_asset
        where
          privacy_asset."assetId" = "primaryAsset"."id"
          and privacy_asset."isNsfw" = false
      )
      else false
    end
  )

-- StackRepository.delete
delete from "stack"
where
  "id" = $1::uuid

-- StackRepository.getById
select
  *,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*,
          exists (
            select
              1
            from
              asset_lock
            where
              asset_lock."assetId" = "asset"."id"
          ) as "isLocked",
          (
            select
              coalesce(json_agg(agg), '[]')
            from
              (
                select
                  "tag"."id",
                  "tag"."value",
                  "tag"."createdAt",
                  "tag"."updatedAt",
                  "tag"."color",
                  "tag"."parentId"
                from
                  "tag"
                  inner join "tag_asset" on "tag"."id" = "tag_asset"."tagId"
                where
                  "tag_asset"."assetId" = "asset"."id"
              ) as agg
          ) as "tags",
          to_json("exifInfo") as "exifInfo"
        from
          "asset"
          inner join lateral (
            select
              "asset_exif"."assetId",
              "asset_exif"."autoStackId",
              "asset_exif"."bitsPerSample",
              "asset_exif"."city",
              "asset_exif"."colorspace",
              "asset_exif"."country",
              "asset_exif"."dateTimeOriginal",
              "asset_exif"."description",
              "asset_exif"."exifImageHeight",
              "asset_exif"."exifImageWidth",
              "asset_exif"."exposureTime",
              "asset_exif"."fileSizeInByte",
              "asset_exif"."fNumber",
              "asset_exif"."focalLength",
              "asset_exif"."fps",
              "asset_exif"."iso",
              "asset_exif"."latitude",
              "asset_exif"."lensModel",
              "asset_exif"."livePhotoCID",
              "asset_exif"."longitude",
              "asset_exif"."make",
              "asset_exif"."model",
              "asset_exif"."modifyDate",
              "asset_exif"."orientation",
              "asset_exif"."profileDescription",
              "asset_exif"."projectionType",
              "asset_exif"."rating",
              "asset_exif"."state",
              "asset_exif"."tags",
              "asset_exif"."timeZone"
            from
              "asset_exif"
            where
              "asset_exif"."assetId" = "asset"."id"
          ) as "exifInfo" on true
        where
          "asset"."deletedAt" is null
          and "asset"."stackId" = "stack"."id"
          and (
            "asset"."visibility" in ('archive', 'timeline')
            and not exists (
              select
                1
              from
                asset_lock
              where
                asset_lock."assetId" = "asset"."id"
            )
          )
          and not (
            case
              when "asset"."id" is null then false
              when coalesce(
                (
                  select
                    phase
                  from
                    immich_fork.state
                  where
                    id = 1
                ),
                'inactive'
              ) in ('legacy', 'dual-write', 'ready') then exists (
                select
                  1
                from
                  asset as nsfw_asset
                where
                  nsfw_asset.id = "asset"."id"
                  and nsfw_asset.is_nsfw = true
              )
              when (
                select
                  phase
                from
                  immich_fork.state
                where
                  id = 1
              ) = 'active' then not exists (
                select
                  1
                from
                  immich_fork.asset_privacy as privacy_asset
                where
                  privacy_asset."assetId" = "asset"."id"
                  and privacy_asset."isNsfw" = false
              )
              else false
            end
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets"
from
  "stack"
  inner join "asset" as "primaryAsset" on "primaryAsset"."id" = "stack"."primaryAssetId"
where
  "id" = $1::uuid
  and not exists (
    select
      1 as "exists"
    from
      "asset" as "lockedPrimary"
    where
      "lockedPrimary"."id" = "stack"."primaryAssetId"
      and exists (
        select
          1
        from
          asset_lock
        where
          asset_lock."assetId" = "lockedPrimary"."id"
      )
  )
  and "primaryAsset"."deletedAt" is null
  and not (
    case
      when "primaryAsset"."id" is null then false
      when coalesce(
        (
          select
            phase
          from
            immich_fork.state
          where
            id = 1
        ),
        'inactive'
      ) in ('legacy', 'dual-write', 'ready') then exists (
        select
          1
        from
          asset as nsfw_asset
        where
          nsfw_asset.id = "primaryAsset"."id"
          and nsfw_asset.is_nsfw = true
      )
      when (
        select
          phase
        from
          immich_fork.state
        where
          id = 1
      ) = 'active' then not exists (
        select
          1
        from
          immich_fork.asset_privacy as privacy_asset
        where
          privacy_asset."assetId" = "primaryAsset"."id"
          and privacy_asset."isNsfw" = false
      )
      else false
    end
  )

-- StackRepository.getForAssetRemoval
select
  "stackId" as "id",
  "stack"."primaryAssetId"
from
  "asset"
  left join "stack" on "stack"."id" = "asset"."stackId"
where
  "asset"."id" = $1

-- StackRepository.merge
begin
update "asset"
set
  "stackId" = $1
where
  "asset"."stackId" = $2
select
  member.id
from
  asset as member
where
  member."stackId" = any ($1::uuid[])
union
select
  member."livePhotoVideoId"
from
  asset as member
where
  member."stackId" = any ($2::uuid[])
  and member."livePhotoVideoId" is not null
with
  source as (
    select distinct
      on (asset."stackId") asset."stackId",
      asset_lock."reason",
      asset_lock."lockedBy"
    from
      asset_lock
      inner join asset on asset.id = asset_lock."assetId"
      inner join stack on stack.id = asset."stackId"
    where
      asset."stackId" = any ($1::uuid[])
    order by
      asset."stackId",
      (asset.id = stack."primaryAssetId") desc,
      asset_lock."lockedAt"
  ),
  target as (
    select
      member.id,
      source."reason",
      source."lockedBy"
    from
      asset as member
      inner join source on source."stackId" = member."stackId"
    union
    select
      member."livePhotoVideoId" as id,
      source."reason",
      source."lockedBy"
    from
      asset as member
      inner join source on source."stackId" = member."stackId"
    where
      member."livePhotoVideoId" is not null
  )
insert into
  asset_lock ("assetId", "reason", "lockedBy")
select
  target.id,
  target."reason",
  target."lockedBy"
from
  target
on conflict ("assetId") do nothing
returning
  "assetId"
commit
