-- NOTE: This file is auto generated by ./sql-generator

-- TrashRepository.restore
update "asset"
set
  "status" = $1,
  "deletedAt" = $2
where
  "ownerId" = $3
  and "status" = $4
  and not exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  )

-- TrashRepository.empty
update "asset"
set
  "status" = $1
where
  "ownerId" = $2
  and "status" = $3
  and not exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  )

-- TrashRepository.restoreAll
update "asset"
set
  "status" = $1,
  "deletedAt" = $2
where
  "status" = $3
  and "id" in ($4)
