-- NOTE: This file is auto generated by ./sql-generator

-- TrashRepository.restoreAll
update "asset"
set
  "status" = $1,
  "deletedAt" = $2
where
  "status" = $3
  and "id" in ($4)
returning
  "id"
