-- NOTE: This file is auto generated by ./sql-generator

-- TrashRepository.getSyncStates
select
  "asset"."id" as "assetId",
  jsonb_build_object(
    'assetId',
    asset.id,
    'deletedAt',
    asset."deletedAt",
    'status',
    asset.status,
    'isOffline',
    asset."isOffline"
  ) as "data"
from
  "asset"
where
  "asset"."ownerId" = $1::uuid
  and "asset"."deletedAt" is not null
  and "asset"."status" != $2
  and "asset"."visibility" != $3
  and not exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  )
order by
  "asset"."deletedAt" desc,
  "asset"."id" desc

-- TrashRepository.restoreAll
update "asset"
set
  "status" = $1,
  "deletedAt" = $2
where
  "status" = $3
  and "id" in ($4)
returning
  "id"
