-- NOTE: This file is auto generated by ./sql-generator

-- UserRepository.get
select
  "id",
  "name",
  "email",
  "avatarColor",
  "profileImagePath",
  "profileChangedAt",
  "clusterGroupId",
  "createdAt",
  "updatedAt",
  "deletedAt",
  "isAdmin",
  "status",
  "oauthId",
  "profileImagePath",
  "shouldChangePassword",
  "storageLabel",
  "quotaSizeInBytes",
  "quotaUsageInBytes",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "user_metadata"."key",
          "user_metadata"."value"
        from
          "user_metadata"
        where
          "user"."id" = "user_metadata"."userId"
      ) as agg
  ) as "metadata"
from
  "user"
where
  "user"."id" = $1
  and "user"."deletedAt" is null

-- UserRepository.getAdmin
select
  "id",
  "name",
  "email",
  "avatarColor",
  "profileImagePath",
  "profileChangedAt",
  "clusterGroupId",
  "createdAt",
  "updatedAt",
  "deletedAt",
  "isAdmin",
  "status",
  "oauthId",
  "profileImagePath",
  "shouldChangePassword",
  "storageLabel",
  "quotaSizeInBytes",
  "quotaUsageInBytes",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "user_metadata"."key",
          "user_metadata"."value"
        from
          "user_metadata"
        where
          "user"."id" = "user_metadata"."userId"
      ) as agg
  ) as "metadata"
from
  "user"
where
  "user"."isAdmin" = $1
  and "user"."deletedAt" is null

-- UserRepository.getAdmins
select
  "id",
  "name",
  "email",
  "avatarColor",
  "profileImagePath",
  "profileChangedAt",
  "clusterGroupId",
  "createdAt",
  "updatedAt",
  "deletedAt",
  "isAdmin",
  "status",
  "oauthId",
  "profileImagePath",
  "shouldChangePassword",
  "storageLabel",
  "quotaSizeInBytes",
  "quotaUsageInBytes",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "user_metadata"."key",
          "user_metadata"."value"
        from
          "user_metadata"
        where
          "user"."id" = "user_metadata"."userId"
      ) as agg
  ) as "metadata"
from
  "user"
where
  "user"."isAdmin" = $1
  and "user"."deletedAt" is null
order by
  "user"."createdAt" asc

-- UserRepository.getFileSamples
select
  "id",
  "profileImagePath"
from
  "user"
where
  "profileImagePath" != ''
limit
  3

-- UserRepository.hasAdmin
select
  "user"."id"
from
  "user"
where
  "user"."isAdmin" = $1
  and "user"."deletedAt" is null

-- UserRepository.getForPinCode
select
  "user"."pinCode",
  "user"."password"
from
  "user"
where
  "user"."id" = $1
  and "user"."deletedAt" is null

-- UserRepository.getForChangePassword
select
  "user"."id",
  "user"."password"
from
  "user"
where
  "user"."id" = $1
  and "user"."deletedAt" is null

-- UserRepository.getByEmail
select
  "id",
  "name",
  "email",
  "avatarColor",
  "profileImagePath",
  "profileChangedAt",
  "clusterGroupId",
  "createdAt",
  "updatedAt",
  "deletedAt",
  "isAdmin",
  "status",
  "oauthId",
  "profileImagePath",
  "shouldChangePassword",
  "storageLabel",
  "quotaSizeInBytes",
  "quotaUsageInBytes",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "user_metadata"."key",
          "user_metadata"."value"
        from
          "user_metadata"
        where
          "user"."id" = "user_metadata"."userId"
      ) as agg
  ) as "metadata"
from
  "user"
where
  "email" = $1
  and "user"."deletedAt" is null

-- UserRepository.getByStorageLabel
select
  "id",
  "name",
  "email",
  "avatarColor",
  "profileImagePath",
  "profileChangedAt",
  "clusterGroupId",
  "createdAt",
  "updatedAt",
  "deletedAt",
  "isAdmin",
  "status",
  "oauthId",
  "profileImagePath",
  "shouldChangePassword",
  "storageLabel",
  "quotaSizeInBytes",
  "quotaUsageInBytes"
from
  "user"
where
  "user"."storageLabel" = $1
  and "user"."deletedAt" is null

-- UserRepository.getByOAuthId
select
  "id",
  "name",
  "email",
  "avatarColor",
  "profileImagePath",
  "profileChangedAt",
  "clusterGroupId",
  "createdAt",
  "updatedAt",
  "deletedAt",
  "isAdmin",
  "status",
  "oauthId",
  "profileImagePath",
  "shouldChangePassword",
  "storageLabel",
  "quotaSizeInBytes",
  "quotaUsageInBytes",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "user_metadata"."key",
          "user_metadata"."value"
        from
          "user_metadata"
        where
          "user"."id" = "user_metadata"."userId"
      ) as agg
  ) as "metadata"
from
  "user"
where
  "user"."oauthId" = $1
  and "user"."deletedAt" is null

-- UserRepository.getDeletedAfter
select
  "id"
from
  "user"
where
  "user"."deletedAt" < $1

-- UserRepository.getList (with deleted)
select
  "id",
  "name",
  "email",
  "avatarColor",
  "profileImagePath",
  "profileChangedAt",
  "clusterGroupId",
  "createdAt",
  "updatedAt",
  "deletedAt",
  "isAdmin",
  "status",
  "oauthId",
  "profileImagePath",
  "shouldChangePassword",
  "storageLabel",
  "quotaSizeInBytes",
  "quotaUsageInBytes",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "user_metadata"."key",
          "user_metadata"."value"
        from
          "user_metadata"
        where
          "user"."id" = "user_metadata"."userId"
      ) as agg
  ) as "metadata"
from
  "user"
order by
  "createdAt" desc

-- UserRepository.getList (without deleted)
select
  "id",
  "name",
  "email",
  "avatarColor",
  "profileImagePath",
  "profileChangedAt",
  "clusterGroupId",
  "createdAt",
  "updatedAt",
  "deletedAt",
  "isAdmin",
  "status",
  "oauthId",
  "profileImagePath",
  "shouldChangePassword",
  "storageLabel",
  "quotaSizeInBytes",
  "quotaUsageInBytes",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "user_metadata"."key",
          "user_metadata"."value"
        from
          "user_metadata"
        where
          "user"."id" = "user_metadata"."userId"
      ) as agg
  ) as "metadata"
from
  "user"
where
  "user"."deletedAt" is null
order by
  "createdAt" desc

-- UserRepository.hasLockedProfileImageSource
select
  "user"."id"
from
  "user"
where
  "user"."id" = $1::uuid
  and exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "user"."profileImageAssetId"
  )

-- UserRepository.getLockedProfileImageSources
select
  "user"."id",
  "user"."profileImagePath",
  "user"."profileImageAssetId"
from
  "user"
where
  "user"."profileImageAssetId" is not null
  and exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "user"."profileImageAssetId"
  )
  and "user"."deletedAt" is null

-- UserRepository.getProfileImageReplacement
SELECT
  to_regclass('immich_fork.state')::text AS "stateTable"
SELECT
  phase
FROM
  immich_fork.state
WHERE
  id = 1
select
  "asset"."id",
  "asset_file"."path"
from
  "asset"
  inner join "asset_file" on "asset_file"."assetId" = "asset"."id"
  and "asset_file"."type" = 'preview'
where
  "asset"."ownerId" = $1::uuid
  and "asset"."type" = 'IMAGE'
  and "asset"."status" = 'active'
  and "asset"."visibility" = 'timeline'
  and not exists (
    select
      1
    from
      asset_lock
    where
      asset_lock."assetId" = "asset"."id"
  )
  and "asset"."deletedAt" is null
  and not case
    when "asset"."id" is null then false
    when coalesce(
      (
        select
          phase
        from
          immich_fork.state
        where
          id = 1
      ),
      'inactive'
    ) in ('legacy', 'dual-write', 'ready') then exists (
      select
        1
      from
        asset as nsfw_asset
      where
        nsfw_asset.id = "asset"."id"
        and nsfw_asset.is_nsfw = true
    )
    when (
      select
        phase
      from
        immich_fork.state
      where
        id = 1
    ) = 'active' then not exists (
      select
        1
      from
        immich_fork.asset_privacy as privacy_asset
      where
        privacy_asset."assetId" = "asset"."id"
        and privacy_asset."isNsfw" = false
    )
    else false
  end
order by
  coalesce(
    (
      select
        best_photo.score
      from
        "public"."asset_best_photo_score" as best_photo
      where
        best_photo."assetId" = "asset"."id"
        and best_photo.score >= 0.9
    ),
    -1
  ) desc,
  "asset"."fileCreatedAt" desc,
  "asset_file"."isEdited" desc
limit
  $2

-- UserRepository.replaceLockedProfileImage
update "user"
set
  "profileImagePath" = $1,
  "profileImageAssetId" = $2,
  "profileChangedAt" = $3
where
  "user"."id" = $4::uuid
  and "user"."profileImageAssetId" = $5::uuid

-- UserRepository.getUserStats
select
  "user"."id" as "userId",
  "user"."name" as "userName",
  "user"."quotaSizeInBytes",
  count(*) filter (
    where
      (
        "asset"."type" = 'IMAGE'
        and "asset"."visibility" != 'hidden'
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
      )
  ) as "photos",
  count(*) filter (
    where
      (
        "asset"."type" = 'VIDEO'
        and "asset"."visibility" != 'hidden'
        and not exists (
          select
            1
          from
            asset_lock
          where
            asset_lock."assetId" = "asset"."id"
        )
      )
  ) as "videos",
  coalesce(
    sum("asset_exif"."fileSizeInByte") filter (
      where
        "asset"."libraryId" is null
    ),
    0
  ) as "usage",
  coalesce(
    sum("asset_exif"."fileSizeInByte") filter (
      where
        (
          "asset"."libraryId" is null
          and "asset"."type" = 'IMAGE'
        )
    ),
    0
  ) as "usagePhotos",
  coalesce(
    sum("asset_exif"."fileSizeInByte") filter (
      where
        (
          "asset"."libraryId" is null
          and "asset"."type" = 'VIDEO'
        )
    ),
    0
  ) as "usageVideos"
from
  "user"
  left join "asset" on "asset"."ownerId" = "user"."id"
  and "asset"."deletedAt" is null
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
group by
  "user"."id"
order by
  "user"."createdAt" asc

-- UserRepository.getCount
select
  count(*) as "count"
from
  "user"
where
  "user"."deletedAt" is null

-- UserRepository.updateUsage
update "user"
set
  "quotaUsageInBytes" = "quotaUsageInBytes" + $1,
  "updatedAt" = $2
where
  "id" = $3::uuid
  and "user"."deletedAt" is null

-- UserRepository.syncUsage
update "user"
set
  "quotaUsageInBytes" = (
    select
      coalesce(sum("asset_exif"."fileSizeInByte"), 0) as "usage"
    from
      "asset"
      left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
    where
      "asset"."libraryId" is null
      and "asset"."ownerId" = "user"."id"
  ),
  "updatedAt" = $1
where
  "user"."deletedAt" is null
  and "user"."id" = $2::uuid
