-- NOTE: This file is auto generated by ./sql-generator

-- VideoMomentRepository.getFrameEmbedding
select
  "video_moment_frame"."assetId",
  "video_moment_frame_embedding"."embedding",
  "video_moment_frame_embedding"."modelName"
from
  "video_moment_frame_embedding"
  inner join "video_moment_frame" on "video_moment_frame"."id" = "video_moment_frame_embedding"."frameId"
where
  "video_moment_frame_embedding"."frameId" = $1::uuid

-- VideoMomentRepository.searchFrames
begin
set
  local vchordrq.probes = 1
select
  "video_moment_frame"."assetId",
  "video_moment_frame"."id" as "frameId",
  "video_moment"."id" as "momentId",
  "video_moment_frame"."timestampMs",
  "video_moment"."caption",
  video_moment_frame_embedding.embedding <=> $1 as "distance"
from
  "video_moment_frame_embedding"
  inner join "video_moment_frame" on "video_moment_frame"."id" = "video_moment_frame_embedding"."frameId"
  inner join "asset" on "asset"."id" = "video_moment_frame"."assetId"
  left join "video_moment" on "video_moment"."frameId" = "video_moment_frame"."id"
  and "video_moment"."source" = $2
where
  "video_moment_frame_embedding"."modelName" = $3
  and "asset"."ownerId" = $4::uuid
  and "asset"."status" = $5
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ($6, $7)
  and (
    not exists (
      select
        1
      from
        asset_lock
      where
        asset_lock."assetId" = "asset"."id"
    )
    or "asset"."ownerId" = $8::uuid
  )
  and "video_moment_frame_embedding"."frameId" != $9::uuid
order by
  video_moment_frame_embedding.embedding <=> $10
limit
  $11
commit
