-- NOTE: This file is auto generated by ./sql-generator

-- WorkflowRepository.search
select
  "workflow_definition"."definition",
  "workflow"."id",
  "workflow"."name",
  "workflow"."description",
  "workflow"."trigger",
  "workflow"."enabled",
  "workflow"."createdAt",
  "workflow"."updatedAt",
  "workflow"."logging",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "workflow_step"."id",
          "plugin"."name" as "pluginName",
          "plugin_method"."name" as "methodName",
          "workflow_step"."config",
          "workflow_step"."enabled"
        from
          "workflow_step"
          inner join "plugin_method" on "plugin_method"."id" = "workflow_step"."pluginMethodId"
          inner join "plugin" on "plugin"."id" = "plugin_method"."pluginId"
        where
          "workflow"."id" = "workflow_step"."workflowId"
        order by
          "workflow_step"."order" asc
      ) as agg
  ) as "steps"
from
  "workflow"
  left join "workflow_definition" on "workflow_definition"."workflowId" = "workflow"."id"
order by
  "workflow"."createdAt" desc

-- WorkflowRepository.get
select
  "workflow_definition"."definition",
  "workflow"."id",
  "workflow"."name",
  "workflow"."description",
  "workflow"."trigger",
  "workflow"."enabled",
  "workflow"."createdAt",
  "workflow"."updatedAt",
  "workflow"."logging",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "workflow_step"."id",
          "plugin"."name" as "pluginName",
          "plugin_method"."name" as "methodName",
          "workflow_step"."config",
          "workflow_step"."enabled"
        from
          "workflow_step"
          inner join "plugin_method" on "plugin_method"."id" = "workflow_step"."pluginMethodId"
          inner join "plugin" on "plugin"."id" = "plugin_method"."pluginId"
        where
          "workflow"."id" = "workflow_step"."workflowId"
        order by
          "workflow_step"."order" asc
      ) as agg
  ) as "steps"
from
  "workflow"
  left join "workflow_definition" on "workflow_definition"."workflowId" = "workflow"."id"
where
  "workflow"."id" = $1

-- WorkflowRepository.getForWorkflowRun
SELECT
  EXISTS (
    SELECT
      1
    FROM
      information_schema.columns
    WHERE
      table_schema = 'public'
      AND table_name = 'plugin_method'
      AND column_name = 'allowedHosts'
  ) AS "exists"
select
  "workflow"."id",
  "workflow"."name",
  "workflow"."trigger",
  "workflow"."logging",
  "workflow_definition"."definition",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "workflow_step"."id",
          "workflow_step"."config",
          "workflow_step"."order",
          "plugin_method"."pluginId" as "pluginId",
          "plugin"."name" as "pluginName",
          "plugin"."enabled" as "pluginEnabled",
          "plugin_method"."name" as "methodName",
          "plugin_method"."types" as "types",
          "plugin_method"."hostFunctions",
          "plugin_method"."allowedHosts" as "allowedHosts"
        from
          "workflow_step"
          inner join "plugin_method" on "plugin_method"."id" = "workflow_step"."pluginMethodId"
          inner join "plugin" on "plugin"."id" = "plugin_method"."pluginId"
        where
          "workflow_step"."workflowId" = "workflow"."id"
          and "workflow_step"."enabled" = $1
        order by
          "workflow_step"."order" asc
      ) as agg
  ) as "steps"
from
  "workflow"
  left join "workflow_definition" on "workflow_definition"."workflowId" = "workflow"."id"
where
  "workflow"."id" = $2
  and "workflow"."enabled" = $3

-- WorkflowRepository.getLogs
select
  "workflow_log"."id",
  "workflow_log"."createdAt",
  "workflow_log"."result",
  "workflow_log"."workflowId",
  "workflow_log"."workflowStepId",
  "workflow_log"."triggerDataId",
  "workflow_log"."runId",
  "workflow_log_detail"."attempt",
  "workflow_log_detail"."errorCode",
  "workflow_log_detail"."error",
  (
    select
      to_json(obj)
    from
      (
        select
          "plugin_method"."pluginId",
          "plugin_method"."name" as "methodName",
          "workflow_step"."order"
        from
          "workflow_step"
          inner join "plugin_method" on "plugin_method"."id" = "workflow_step"."pluginMethodId"
        where
          "workflow_step"."id" = "workflow_log"."workflowStepId"
      ) as obj
  ) as "step"
from
  "workflow_log"
  left join "workflow_log_detail" on "workflow_log_detail"."logId" = "workflow_log"."id"
where
  "workflow_log"."workflowId" = $1
order by
  "workflow_log"."createdAt" desc
limit
  $2

-- WorkflowRepository.getLatestRunAttempt
select
  "workflow_log"."runId",
  "workflow_log"."triggerDataId",
  "workflow_log"."result",
  "workflow_log_detail"."attempt"
from
  "workflow_log"
  left join "workflow_log_detail" on "workflow_log_detail"."logId" = "workflow_log"."id"
where
  "workflow_log"."workflowId" = $1
  and "workflow_log"."runId" = $2
order by
  "workflow_log"."createdAt" desc
limit
  $3

-- WorkflowRepository.delete
delete from "workflow"
where
  "id" = $1
