/**
 * FL-135: the email header logo is served by the Frameleaf server itself (web/static/frameleaf,
 * generated by scripts/frameleaf-logo-exports.mjs) from the same external domain the email's links
 * already use, instead of a third-party host.
 */
export const FRAMELEAF_EMAIL_LOGO_PATH = '/frameleaf/frameleaf-logo-light.png';

export const getFrameleafEmailLogoUrl = (baseUrl: string) =>
  `${baseUrl.replace(/\/+$/, '')}${FRAMELEAF_EMAIL_LOGO_PATH}`;
