/**
 * GENERATED FILE — do not edit.
 *
 * Source: studio/dependency-attribution.json
 * Generator: scripts/frameleaf-studio-rights.mjs
 *
 * The reviewed rights decisions for every resource the pinned Studio engine can reach (FL-86,
 * `STU-103`). A use is admitted only when its decision is 'allowed'; the owner's default
 * (FL-146, September 25, 2026) keeps every row blocked until it is approved individually.
 * Enforcement lives in `studio-rights.ts`.
 */

export type StudioRightsDecision = 'allowed' | 'blocked';

export type StudioResourceRights = {
  kind: string;
  license: string | null;
  redistribution: StudioRightsDecision;
  localRuntime: StudioRightsDecision;
  hostedUse: StudioRightsDecision;
};

export const STUDIO_RIGHTS_SOURCE_SHA256 = 'c78ca1c5fd3080676889db9d529149e91b677fa4d1d80c02295a8cbeb2f59dd1';

/** Whether the engine as a whole may be redistributed. False blocks every redistribution. */
export const STUDIO_DISTRIBUTION_APPROVAL = false;

export const studioResourceRights: Readonly<Record<string, StudioResourceRights>> = {
  'asset:lottiefiles': {
    kind: 'asset',
    license: 'Lottie Simple License FL 9.13.21',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'asset:user-import': {
    kind: 'asset',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Abel': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Alfa Slab One': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Almarai': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Anek Telugu': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Anton': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Archivo': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Archivo Black': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Arimo': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Arvo': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Assistant': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Barlow': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Barlow Condensed': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Barlow Semi Condensed': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Bebas Neue': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Bitter': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Bricolage Grotesque': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Bungee': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Cabin': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Cairo': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Caveat': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Changa One': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Comfortaa': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Cormorant Garamond': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Crimson Text': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:DM Sans': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:DM Serif Display': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Dancing Script': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Domine': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Dosis': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:EB Garamond': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Exo 2': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Figtree': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Fira Sans': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Fjalla One': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Google Sans': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Gravitas One': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Heebo': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Hind': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Hind Siliguri': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:IBM Plex Mono': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:IBM Plex Sans': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Inconsolata': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Inter': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Inter Tight': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Josefin Sans': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Jost': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Kanit': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Karla': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Lato': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Lexend': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Lexend Deca': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Libre Baskerville': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Libre Franklin': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Lobster': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Lobster Two': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Lora': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:M PLUS 1p': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:M PLUS Rounded 1c': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Manrope': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Merriweather': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Merriweather Sans': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Montserrat': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Mukta': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Mulish': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Nanum Gothic': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Noto Color Emoji': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Noto Sans': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Noto Sans Arabic': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Noto Sans JP': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Noto Sans KR': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Noto Sans SC': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Noto Sans TC': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Noto Sans Telugu': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Noto Serif': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Noto Serif JP': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Nunito': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Nunito Sans': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Open Sans': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Orbitron': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Oswald': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Outfit': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Overpass': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Oxygen': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:PT Sans': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:PT Sans Narrow': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:PT Serif': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Pacifico': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Playfair Display': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Plus Jakarta Sans': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Poppins': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Prompt': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Public Sans': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Quicksand': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Rajdhani': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Raleway': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Ramabhadra': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Red Hat Display': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Roboto': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Roboto Condensed': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Roboto Flex': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Roboto Mono': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Roboto Slab': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Rubik': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Saira': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Satisfy': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Schibsted Grotesk': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Shadows Into Light': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Share Tech': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Slabo 27px': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Smooch Sans': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Sora': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Source Code Pro': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Source Sans 3': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Source Serif 4': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Space Grotesk': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Tajawal': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Teko': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Titillium Web': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Ubuntu': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Urbanist': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'font:Work Sans': {
    kind: 'font',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:LiquidAI/LFM2.5-VL-450M-ONNX': {
    kind: 'model',
    license: 'other',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:Olicorne/parakeet-tdt-0.6b-v3-smoothquant-onnx': {
    kind: 'model',
    license: 'cc-by-4.0',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:OpenMOSS-Team/MOSS-Audio-Tokenizer-Nano-ONNX': {
    kind: 'model',
    license: 'apache-2.0',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:OpenMOSS-Team/MOSS-TTS-Nano-100M-ONNX': {
    kind: 'model',
    license: 'apache-2.0',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:Xenova/all-MiniLM-L6-v2': {
    kind: 'model',
    license: 'apache-2.0',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:Xenova/clap-htsat-unfused': {
    kind: 'model',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:Xenova/clip-vit-base-patch32': {
    kind: 'model',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:Xenova/musicgen-small': {
    kind: 'model',
    license: 'cc-by-nc-4.0',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:onnx-community/Kokoro-82M-v1.0-ONNX': {
    kind: 'model',
    license: 'apache-2.0',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:onnx-community/gemma-4-E4B-it-ONNX': {
    kind: 'model',
    license: 'apache-2.0',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:onnx-community/whisper-base_timestamped': {
    kind: 'model',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:onnx-community/whisper-large-v3-turbo_timestamped': {
    kind: 'model',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:onnx-community/whisper-small_timestamped': {
    kind: 'model',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:onnx-community/whisper-tiny_timestamped': {
    kind: 'model',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:supertonic-3': {
    kind: 'model',
    license: 'OpenRAIL-M',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'model:walterlow/RIFE_fp32_timestep': {
    kind: 'model',
    license: 'mit',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'runtime:onnx-cdn': {
    kind: 'runtime-code',
    license: 'MIT',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'runtime:whisper-transformers': {
    kind: 'runtime-code',
    license: 'Apache-2.0',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'tool:dolby-artistic-trim': {
    kind: 'tool',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'tool:dolby-portal': {
    kind: 'tool',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-af_alloy': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-af_aoede': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-af_bella': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-af_heart': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-af_jessica': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-af_kore': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-af_nicole': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-af_nova': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-af_river': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-af_sarah': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-af_sky': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-am_adam': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-am_echo': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-am_eric': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-am_fenrir': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-am_liam': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-am_michael': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-am_onyx': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-am_puck': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-am_santa': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-bf_alice': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-bf_emma': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-bf_isabella': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-bf_lily': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-bm_daniel': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-bm_fable': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-bm_george': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-bm_lewis': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-ef_dora': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-em_alex': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-em_santa': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-ff_siwis': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-hf_alpha': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-hf_beta': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-hm_omega': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-hm_psi': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-if_sara': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-im_nicola': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-jf_alpha': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-jf_gongitsune': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-jf_nezumi': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-jf_tebukuro': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-jm_kumo': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-pf_dora': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-pm_alex': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-pm_santa': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-zf_xiaobei': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-zf_xiaoni': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-zf_xiaoxiao': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-zf_xiaoyi': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-zm_yunjian': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-zm_yunxi': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-zm_yunxia': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:kokoro-zm_yunyang': {
    kind: 'voice',
    license: null,
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:supertonic-F1': {
    kind: 'voice',
    license: 'OpenRAIL-M (model; voice applicability unverified)',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:supertonic-F2': {
    kind: 'voice',
    license: 'OpenRAIL-M (model; voice applicability unverified)',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:supertonic-F3': {
    kind: 'voice',
    license: 'OpenRAIL-M (model; voice applicability unverified)',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:supertonic-F4': {
    kind: 'voice',
    license: 'OpenRAIL-M (model; voice applicability unverified)',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:supertonic-F5': {
    kind: 'voice',
    license: 'OpenRAIL-M (model; voice applicability unverified)',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:supertonic-M1': {
    kind: 'voice',
    license: 'OpenRAIL-M (model; voice applicability unverified)',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:supertonic-M2': {
    kind: 'voice',
    license: 'OpenRAIL-M (model; voice applicability unverified)',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:supertonic-M3': {
    kind: 'voice',
    license: 'OpenRAIL-M (model; voice applicability unverified)',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:supertonic-M4': {
    kind: 'voice',
    license: 'OpenRAIL-M (model; voice applicability unverified)',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'voice:supertonic-M5': {
    kind: 'voice',
    license: 'OpenRAIL-M (model; voice applicability unverified)',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'weights:anime4k-3d': {
    kind: 'bundled-weights',
    license: 'MIT',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'weights:anime4k-an': {
    kind: 'bundled-weights',
    license: 'MIT',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
  'weights:anime4k-rl': {
    kind: 'bundled-weights',
    license: 'MIT',
    redistribution: 'blocked',
    localRuntime: 'blocked',
    hostedUse: 'blocked',
  },
};
