/**
 * FL-306: check the published Studio graph protocol against the engine's own answers without the
 * engine. `graph-protocol.mjs` implements the protocol's computable rules from the prose; every
 * engine-generated digest, identity draw and rounding answer in `studio/graph-conformance-v1.json`
 * must agree with it, and every graph there must satisfy `studio/graph-schema-v1.json`.
 *
 * The engine replay itself (`studio/adapters/web/test/graph-conformance.test.ts`) runs in the
 * Studio engine workflow; this check runs in the Scripts unit tests on every pull request, so a
 * hand-edited answer, schema or fixture is caught even where the engine is not built.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import { canonicalJson, envelopeDigest, framesOf, graphDigest, sha256Hex, uuidStream, validate } from './graph-protocol.mjs';

const read = (name) => JSON.parse(readFileSync(new URL(`../${name}`, import.meta.url), 'utf8'));
const fixtures = read('graph-conformance-v1.json');
const schema = read('graph-schema-v1.json');
const catalogue = read('frameleaf-studio-commands.json');
const build = read('engine-build.json');

const graphs = () => [
  ...Object.entries(fixtures.bases).map(([name, base]) => [`base ${name}`, base.graph, base.digest]),
  ...fixtures.cases
    .filter((entry) => entry.expect?.status === 'applied')
    .map((entry) => [entry.id, entry.expect.graph, entry.expect.digest]),
];

test('the fixtures were generated by the pinned engine and every case has an answer', () => {
  assert.equal(fixtures.format, 'frameleaf-studio-graph-conformance');
  assert.equal(fixtures.version, 1);
  assert.deepEqual(fixtures.engine, { name: 'freecut', revision: build.upstreamCommit });
  for (const entry of fixtures.cases) assert.ok(entry.expect, `${entry.id} has no answer`);
  for (const script of fixtures.history) assert.ok(script.expect, `${script.id} has no answer`);
  const ids = fixtures.cases.map((entry) => entry.id);
  assert.equal(new Set(ids).size, ids.length, 'case ids are unique');
});

test('canonical serialisation vectors', () => {
  for (const vector of fixtures.vectors.canonicalJson) {
    assert.equal(canonicalJson(vector.value), vector.canonical, JSON.stringify(vector.value));
    assert.equal(sha256Hex(vector.canonical), vector.sha256);
  }
});

test('identity stream vectors', () => {
  for (const vector of fixtures.vectors.uuids) {
    const next = uuidStream(vector.seed);
    assert.deepEqual(Array.from({ length: vector.count }, () => next()), vector.uuids, vector.seed);
  }
});

test('time rounding vectors', () => {
  for (const vector of fixtures.vectors.frames) {
    assert.equal(framesOf(vector.time, vector.rate), vector.frames, JSON.stringify(vector));
  }
});

test('every graph digest and envelope digest follows the canonical serialisation', () => {
  for (const [name, graph, digest] of graphs()) assert.equal(graphDigest(graph), digest, name);
  for (const entry of fixtures.cases.filter((candidate) => candidate.expect?.status === 'applied')) {
    assert.equal(envelopeDigest(entry.expect.graph, build.upstreamCommit), entry.expect.envelopeDigest, entry.id);
  }
});

test('every identity a command minted is the documented draw of its envelope stream', () => {
  for (const entry of fixtures.cases.filter((candidate) => candidate.expect?.status === 'applied')) {
    entry.expect.draws.forEach((draws, index) => {
      const next = uuidStream(`${entry.envelopes[index].idempotencyKey}:${index}`);
      for (const draw of draws) assert.equal(next(), draw.id, `${entry.id} envelope ${index} draw ${draw.draw}`);
    });
  }
});

test('every graph the engine wrote satisfies the published schema', () => {
  for (const [name, graph] of graphs()) {
    const errors = validate(schema, graph);
    assert.deepEqual(errors, [], `${name}:\n${errors.slice(0, 20).join('\n')}`);
  }
});

test('the media records the fixtures give the engine satisfy the published media record schema', () => {
  const record = { ...schema, $ref: '#/$defs/mediaRecord' };
  for (const [set, records] of Object.entries(fixtures.media)) {
    for (const media of records) assert.deepEqual(validate(record, media), [], `${set} ${media.id}`);
  }
});

/** Every item list of a graph, keyed by where it lives: the main timeline and each composition. */
const itemLists = (graph) => [
  ['timeline', graph.timeline?.items ?? []],
  ...(graph.timeline?.compositions ?? []).map((composition) => [`composition ${composition.id}`, composition.items ?? []]),
];

test('the universal rules of the protocol hold for every applied case', () => {
  for (const entry of fixtures.cases.filter((candidate) => candidate.expect?.status === 'applied')) {
    const before = fixtures.bases[entry.base].graph;
    const after = entry.expect.graph;
    // Section 2.6: normal form is a fixed point. Section 4.3: no command writes the clock.
    assert.equal(entry.expect.fixedPoint, true, `${entry.id} is not a fixed point`);
    assert.equal(entry.expect.clockIndependent, true, `${entry.id} depends on issuedAt`);
    // Section 2.1: commands leave the project's own timestamps and duration alone.
    for (const field of ['id', 'createdAt', 'updatedAt', 'duration']) {
      assert.deepEqual(after[field], before[field], `${entry.id} changed ${field}`);
    }
    // Section 5: surviving items keep their relative order; new items come after them.
    const lists = new Map(itemLists(before));
    for (const [where, items] of itemLists(after)) {
      const old = new Set((lists.get(where) ?? []).map((item) => item.id));
      const ids = items.map((item) => item.id);
      const firstNew = ids.findIndex((id) => !old.has(id));
      if (firstNew >= 0) {
        assert.ok(ids.slice(firstNew).every((id) => !old.has(id)), `${entry.id}: ${where} interleaves new items`);
      }
      const survivors = (lists.get(where) ?? []).map((item) => item.id).filter((id) => ids.includes(id));
      assert.deepEqual(ids.filter((id) => old.has(id)), survivors, `${entry.id}: ${where} reorders items`);
    }
  }
});

test('command status names only graph-changing catalogue commands', () => {
  const mutating = new Set(catalogue.commands.filter((command) => command.mutatesGraph).map((command) => command.id));
  for (const id of Object.keys(fixtures.commandStatus)) assert.ok(mutating.has(id), id);
});
