/**
 * FL-306, FL-307, FL-308: check the published Studio graph protocol against the engine's own answers
 * without the engine. `graph-protocol.mjs` implements the protocol's computable rules from the
 * prose; every engine-generated digest, identity draw and rounding answer in
 * `studio/graph-conformance-v1.json` must agree with it, and every graph there must satisfy
 * `studio/graph-schema-v1.json`. For part 2 (FL-307) the rules of section 12 that a graph and a
 * payload alone decide are re-derived too. For part 3 (FL-308) the parameter catalogue
 * `studio/graph-parameters-v1.json` is checked against its own digest and the command catalogue,
 * and every effect, transition, easing, modifier and text motion in a graph must be one it lists.
 * `graph-reference.mjs`, a reference implementation written from sections 12 and 13, replays every
 * part 2 and part 3 case: the prose must be enough to reproduce the engine's graphs, ids and
 * refusals.
 *
 * The engine replay itself (`studio/adapters/web/test/graph-conformance.test.ts`) runs in the
 * Studio engine workflow; this check runs in the Scripts unit tests on every pull request, so a
 * hand-edited answer, schema or fixture is caught even where the engine is not built.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import {
  applyMarkerCommand,
  applyTrackCommand,
  canonicalJson,
  clampInOut,
  classicNames,
  envelopeDigest,
  framesOf,
  graphDigest,
  isMediaClip,
  overlapsOf,
  retime,
  sha256Hex,
  splitSource,
  transitionKept,
  trimEnd,
  trimStart,
  uuidStream,
  validate,
} from './graph-protocol.mjs';
import { applyBatch, Unspecified } from './graph-reference.mjs';

const read =(name) => JSON.parse(readFileSync(new URL(`../${name}`, import.meta.url), 'utf8'));
const fixtures = read('graph-conformance-v1.json');
const schema = read('graph-schema-v1.json');
const catalogue = read('frameleaf-studio-commands.json');
const build = read('engine-build.json');
const parameters = read('graph-parameters-v1.json');

const graphs = () => [
  ...Object.entries(fixtures.bases).map(([name, base]) => [`base ${name}`, base.graph, base.digest]),
  ...fixtures.cases
    .filter((entry) => entry.expect?.status === 'applied')
    .map((entry) => [entry.id, entry.expect.graph, entry.expect.digest]),
];

/** Section 10: a case marked `outsideNormalForm` records a graph a native client must never write. */
const outside = new Set(fixtures.cases.filter((entry) => entry.outsideNormalForm === true).map((entry) => entry.id));
const normalGraphs = () => graphs().filter(([name]) => !outside.has(name));
const applied = (entry) => entry.expect?.status === 'applied';

test('the fixtures were generated by the pinned engine and every case has an answer', () => {
  assert.equal(fixtures.format, 'frameleaf-studio-graph-conformance');
  assert.equal(fixtures.version, 1);
  assert.deepEqual(fixtures.engine, { name: 'freecut', revision: build.upstreamCommit });
  for (const entry of fixtures.cases) assert.ok(entry.expect, `${entry.id} has no answer`);
  for (const script of fixtures.history) assert.ok(script.expect, `${script.id} has no answer`);
  const ids = fixtures.cases.map((entry) => entry.id);
  assert.equal(new Set(ids).size, ids.length, 'case ids are unique');
});

test('canonical serialisation vectors', () => {
  for (const vector of fixtures.vectors.canonicalJson) {
    assert.equal(canonicalJson(vector.value), vector.canonical, JSON.stringify(vector.value));
    assert.equal(sha256Hex(vector.canonical), vector.sha256);
  }
});

test('identity stream vectors', () => {
  for (const vector of fixtures.vectors.uuids) {
    const next = uuidStream(vector.seed);
    assert.deepEqual(Array.from({ length: vector.count }, () => next()), vector.uuids, vector.seed);
  }
});

test('time rounding vectors', () => {
  for (const vector of fixtures.vectors.frames) {
    assert.equal(framesOf(vector.time, vector.rate), vector.frames, JSON.stringify(vector));
  }
});

test('every graph digest and envelope digest follows the canonical serialisation', () => {
  for (const [name, graph, digest] of graphs()) assert.equal(graphDigest(graph), digest, name);
  for (const entry of fixtures.cases.filter((candidate) => candidate.expect?.status === 'applied')) {
    assert.equal(envelopeDigest(entry.expect.graph, build.upstreamCommit), entry.expect.envelopeDigest, entry.id);
  }
});

test('every identity a command minted is the documented draw of its envelope stream', () => {
  for (const entry of fixtures.cases.filter((candidate) => candidate.expect?.status === 'applied')) {
    entry.expect.draws.forEach((draws, index) => {
      const next = uuidStream(`${entry.envelopes[index].idempotencyKey}:${index}`);
      for (const draw of draws) assert.equal(next(), draw.id, `${entry.id} envelope ${index} draw ${draw.draw}`);
    });
  }
});

test('every graph the engine wrote in normal form satisfies the published schema', () => {
  for (const [name, graph] of normalGraphs()) {
    const errors = validate(schema, graph);
    assert.deepEqual(errors, [], `${name}:\n${errors.slice(0, 20).join('\n')}`);
  }
});

test('a case is outside normal form exactly when it is marked so', () => {
  for (const entry of fixtures.cases) {
    if (!applied(entry)) {
      assert.notEqual(entry.outsideNormalForm, true, `${entry.id} is rejected, so it cannot be outside normal form`);
      continue;
    }
    assert.equal(entry.expect.fixedPoint, entry.outsideNormalForm !== true, `${entry.id}: fixedPoint and outsideNormalForm disagree`);
  }
  // Section 11 lists exactly these edits as ones a native client refuses.
  assert.deepEqual([...outside].sort(), [
    'clip.move/overlap-is-not-checked',
    'clip.setSpeed/above-ten',
    'clip.setTransform/rotation-is-not-reduced',
    'clip.update/volume-is-not-clamped',
  ]);
  // Each of them breaks the schema or the no-overlap rule, which is why a native client refuses it.
  for (const entry of fixtures.cases.filter((candidate) => outside.has(candidate.id))) {
    const broken = validate(schema, entry.expect.graph).length > 0 || overlapsOf(entry.expect.graph).length > 0;
    assert.ok(broken, `${entry.id} is marked outside normal form but breaks no rule`);
  }
});

test('the media records the fixtures give the engine satisfy the published media record schema', () => {
  const record = { ...schema, $ref: '#/$defs/mediaRecord' };
  for (const [set, records] of Object.entries(fixtures.media)) {
    for (const media of records) assert.deepEqual(validate(record, media), [], `${set} ${media.id}`);
  }
});

/** Every item list of a graph, keyed by where it lives: the main timeline and each composition. */
const itemLists = (graph) => [
  ['timeline', graph.timeline?.items ?? []],
  ...(graph.timeline?.compositions ?? []).map((composition) => [`composition ${composition.id}`, composition.items ?? []]),
];

test('the universal rules of the protocol hold for every applied case', () => {
  for (const entry of fixtures.cases.filter((candidate) => candidate.expect?.status === 'applied')) {
    const before = fixtures.bases[entry.base].graph;
    const after = entry.expect.graph;
    // Section 2.6: normal form is a fixed point (the marked exceptions are checked above).
    // Section 4.3: no command writes the clock.
    assert.equal(entry.expect.clockIndependent, true, `${entry.id} depends on issuedAt`);
    // Section 2.1: commands leave the project's own timestamps and duration alone.
    for (const field of ['id', 'createdAt', 'updatedAt', 'duration']) {
      assert.deepEqual(after[field], before[field], `${entry.id} changed ${field}`);
    }
    // Section 5: surviving items keep their relative order; new items come after them.
    const lists = new Map(itemLists(before));
    for (const [where, items] of itemLists(after)) {
      const old = new Set((lists.get(where) ?? []).map((item) => item.id));
      const ids = items.map((item) => item.id);
      const firstNew = ids.findIndex((id) => !old.has(id));
      if (firstNew >= 0) {
        assert.ok(ids.slice(firstNew).every((id) => !old.has(id)), `${entry.id}: ${where} interleaves new items`);
      }
      const survivors = (lists.get(where) ?? []).map((item) => item.id).filter((id) => ids.includes(id));
      assert.deepEqual(ids.filter((id) => old.has(id)), survivors, `${entry.id}: ${where} reorders items`);
    }
  }
});

test('command status names only graph-changing catalogue commands', () => {
  const mutating = new Set(catalogue.commands.filter((command) => command.mutatesGraph).map((command) => command.id));
  for (const id of Object.keys(fixtures.commandStatus)) assert.ok(mutating.has(id), id);
});

/* Part 2 (FL-307): section 12 */

const part2 = Object.entries(fixtures.commandStatus)
  .filter(([, entry]) => entry.story === 'FL-307')
  .map(([id]) => id)
  .sort();
const part2Cases = fixtures.cases.filter((entry) => entry.story === 'FL-307');
/** Cases whose batch is one envelope of `command`, so the base graph is the graph the command saw. */
const single = (command) => part2Cases.filter((entry) => entry.envelopes.length === 1 && entry.envelopes[0].id === command);
const lastFrameOf = (graph) => Math.max(0, ...(graph.timeline.items ?? []).map((item) => item.from + item.durationInFrames));
const itemOf = (graph, id) => graph.timeline.items.find((item) => item.id === id);

test('part 2 covers its 28 commands with applied and rejected cases', () => {
  assert.equal(part2.length, 28);
  for (const command of part2) {
    const cases = part2Cases.filter((entry) => entry.id.startsWith(`${command}/`));
    for (const entry of cases) assert.ok(entry.covers.includes(command), `${entry.id} does not cover ${command}`);
    const count = (status) => cases.filter((entry) => entry.expect.status === status).length;
    assert.ok(count('rejected') > 0, `${command} has no rejected case`);
    // 12.8.4: music.add is always refused at this revision.
    if (command === 'music.add') assert.equal(count('applied'), 0, 'music.add must never apply');
    else assert.ok(count('applied') > 0, `${command} has no applied case`);
  }
});

test('every refusal names an envelope of its batch and one of the three reasons', () => {
  for (const entry of fixtures.cases.filter((candidate) => candidate.expect?.status === 'rejected')) {
    assert.ok(['invalid', 'failed', 'not-implemented'].includes(entry.expect.reason), `${entry.id}: ${entry.expect.reason}`);
    assert.ok(Number.isInteger(entry.expect.index) && entry.expect.index >= 0, entry.id);
    assert.ok(entry.expect.index < entry.envelopes.length, `${entry.id}: index outside the batch`);
    assert.equal(typeof entry.expect.detail, 'string', entry.id);
  }
});

test('the graph-wide rules of part 2 hold for every graph in normal form', () => {
  for (const [name, graph] of normalGraphs()) {
    const { timeline, metadata } = graph;
    if (!timeline) continue;
    // Section 5: no two clips of a track share a frame unless a transition joins them.
    assert.deepEqual(overlapsOf(graph), [], `${name}: overlap`);
    // 12.2.8: tracks are stored in ascending order and classic names follow position.
    const orders = timeline.tracks.map((track) => track.order);
    assert.deepEqual(orders, orders.toSorted((a, b) => a - b), `${name}: tracks are not in ascending order`);
    for (const [id, expected] of classicNames(timeline.tracks)) {
      assert.equal(timeline.tracks.find((track) => track.id === id).name, expected, `${name}: track ${id}`);
    }
    // Every clip is on a track of the graph, and clip ids are unique.
    const tracks = new Set(timeline.tracks.map((track) => track.id));
    const ids = timeline.items.map((item) => item.id);
    assert.equal(new Set(ids).size, ids.length, `${name}: duplicate clip id`);
    for (const item of timeline.items) assert.ok(tracks.has(item.trackId), `${name}: ${item.id} is on no track`);
    // 12.2.4: a media clip's source window is not empty and lies inside its source.
    for (const item of timeline.items.filter((candidate) => ['video', 'audio'].includes(candidate.type))) {
      assert.ok(item.sourceStart < item.sourceEnd, `${name}: ${item.id} has an empty source window`);
      if (item.sourceDuration !== undefined) assert.ok(item.sourceEnd <= item.sourceDuration, `${name}: ${item.id} runs past its source`);
    }
    // 12.2.6, rules 1 to 4: every transition left in a graph is one that repair keeps.
    for (const transition of timeline.transitions ?? []) {
      assert.ok(transitionKept(transition, graph), `${name}: transition ${transition.id} should have been removed`);
    }
    // 12.2.7: in and out points are already clamped to the extent.
    assert.deepEqual(
      clampInOut(timeline.inPoint, timeline.outPoint, lastFrameOf(graph), metadata.fps),
      { inPoint: timeline.inPoint, outPoint: timeline.outPoint },
      `${name}: in and out points`,
    );
    // 12.8: a marker label is never empty.
    for (const marker of timeline.markers ?? []) assert.notEqual(marker.label, '', `${name}: empty marker label`);
  }
});

test('12.2.2: a command that refuses locked clips leaves every clip on a locked track as it was', () => {
  // The first row of the lock table: these refuse as soon as a clip they would change is locked.
  const checking = ['clip.roll', 'clip.slip', 'clip.slide', 'clip.push', 'clip.join', 'clip.reorder', 'clip.overwrite', 'track.closeGap'];
  let checked = 0;
  for (const entry of part2Cases.filter((candidate) => applied(candidate) && checking.includes(candidate.covers[0]))) {
    const before = fixtures.bases[entry.base].graph;
    const after = entry.expect.graph;
    const locked = new Set(after.timeline.tracks.filter((track) => track.locked).map((track) => track.id));
    for (const item of before.timeline.items.filter((candidate) => locked.has(candidate.trackId))) {
      assert.deepEqual(itemOf(after, item.id), item, `${entry.id}: ${item.id} is on a locked track and changed`);
    }
    checked++;
  }
  assert.ok(checked >= 30, `only ${checked} cases were checked`);
  // And each of them has a case that a lock refuses.
  for (const command of checking) {
    const refused = part2Cases.some(
      (entry) => entry.id.startsWith(`${command}/`) && entry.expect.status === 'rejected' && /locked/.test(entry.expect.detail),
    );
    assert.ok(refused, `${command} has no case refused for a lock`);
  }
});

test('12.2.5: the halves of a split clip have the documented ids, lengths and source frames', () => {
  let checked = 0;
  for (const entry of single('clip.split').filter(applied)) {
    const before = fixtures.bases[entry.base].graph;
    const after = entry.expect.graph;
    const { fps, frameRate } = before.metadata;
    const at = framesOf(entry.envelopes[0].payload.at, frameRate);
    const known = new Set(before.timeline.items.map((item) => item.id));
    for (const original of before.timeline.items) {
      const left = itemOf(after, original.id);
      if (left.durationInFrames === original.durationInFrames) continue;
      const right = after.timeline.items.find(
        (item) => !known.has(item.id) && item.trackId === original.trackId && item.from === at && item.type === original.type,
      );
      assert.ok(right, `${entry.id}: ${original.id} has no right half`);
      assert.equal(left.from, original.from, entry.id);
      assert.equal(left.durationInFrames, at - original.from, entry.id);
      assert.equal(right.durationInFrames, original.from + original.durationInFrames - at, entry.id);
      // Both halves share the lineage: the clip's originId, or its id when it had none.
      assert.equal(left.originId, original.originId ?? original.id, entry.id);
      assert.equal(right.originId, left.originId, entry.id);
      // The right half is appended after every clip the graph already had.
      assert.ok(after.timeline.items.indexOf(right) >= before.timeline.items.length, `${entry.id}: the right half is not appended`);
      if (isMediaClip(original)) {
        const expected = splitSource(original, left.durationInFrames, fps);
        assert.deepEqual({ sourceStart: left.sourceStart, sourceEnd: left.sourceEnd }, expected.left, `${entry.id}: left source`);
        assert.deepEqual({ sourceStart: right.sourceStart, sourceEnd: right.sourceEnd }, expected.right, `${entry.id}: right source`);
      } else {
        // A still's source fields are copied to both halves unchanged.
        for (const half of [left, right]) {
          assert.deepEqual([half.sourceStart, half.sourceEnd], [original.sourceStart, original.sourceEnd], `${entry.id}: still source`);
        }
      }
      checked++;
    }
  }
  assert.ok(checked >= 8, `only ${checked} split clips were checked`);
});

test('12.4.1: a trim without ripple gives the named clip the documented extent and source frames', () => {
  let checked = 0;
  for (const command of ['clip.trimStart', 'clip.trimEnd']) {
    for (const entry of single(command).filter(applied)) {
      const { payload } = entry.envelopes[0];
      if (payload.ripple === true) continue;
      const before = fixtures.bases[entry.base].graph;
      const { fps, frameRate } = before.metadata;
      const original = itemOf(before, payload.clipId);
      const expected =
        command === 'clip.trimStart'
          ? trimStart(original, framesOf(payload.start, frameRate) - original.from, fps)
          : trimEnd(original, framesOf(payload.end, frameRate) - (original.from + original.durationInFrames), fps);
      assert.deepEqual(itemOf(entry.expect.graph, payload.clipId), expected, entry.id);
      checked++;
    }
  }
  assert.ok(checked >= 10, `only ${checked} trims were checked`);
});

test('12.4.5: a retimed clip has the documented length and stored speed', () => {
  let checked = 0;
  for (const entry of part2Cases.filter((candidate) => applied(candidate) && candidate.envelopes.at(-1)?.id === 'clip.setSpeed')) {
    const { payload } = entry.envelopes.at(-1);
    const after = entry.expect.graph;
    const item = itemOf(after, payload.clipId);
    // The source window does not change, so the retimed clip itself carries what the rule needs.
    const expected = retime(item, payload.speed, after.metadata);
    assert.equal(item.durationInFrames, expected.durationInFrames, `${entry.id}: length`);
    assert.equal(item.speed, expected.speed, `${entry.id}: stored speed`);
    checked++;
  }
  assert.ok(checked >= 8, `only ${checked} retimes were checked`);
});

test('12.8: marker commands replayed from the prose give the marker lists the engine wrote', () => {
  let checked = 0;
  for (const command of ['marker.add', 'marker.update', 'marker.remove']) {
    for (const entry of part2Cases.filter((candidate) => applied(candidate) && candidate.id.startsWith(`${command}/`))) {
      const before = fixtures.bases[entry.base].graph;
      let markers = before.timeline.markers ?? [];
      entry.envelopes.forEach((envelope, index) => {
        markers = applyMarkerCommand(markers, envelope, before.metadata.frameRate, uuidStream(`${envelope.idempotencyKey}:${index}`));
      });
      assert.deepEqual(entry.expect.graph.timeline.markers, markers.length > 0 ? markers : undefined, entry.id);
      // Nothing else in the graph changes.
      const { markers: _before, ...restBefore } = before.timeline;
      const { markers: _after, ...restAfter } = entry.expect.graph.timeline;
      assert.deepEqual(restAfter, restBefore, `${entry.id}: a marker command changed something else`);
      checked++;
    }
  }
  assert.ok(checked >= 8, `only ${checked} marker cases were checked`);
});

test('12.7: track list commands replayed from the prose give the track lists the engine wrote', () => {
  const replayable = ['track.add', 'track.reorder', 'track.set'];
  let checked = 0;
  for (const entry of part2Cases.filter((candidate) => applied(candidate) && replayable.includes(candidate.covers[0]))) {
    if (!entry.envelopes.every((envelope) => replayable.includes(envelope.id))) continue;
    const before = fixtures.bases[entry.base].graph;
    let tracks = before.timeline.tracks;
    entry.envelopes.forEach((envelope, index) => {
      tracks = applyTrackCommand(tracks, envelope, uuidStream(`${envelope.idempotencyKey}:${index}`));
    });
    assert.deepEqual(entry.expect.graph.timeline.tracks, tracks, entry.id);
    // These commands change no clip.
    assert.deepEqual(entry.expect.graph.timeline.items, before.timeline.items, `${entry.id}: a track command changed a clip`);
    checked++;
  }
  assert.ok(checked >= 18, `only ${checked} track cases were checked`);
});

test('12.7.2: track.remove removes the track and its clips and leaves the other clips alone', () => {
  let checked = 0;
  for (const entry of single('track.remove').filter(applied)) {
    const before = fixtures.bases[entry.base].graph;
    const { trackId } = entry.envelopes[0].payload;
    assert.deepEqual(entry.expect.graph.timeline.tracks, applyTrackCommand(before.timeline.tracks, entry.envelopes[0]), entry.id);
    assert.deepEqual(
      entry.expect.graph.timeline.items,
      before.timeline.items.filter((item) => item.trackId !== trackId),
      entry.id,
    );
    checked++;
  }
  assert.ok(checked >= 3, `only ${checked} removals were checked`);
});

/**
 * The cases the reference implementation does not replay. Six need a rule the prose defers to part
 * 4. Six hold engine arithmetic (13.1): values from sines, arctangents and keyframe interpolation
 * that the protocol does not fix to the last bit, which the fixtures mark `engineArithmetic`. A case
 * that starts to need either must be added here on purpose.
 */
const deferred = new Map([
  ['clip.move/rejects-clip-inside-composition', 'composition.add is specified in part 4'],
  ['clip.update/style-bold', 'title styles are specified in part 4'],
  ['clip.update/style-minimal', 'title styles are specified in part 4'],
  ['clip.update/style-lower-third', 'title styles are specified in part 4'],
  ['clip.update/animation', 'title animations are specified in part 4'],
  ['clip.update/rejects-unknown-style', 'title styles are specified in part 4'],
  ['clip.setTransformParent/detach', 'engine arithmetic: the pose of an already-parented clip'],
  ['clip.setTransformParent/reparent', 'engine arithmetic: the pose of an already-parented clip'],
  ['clip.setTransformParent/animated-parent', 'engine arithmetic: the pose of a keyframed clip'],
  ['property.bakeModifier/spin', 'engine arithmetic: baked keyframe values'],
  ['property.bakeModifier/sway', 'engine arithmetic: baked keyframe values'],
  ['property.bakeModifier/all-modifiers-over-keyframes', 'engine arithmetic: baked keyframe values'],
]);

/* Part 3 (FL-308): section 13 */

const part3 = Object.entries(fixtures.commandStatus)
  .filter(([, entry]) => entry.story === 'FL-308')
  .map(([id]) => id)
  .sort();
const part3Cases = fixtures.cases.filter((entry) => entry.story === 'FL-308');
const replayable = [...part2Cases, ...part3Cases];

test('part 3 covers its 12 commands with applied and rejected cases', () => {
  assert.deepEqual(part3, [
    'clip.setKenBurns',
    'clip.setTransition',
    'effect.add',
    'effect.remove',
    'keyframe.add',
    'keyframe.remove',
    'keyframe.setEasing',
    'keyframe.update',
    'property.bakeModifier',
    'property.setExpression',
    'property.setModifier',
    'text.setMotion',
  ]);
  for (const command of part3) {
    const cases = part3Cases.filter((entry) => entry.id.startsWith(`${command}/`));
    for (const entry of cases) assert.ok(entry.covers.includes(command), `${entry.id} does not cover ${command}`);
    const count = (status) => cases.filter((entry) => entry.expect.status === status).length;
    assert.ok(count('applied') > 0, `${command} has no applied case`);
    assert.ok(count('rejected') > 0, `${command} has no rejected case`);
  }
});

test('13.1: the cases marked engineArithmetic are exactly the ones the protocol leaves to the engine', () => {
  const marked = fixtures.cases.filter((entry) => entry.engineArithmetic === true);
  assert.deepEqual(
    marked.map((entry) => entry.id).sort(),
    [...deferred]
      .filter(([, reason]) => reason.startsWith('engine arithmetic'))
      .map(([id]) => id)
      .sort(),
  );
  // Only an applied answer can hold such values; a refusal is always reproducible.
  for (const entry of marked) assert.equal(entry.expect.status, 'applied', entry.id);
});

test('13.2: every effect, transition, easing, modifier and text motion in a graph is one the catalogue lists', () => {
  const effects = new Set(parameters.effects.map((entry) => entry.id));
  const transitions = new Set(parameters.transitions.map((entry) => entry.id));
  const modifiers = new Set(parameters.motionModifiers.map((entry) => entry.id));
  const easings = new Set(parameters.easing.types);
  let checked = 0;
  for (const [name, graph] of normalGraphs()) {
    const { timeline } = graph;
    if (!timeline) continue;
    const clips = new Map(timeline.items.map((item) => [item.id, item]));
    for (const item of timeline.items) {
      // 13.2.2: an effect stack names catalogue effects, under ids unique on the clip.
      const stack = item.effects ?? [];
      assert.equal(new Set(stack.map((effect) => effect.id)).size, stack.length, `${name}: ${item.id} repeats an effect id`);
      for (const { effect } of stack) {
        if (effect.type === 'gpu-effect') assert.ok(effects.has(effect.gpuEffectType), `${name}: effect ${effect.gpuEffectType}`);
        checked++;
      }
      // 13.6.2: at most one modifier of a type on a clip.
      const types = (item.motionModifiers ?? []).map((modifier) => modifier.type);
      assert.equal(new Set(types).size, types.length, `${name}: ${item.id} has two modifiers of one type`);
      for (const type of types) assert.ok(modifiers.has(type), `${name}: modifier ${type}`);
      // 13.7.1: each text motion slot holds a preset of that slot, with normalised values.
      for (const [slot, motion] of Object.entries(item.textMotion ?? {})) {
        assert.ok(parameters.textMotion[slot]?.includes(motion.presetId), `${name}: ${slot} text motion ${motion.presetId}`);
        assert.ok(Number.isInteger(motion.durationFrames) && motion.durationFrames >= 1, `${name}: text motion duration`);
        assert.ok(motion.intensity >= 0 && motion.intensity <= 2, `${name}: text motion intensity`);
        checked++;
      }
      // 13.8.4: a blend mode is one of the catalogue's.
      if (item.blendMode !== undefined) {
        assert.ok(parameters.blendModes.some((mode) => mode.id === item.blendMode), `${name}: blend mode ${item.blendMode}`);
      }
    }
    // 13.2.3: a transition names a catalogue presentation; a clip has at most one transition out of it and one into it.
    const list = timeline.transitions ?? [];
    for (const transition of list) {
      assert.ok(transitions.has(transition.presentation), `${name}: transition ${transition.presentation}`);
      assert.equal(transition.type, 'crossfade', name);
      checked++;
    }
    for (const side of ['leftClipId', 'rightClipId']) {
      const ids = list.map((transition) => transition[side]);
      assert.equal(new Set(ids).size, ids.length, `${name}: two transitions share a ${side}`);
    }
    // 13.2.4: one entry per clip, for a clip of the timeline; keyframes in frame order, one per frame.
    const entries = timeline.keyframes ?? [];
    assert.equal(new Set(entries.map((entry) => entry.itemId)).size, entries.length, `${name}: two keyframes entries for one clip`);
    for (const entry of entries) {
      assert.ok(clips.has(entry.itemId), `${name}: keyframes of a clip that is not there (${entry.itemId})`);
      const vector = entry.vectorProperties ?? [];
      const names = [...entry.properties.map((group) => `scalar:${group.property}`), ...vector.map((group) => `vector:${group.property}`)];
      assert.equal(new Set(names).size, names.length, `${name}: ${entry.itemId} lists a property twice`);
      for (const group of [...entry.properties, ...vector]) {
        const frames = group.keyframes.map((keyframe) => keyframe.frame);
        assert.deepEqual(frames, [...new Set(frames)].sort((a, b) => a - b), `${name}: ${entry.itemId} ${group.property} frames`);
        for (const keyframe of group.keyframes) {
          assert.ok(easings.has(keyframe.easing), `${name}: easing ${keyframe.easing}`);
          // 13.2.6: stored parameters belong to the easing they sit beside.
          if (keyframe.easingConfig) {
            assert.equal(keyframe.easingConfig.type, keyframe.easing, `${name}: easing parameters of another easing`);
            assert.ok(keyframe.easing === 'cubic-bezier' ? keyframe.easingConfig.bezier : keyframe.easingConfig.spring, name);
          }
          checked++;
        }
      }
      const targets = (entry.expressions ?? []).map((expression) => expression.targetProperty);
      assert.equal(new Set(targets).size, targets.length, `${name}: two expressions on one property`);
      for (const target of targets) assert.ok(parameters.properties.expression.includes(target), `${name}: expression on ${target}`);
    }
  }
  assert.ok(checked >= 600, `only ${checked} entries were checked`);
});

test('13.7.2: a Ken Burns record names two keyframes each of x, y, width and height, at the first and last frame', () => {
  let checked = 0;
  for (const [name, graph] of normalGraphs()) {
    for (const item of graph.timeline?.items ?? []) {
      const record = item.frameleafKenBurns;
      if (!record) continue;
      assert.equal(item.type, 'image', name);
      const entry = graph.timeline.keyframes.find((candidate) => candidate.itemId === item.id);
      const last = Math.max(1, item.durationInFrames - 1);
      const owned = ['x', 'y', 'width', 'height'].flatMap((property) =>
        entry.properties.find((group) => group.property === property).keyframes.filter((keyframe) => record.keyframeIds.includes(keyframe.id)),
      );
      if (owned.length !== record.keyframeIds.length) continue; // a recorded keyframe was removed by hand afterwards
      assert.deepEqual(
        owned.map((keyframe) => keyframe.id),
        record.keyframeIds,
        `${name}: the record lists its keyframes in property order`,
      );
      assert.deepEqual(
        owned.map((keyframe) => keyframe.frame),
        [0, last, 0, last, 0, last, 0, last],
        name,
      );
      // The move is uniform: the photo keeps its shape, so width and height scale together.
      const [, , , , w0, w1, h0, h1] = owned.map((keyframe) => keyframe.value);
      assert.ok(Math.abs(w0 / h0 - w1 / h1) < 1e-9, `${name}: the move changes the photo's shape`);
      checked++;
    }
  }
  assert.ok(checked >= 8, `only ${checked} records were checked`);
});

test('sections 12 and 13 are enough to reproduce every part 2 and part 3 case: graphs, ids and refusals', () => {
  const skipped = [];
  let replayed = 0;
  for (const entry of replayable) {
    const base = fixtures.bases[entry.base];
    let outcome;
    try {
      outcome = applyBatch(base.graph, entry.envelopes, fixtures.media[entry.media ?? base.media]);
    } catch (error) {
      if (!(error instanceof Unspecified)) throw new Error(`${entry.id}: ${error.message}`, { cause: error });
      skipped.push(entry.id);
      continue;
    }
    if (entry.expect.status === 'rejected') {
      assert.deepEqual(
        { status: outcome.status, index: outcome.index, reason: outcome.reason },
        { status: 'rejected', index: entry.expect.index, reason: entry.expect.reason },
        `${entry.id}: ${outcome.detail ?? 'the reference applied the batch'}`,
      );
    } else {
      assert.equal(outcome.status, 'applied', `${entry.id}: refused at ${outcome.index} (${outcome.reason}): ${outcome.detail}`);
      // The digest covers every id the batch drew and every field it wrote.
      assert.deepEqual(JSON.parse(JSON.stringify(outcome.graph)), entry.expect.graph, entry.id);
      assert.equal(graphDigest(outcome.graph), entry.expect.digest, `${entry.id}: digest`);
    }
    replayed++;
  }
  assert.deepEqual(skipped.sort(), [...deferred.keys()].sort(), 'the cases deferred to part 4 or left to the engine');
  assert.equal(replayed, replayable.length - deferred.size);
  assert.ok(replayed >= 750, `only ${replayed} cases were replayed`);
});

/* Part 3 (FL-308): the parameter catalogue */

/** Every key of every object in a JSON value. */
const keysOf = (value, found = new Set()) => {
  if (Array.isArray(value)) for (const entry of value) keysOf(entry, found);
  else if (value && typeof value === 'object') {
    for (const [key, entry] of Object.entries(value)) {
      found.add(key);
      keysOf(entry, found);
    }
  }
  return found;
};
const manifestIds = (command, prefix) =>
  catalogue.commands
    .find((entry) => entry.id === command)
    .manifestIds.filter((id) => id.startsWith(prefix))
    .map((id) => id.slice(prefix.length))
    .sort();

test('13.2.1: the parameter catalogue is the generated one, unedited', () => {
  assert.equal(parameters.format, 'frameleaf-studio-graph-parameters');
  assert.equal(parameters.version, 1);
  assert.deepEqual(parameters.engine, { name: 'freecut', revision: build.upstreamCommit });
  // The generator stamps the digest of everything else; a hand edit of any value breaks it.
  const { contentSha256, ...content } = parameters;
  assert.equal(sha256Hex(canonicalJson(content)), contentSha256, 'the catalogue was edited by hand: regenerate it from the engine');
  assert.deepEqual(parameters.counts, {
    effects: parameters.effects.length,
    transitions: parameters.transitions.length,
    blendModes: parameters.blendModes.length,
  });
  for (const kind of ['effects', 'transitions', 'blendModes']) {
    const ids = parameters[kind].map((entry) => entry.id);
    assert.equal(new Set(ids).size, ids.length, `${kind}: ids are unique`);
  }
  // Clean room: ids, names, types and numbers only. No display text or source from the engine.
  for (const key of ['label', 'description', 'shader', 'icon', 'entryPoint']) {
    assert.ok(!keysOf(parameters).has(key), `the catalogue carries engine text under "${key}"`);
  }
});

test('13.2.1: the catalogue lists what the command catalogue names: every effect, blend mode and published transition', () => {
  const sorted = (kind) => parameters[kind].map((entry) => entry.id).sort();
  assert.deepEqual(sorted('effects'), manifestIds('effect.update', 'effect.'), 'effects');
  assert.deepEqual(sorted('blendModes'), manifestIds('clip.setBlendMode', 'blend.'), 'blend modes');
  const transitions = new Set(sorted('transitions'));
  for (const id of manifestIds('clip.setTransition', 'transition.')) assert.ok(transitions.has(id), `transition ${id}`);
  for (const [alias, id] of Object.entries(parameters.transitionAliases)) {
    assert.ok(transitions.has(id), `alias ${alias} names ${id}`);
    assert.ok(!transitions.has(alias), `alias ${alias} is also a transition id`);
  }
  // Blend mode indexes are 0..n-1 in listed order.
  parameters.blendModes.forEach((mode, index) => assert.equal(mode.index, index, mode.id));
});

test('13.2.1: every catalogue parameter has a type, and a default its own type and range allow', () => {
  const colour = /^#([0-9a-f]{6}|[0-9a-f]{8})$/i;
  for (const effect of parameters.effects) {
    const names = effect.parameters.map((parameter) => parameter.name);
    assert.equal(new Set(names).size, names.length, `${effect.id}: parameter names are unique`);
    for (const parameter of effect.parameters) {
      const where = `${effect.id}.${parameter.name}`;
      assert.ok(['number', 'boolean', 'select', 'color', 'json', 'text', 'point'].includes(parameter.type), `${where}: type ${parameter.type}`);
      assert.equal(typeof parameter.animatable, 'boolean', where);
      if (parameter.type === 'number') {
        assert.equal(typeof parameter.default, 'number', where);
        assert.ok(typeof parameter.min === 'number' && typeof parameter.max === 'number' && parameter.min <= parameter.max, `${where}: range`);
        assert.ok(parameter.default >= parameter.min && parameter.default <= parameter.max, `${where}: default outside its range`);
      } else if (parameter.type === 'boolean') {
        assert.equal(typeof parameter.default, 'boolean', where);
      } else if (parameter.type === 'select') {
        assert.ok(Array.isArray(parameter.options) && parameter.options.includes(parameter.default), `${where}: default is not an option`);
      } else {
        assert.equal(typeof parameter.default, 'string', where);
        if (parameter.type === 'color') assert.match(parameter.default, colour, where);
      }
    }
  }
  for (const transition of parameters.transitions) {
    const { default: usual, min, max } = transition.editorDuration;
    assert.ok(Number.isInteger(min) && min >= 1 && min <= usual && usual <= max, `${transition.id}: editor duration`);
    if (transition.directions) assert.ok(transition.directions.length > 0, `${transition.id}: directions`);
    for (const parameter of transition.parameters) {
      const where = `${transition.id}.${parameter.name}`;
      if (parameter.type === 'number') {
        assert.ok(parameter.default >= parameter.min && parameter.default <= parameter.max, `${where}: default outside its range`);
      } else {
        assert.equal(parameter.type, 'color', where);
        assert.equal(parameter.valueFormat, 'rgb-array', where);
        assert.ok(Array.isArray(parameter.default) && parameter.default.length === 3, where);
      }
    }
  }
});

test('13.8: each direct edit names graph fields, and its command is one the engine refuses', () => {
  for (const edit of parameters.directEdits) {
    assert.ok(edit.fields.length > 0 && edit.fields.every((field) => field.startsWith('timeline.')), edit.id);
    assert.match(edit.section, /^13\.8\.\d+$/, edit.id);
    if (edit.command !== null) {
      assert.equal(fixtures.commandStatus[edit.command]?.status, 'not-implemented', `${edit.id}: ${edit.command}`);
    }
  }
});

test('a refused batch leaves the graph it was given untouched', () => {
  for (const entry of replayable.filter((candidate) => candidate.expect.status === 'rejected' && !deferred.has(candidate.id))) {
    const base = fixtures.bases[entry.base];
    const before = canonicalJson(base.graph);
    applyBatch(base.graph, entry.envelopes, fixtures.media[entry.media ?? base.media]);
    assert.equal(canonicalJson(base.graph), before, `${entry.id}: the reference changed its input`);
  }
});
