import { createZodDto } from 'nestjs-zod';
import z from 'zod';

/**
 * Cloud backup administration (FL-160, CLD-301): the bucket claim, the bucket key and the runs. The bucket
 * key is never returned, except once: the key this server generates for the recovery kit. The secret
 * access key of your own bucket is write-only.
 */

export const CloudBackupKeyModeSchema = z
  .enum(['server', 'own-stored', 'own-memory'])
  .describe(
    'server: generated by this server and kept next to its identity; own-stored: your own key with a copy on this server; own-memory: your own key, never saved',
  )
  .meta({ id: 'CloudBackupKeyMode' });

const CloudBackupTargetSchema = z
  .enum(['managed', 'byo-s3'])
  .describe('managed: Frameleaf-managed storage; byo-s3: your own S3-compatible bucket')
  .meta({ id: 'CloudBackupTarget' });

export const CloudBackupTargetSettingSchema = z
  .enum(['off', 'managed', 'byo-s3'])
  .describe('off: no cloud backup; managed: Frameleaf-managed storage; byo-s3: your own S3-compatible bucket')
  .meta({ id: 'CloudBackupTargetSetting' });

const CloudBackupBucketStateSchema = z
  .enum(['empty', 'claimed', 'not-empty'])
  .describe('empty: ready to claim; claimed: holds a Frameleaf claim; not-empty: holds other files')
  .meta({ id: 'CloudBackupBucketState' });

const CloudBackupRunPhaseSchema = z
  .enum(['database', 'reconcile', 'assets', 'profiles', 'manifest', 'done'])
  .describe('Where a run has got to: the database dump, the bucket listing, assets, profile images, the manifest')
  .meta({ id: 'CloudBackupRunPhase' });

const CloudBackupRunStateSchema = z
  .enum(['queued', 'running', 'pausing', 'paused', 'cancelling'])
  .describe('The run in progress: waiting for a worker, running, stopping at its next checkpoint, paused, stopping')
  .meta({ id: 'CloudBackupRunState' });

const CloudBackupLastRunStatusSchema = z
  .enum(['running', 'waiting-for-key', 'completed', 'failed', 'cancelled'])
  .describe('How the last run went; waiting-for-key: an own-memory key is not loaded')
  .meta({ id: 'CloudBackupLastRunStatus' });

const CloudBackupS3Schema = z
  .object({
    endpoint: z.string().max(2048).describe('Storage address (HTTPS)'),
    region: z.string().max(64).optional().describe('Region; empty reads it from the storage address'),
    bucket: z.string().max(63).describe('An empty bucket dedicated to this server'),
    accessKeyId: z.string().max(256).describe('Access key ID'),
    secretAccessKey: z
      .string()
      .max(4096)
      .describe('Secret access key; empty uses the one stored for the same address, bucket and access key'),
  })
  .meta({ id: 'CloudBackupS3Dto' });

const CloudBackupCheckSchema = z.object({ s3: CloudBackupS3Schema }).meta({ id: 'CloudBackupCheckDto' });

const CloudBackupCheckResponseSchema = z
  .object({
    ok: z.boolean().describe('The bucket can be claimed for this server'),
    state: CloudBackupBucketStateSchema,
    message: z.string().describe('What the check found, in plain words'),
  })
  .meta({ id: 'CloudBackupCheckResponseDto' });

const CloudBackupGeneratedKeySchema = z
  .object({
    key: z.string().describe('The new bucket key (base64). Shown once, for the recovery kit; never returned again'),
    fingerprint: z.string().describe('The key fingerprint that matches a key file to its bucket'),
    recoveryCode: z.string().describe('The key as the recovery kit writes it'),
    createdAt: z.string(),
  })
  .meta({ id: 'CloudBackupGeneratedKeyDto' });

const CloudBackupSetupSchema = z
  .object({
    target: CloudBackupTargetSchema,
    s3: CloudBackupS3Schema.optional(),
    keyMode: CloudBackupKeyModeSchema,
    key: z
      .string()
      .min(1)
      .max(4096)
      .describe('The bucket key: the key file, the base64 key or the recovery code. Never returned'),
    acknowledgement: z
      .string()
      .max(64)
      .optional()
      .describe('own-memory only: "I understand" that a lost key makes every backup permanently unreadable'),
  })
  .meta({ id: 'CloudBackupSetupDto' });

const CloudBackupUnlockSchema = z
  .object({
    key: z.string().min(1).max(4096).describe('The key file, the base64 key or the recovery code. Kept in memory only'),
  })
  .meta({ id: 'CloudBackupUnlockDto' });

const CloudBackupLastRunSchema = z
  .object({
    operationId: z.string(),
    status: CloudBackupLastRunStatusSchema,
    startedAt: z.string(),
    finishedAt: z.string().nullable(),
    uploaded: z.int().describe('New or changed files uploaded'),
    skipped: z.int().describe('Files already in the bucket'),
    missing: z.int().describe('Files that were not on disk'),
    bytesUploaded: z.int(),
    error: z.string().nullable(),
  })
  .meta({ id: 'CloudBackupLastRunDto' });

const CloudBackupActiveRunSchema = z
  .object({
    operationId: z.string(),
    state: CloudBackupRunStateSchema,
    phase: CloudBackupRunPhaseSchema,
    progress: z.number().meta({ format: 'double' }).describe('0 to 100'),
    uploaded: z.int(),
    skipped: z.int(),
  })
  .meta({ id: 'CloudBackupActiveRunDto' });

const CloudBackupStatusSchema = z
  .object({
    configured: z.boolean().describe('A bucket is claimed and cloud backup is on'),
    target: CloudBackupTargetSettingSchema,
    managedAvailable: z
      .boolean()
      .describe('Frameleaf-managed storage can be chosen; false until Frameleaf Cloud offers backup storage'),
    endpoint: z.string().nullable(),
    region: z.string().nullable(),
    bucket: z.string().nullable(),
    instanceId: z.string().nullable(),
    claimedAt: z.string().nullable(),
    keyMode: CloudBackupKeyModeSchema.nullable(),
    keyFingerprint: z.string().nullable(),
    keyLoaded: z.boolean().describe('The key is available to this server; false in own-memory mode until unlocked'),
    lastRun: CloudBackupLastRunSchema.nullable(),
    lastSuccessAt: z.string().nullable(),
    lastManifestKey: z.string().nullable(),
    usage: z
      .object({ objects: z.int(), bytes: z.int() })
      .nullable()
      .describe('Unique files this server has in the bucket and their size'),
    activeRun: CloudBackupActiveRunSchema.nullable(),
  })
  .meta({ id: 'CloudBackupStatusResponseDto' });

export class CloudBackupCheckDto extends createZodDto(CloudBackupCheckSchema) {}
export class CloudBackupCheckResponseDto extends createZodDto(CloudBackupCheckResponseSchema) {}
export class CloudBackupGeneratedKeyDto extends createZodDto(CloudBackupGeneratedKeySchema) {}
export class CloudBackupSetupDto extends createZodDto(CloudBackupSetupSchema) {}
export class CloudBackupUnlockDto extends createZodDto(CloudBackupUnlockSchema) {}
export class CloudBackupStatusResponseDto extends createZodDto(CloudBackupStatusSchema) {}
export type CloudBackupS3 = z.infer<typeof CloudBackupS3Schema>;
export type CloudBackupRunState = z.infer<typeof CloudBackupRunStateSchema>;
