import { createZodDto } from 'nestjs-zod';
import z from 'zod';

/**
 * Cloud backup administration (FL-160, CLD-301): the bucket claim, the bucket key and the runs. The bucket
 * key is never returned, except once: the key this server generates for the recovery kit. The secret
 * access key of your own bucket is write-only.
 */

export const CloudBackupKeyModeSchema = z
  .enum(['server', 'own-stored', 'own-memory'])
  .describe(
    'server: generated by this server and kept next to its identity; own-stored: your own key with a copy on this server; own-memory: your own key, never saved',
  )
  .meta({ id: 'CloudBackupKeyMode' });

const CloudBackupTargetSchema = z
  .enum(['managed', 'byo-s3'])
  .describe('managed: Frameleaf-managed storage; byo-s3: your own S3-compatible bucket')
  .meta({ id: 'CloudBackupTarget' });

export const CloudBackupTargetSettingSchema = z
  .enum(['off', 'managed', 'byo-s3'])
  .describe('off: no cloud backup; managed: Frameleaf-managed storage; byo-s3: your own S3-compatible bucket')
  .meta({ id: 'CloudBackupTargetSetting' });

const CloudBackupBucketStateSchema = z
  .enum(['empty', 'claimed', 'not-empty'])
  .describe('empty: ready to claim; claimed: holds a Frameleaf claim; not-empty: holds other files')
  .meta({ id: 'CloudBackupBucketState' });

const CloudBackupRunPhaseSchema = z
  .enum(['database', 'reconcile', 'assets', 'profiles', 'manifest', 'done'])
  .describe('Where a run has got to: the database dump, the bucket listing, assets, profile images, the manifest')
  .meta({ id: 'CloudBackupRunPhase' });

const CloudBackupRunStateSchema = z
  .enum(['queued', 'running', 'pausing', 'paused', 'cancelling'])
  .describe('The run in progress: waiting for a worker, running, stopping at its next checkpoint, paused, stopping')
  .meta({ id: 'CloudBackupRunState' });

const CloudBackupLastRunStatusSchema = z
  .enum(['running', 'waiting-for-key', 'completed', 'failed', 'cancelled'])
  .describe('How the last run went; waiting-for-key: an own-memory key is not loaded')
  .meta({ id: 'CloudBackupLastRunStatus' });

const CloudBackupS3Schema = z
  .object({
    endpoint: z.string().max(2048).describe('Storage address (HTTPS)'),
    region: z.string().max(64).optional().describe('Region; empty reads it from the storage address'),
    bucket: z.string().max(63).describe('An empty bucket dedicated to this server'),
    accessKeyId: z.string().max(256).describe('Access key ID'),
    secretAccessKey: z
      .string()
      .max(4096)
      .describe('Secret access key; empty uses the one stored for the same address, bucket and access key'),
  })
  .meta({ id: 'CloudBackupS3Dto' });

const CloudBackupCheckSchema = z.object({ s3: CloudBackupS3Schema }).meta({ id: 'CloudBackupCheckDto' });

const CloudBackupCheckResponseSchema = z
  .object({
    ok: z.boolean().describe('The bucket can be claimed for this server'),
    state: CloudBackupBucketStateSchema,
    message: z.string().describe('What the check found, in plain words'),
  })
  .meta({ id: 'CloudBackupCheckResponseDto' });

const CloudBackupGeneratedKeySchema = z
  .object({
    key: z.string().describe('The new bucket key (base64). Shown once, for the recovery kit; never returned again'),
    fingerprint: z.string().describe('The key fingerprint that matches a key file to its bucket'),
    recoveryCode: z.string().describe('The key as the recovery kit writes it'),
    createdAt: z.string(),
  })
  .meta({ id: 'CloudBackupGeneratedKeyDto' });

const CloudBackupSetupSchema = z
  .object({
    target: CloudBackupTargetSchema,
    s3: CloudBackupS3Schema.optional(),
    keyMode: CloudBackupKeyModeSchema,
    key: z
      .string()
      .min(1)
      .max(4096)
      .describe('The bucket key: the key file, the base64 key or the recovery code. Never returned'),
    acknowledgement: z
      .string()
      .max(64)
      .optional()
      .describe('own-memory only: "I understand" that a lost key makes every backup permanently unreadable'),
  })
  .meta({ id: 'CloudBackupSetupDto' });

const CloudBackupUnlockSchema = z
  .object({
    key: z.string().min(1).max(4096).describe('The key file, the base64 key or the recovery code. Kept in memory only'),
  })
  .meta({ id: 'CloudBackupUnlockDto' });

/** FL-164: what a `cloud_backup` operation does. */
const CloudBackupTaskSchema = z
  .enum(['backup', 'verify', 'prune'])
  .describe('backup: a backup run; verify: a check of the backed-up files; prune: a clean-up of runs past retention')
  .meta({ id: 'CloudBackupTask' });

const CloudBackupVerifyDepthSchema = z
  .enum(['sample', 'full'])
  .describe('sample: fetch and check this week’s 1/52 of the files; full: check every referenced file is there')
  .meta({ id: 'CloudBackupVerifyDepth' });

const CloudBackupRestoreScopeSchema = z
  .enum(['files', 'asset', 'album', 'database', 'library'])
  .describe(
    'files: into a restore folder for Library Care; asset: one item back in place (made again when it was deleted); album: an album and its members (made again when deleted); database: the dump for the maintenance restore; library: every file back in place and the dump',
  )
  .meta({ id: 'CloudBackupRestoreScope' });

const CloudBackupRestoreDetailsSchema = z
  .enum(['keep', 'fill', 'replace'])
  .describe(
    'How the details of an item still in the library come back. keep: only the file; fill: backed-up values fill empty fields; replace: fields that differ go back to the backup’s values',
  )
  .meta({ id: 'CloudBackupRestoreDetails' });

const CloudBackupAlbumStateSchema = z
  .enum(['deleted', 'missing-items', 'complete'])
  .describe(
    'deleted: the album is gone; missing-items: some of its items are no longer in it; complete: nothing to bring back',
  )
  .meta({ id: 'CloudBackupAlbumState' });

const CloudBackupItemStateSchema = z
  .enum(['active', 'trashed', 'deleted'])
  .describe('Whether the item is in the library now, in the trash, or gone')
  .meta({ id: 'CloudBackupItemState' });

const CloudBackupItemFilterSchema = z
  .enum(['all', 'deleted', 'in-library'])
  .describe('all items; only items no longer in the library; only items still in the library (or its trash)')
  .meta({ id: 'CloudBackupItemFilter' });

/** A manifest key as runs write it: `m/20260926T030000Z.json.gz`. */
const ManifestKeySchema = z
  .string()
  .regex(/^m\/\d{8}T\d{6}Z\.json\.gz$/)
  .describe('The backup run’s manifest in the bucket');

const CloudBackupVerifySchema = z.object({ depth: CloudBackupVerifyDepthSchema }).meta({ id: 'CloudBackupVerifyDto' });

const CloudBackupPruneSchema = z
  .object({
    dryRun: z
      .boolean()
      .describe('Count what the clean-up would remove without removing anything; a clean-up needs a dry run first'),
  })
  .meta({ id: 'CloudBackupPruneDto' });

const CloudBackupEscrowSchema = z
  .object({
    passphrase: z
      .string()
      .min(12)
      .max(1024)
      .describe('Wraps the bucket key before it is sent; never stored and never sent to Frameleaf Cloud'),
  })
  .meta({ id: 'CloudBackupEscrowDto' });

const CloudBackupRestoreSchema = z
  .object({
    manifestKey: ManifestKeySchema,
    scope: CloudBackupRestoreScopeSchema,
    assetIds: z
      .array(z.uuidv4())
      .max(10_000)
      .optional()
      .describe('files: the items to restore (every item when absent); asset: exactly one item'),
    albumId: z.uuidv4().optional().describe('album: the album to restore'),
    details: CloudBackupRestoreDetailsSchema.optional().describe(
      'asset and album: how details of items still in the library come back; keep when absent',
    ),
  })
  .meta({ id: 'CloudBackupRestoreDto' });

const CloudBackupManifestAlbumsSchema = z
  .object({ manifestKey: ManifestKeySchema })
  .meta({ id: 'CloudBackupManifestAlbumsDto' });

const CloudBackupManifestItemsSchema = z
  .object({
    manifestKey: ManifestKeySchema,
    query: z.string().max(200).optional().describe('Part of a file name'),
    filter: CloudBackupItemFilterSchema.optional(),
    limit: z.int().min(1).max(500).optional().describe('Items to return; 100 when absent'),
  })
  .meta({ id: 'CloudBackupManifestItemsDto' });

const CloudBackupManifestSchema = z
  .object({
    key: z.string(),
    status: z.enum(['complete', 'degraded']).meta({ id: 'CloudBackupManifestStatus' }),
    createdAt: z.string(),
    finishedAt: z.string().nullable(),
    assets: z.int(),
    files: z.int(),
    bytes: z.int(),
    databaseKey: z.string().nullable().describe('The database dump this backup pairs with'),
  })
  .meta({ id: 'CloudBackupManifestDto' });

const CloudBackupManifestsResponseSchema = z
  .object({ manifests: z.array(CloudBackupManifestSchema).describe('Kept backups, newest first') })
  .meta({ id: 'CloudBackupManifestsResponseDto' });

const CloudBackupManifestItemSchema = z
  .object({
    assetId: z.string(),
    name: z.string().describe('The original’s file name when it was backed up; empty for a Locked item'),
    locked: z.boolean().describe('A Locked item: never named in this list'),
    ownerId: z.string().nullable(),
    ownerName: z.string().nullable(),
    files: z.int(),
    bytes: z.int(),
    modifiedAt: z.string().nullable().describe('When the original was last written before the backup'),
    state: CloudBackupItemStateSchema,
    hasDetails: z
      .boolean()
      .describe('The backup holds the item’s details, so a deleted item comes back as it was, not only as a file'),
  })
  .meta({ id: 'CloudBackupManifestItemDto' });

const CloudBackupManifestAlbumSchema = z
  .object({
    albumId: z.string(),
    name: z.string(),
    ownerId: z.string(),
    ownerName: z.string().nullable(),
    items: z.int().describe('Items the album held in this backup'),
    missing: z.int().describe('Of those, items no longer in the album'),
    state: CloudBackupAlbumStateSchema,
  })
  .meta({ id: 'CloudBackupManifestAlbumDto' });

const CloudBackupManifestAlbumsResponseSchema = z
  .object({
    manifestKey: z.string(),
    hasDetails: z.boolean().describe('The backup records albums; false for a backup made before they were recorded'),
    albums: z.array(CloudBackupManifestAlbumSchema).describe('Deleted albums and albums missing items, by name'),
  })
  .meta({ id: 'CloudBackupManifestAlbumsResponseDto' });

const CloudBackupManifestItemsResponseSchema = z
  .object({
    manifestKey: z.string(),
    total: z.int().describe('Items that match, of which at most `limit` are listed'),
    items: z.array(CloudBackupManifestItemSchema),
  })
  .meta({ id: 'CloudBackupManifestItemsResponseDto' });

const CloudBackupLastVerifySchema = z
  .object({
    operationId: z.string(),
    depth: CloudBackupVerifyDepthSchema,
    at: z.string(),
    status: z.enum(['passed', 'degraded', 'failed']).meta({ id: 'CloudBackupVerifyStatus' }),
    checked: z.int(),
    missing: z.int(),
    mismatched: z.int(),
    degradedManifests: z.int(),
    error: z.string().nullable(),
  })
  .meta({ id: 'CloudBackupLastVerifyDto' });

const CloudBackupLastPruneSchema = z
  .object({
    operationId: z.string(),
    dryRun: z.boolean(),
    at: z.string(),
    manifestsKept: z.int(),
    manifestsRemoved: z.int(),
    objectsRemoved: z.int(),
    bytesRemoved: z.int(),
    dumpsRemoved: z.int(),
  })
  .meta({ id: 'CloudBackupLastPruneDto' });

const CloudBackupManagedSchema = z
  .object({
    storageId: z.uuid().nullable().optional(),
    location: z
      .object({
        locationId: z.string(),
        cityId: z.string(),
        city: z.string(),
        country: z.string(),
        countryCode: z.string(),
      })
      .meta({ id: 'CloudBackupLocationDto' })
      .nullable()
      .optional(),
    readOnly: z.boolean().describe('Uploads are stopped; restores keep working'),
    readOnlyReason: z
      .string()
      .nullable()
      .describe(
        'Why uploads are stopped, as Frameleaf Cloud says: purge_hold, entitlement, unlinked, suspended, purging or plan_full (the plan is full; new items wait until it is upgraded). Open-ended: show an unknown value generically.',
      ),
    quotaBytes: z.int().describe('Storage included with the plan; more is added in 1 TB blocks'),
    usedBytes: z.int().nullable(),
    objects: z.int().nullable(),
    allowanceBytes: z.int().nullable(),
    extraBlocks: z.int().nullable(),
    measuredAt: z.string().nullable(),
    refusal: z.string().nullable().describe('Why Frameleaf Cloud last refused backup storage'),
  })
  .meta({ id: 'CloudBackupManagedDto' });

const CloudBackupEscrowStatusSchema = z
  .object({
    available: z.boolean().describe('Server key mode and a linked server: escrow can be turned on'),
    stored: z.boolean(),
    storedAt: z.string().nullable(),
  })
  .meta({ id: 'CloudBackupEscrowStatusDto' });

const CloudBackupActiveRestoreSchema = z
  .object({
    operationId: z.string(),
    state: CloudBackupRunStateSchema,
    scope: CloudBackupRestoreScopeSchema,
    progress: z.number().meta({ format: 'double' }).describe('0 to 100'),
    files: z.int(),
    filesTotal: z.int(),
    bytes: z.int(),
    bytesTotal: z.int(),
  })
  .meta({ id: 'CloudBackupActiveRestoreDto' });

const CloudBackupLastRestoreSchema = z
  .object({
    operationId: z.string(),
    scope: CloudBackupRestoreScopeSchema,
    manifestKey: z.string(),
    status: z.enum(['completed', 'failed', 'cancelled']).meta({ id: 'CloudBackupRestoreStatus' }),
    at: z.string(),
    files: z.int(),
    bytes: z.int(),
    skipped: z.int(),
    replaced: z.int(),
    destination: z.string().nullable().describe('The folder a files restore wrote to'),
    recreated: z.int().describe('Deleted items made again'),
    detailsRestored: z.int().describe('Items still in the library whose details came back'),
    databaseFile: z.string().nullable().describe('The restored dump, listed by the maintenance restore'),
    error: z.string().nullable(),
  })
  .meta({ id: 'CloudBackupLastRestoreDto' });

const CloudBackupLastRunSchema = z
  .object({
    operationId: z.string(),
    status: CloudBackupLastRunStatusSchema,
    startedAt: z.string(),
    finishedAt: z.string().nullable(),
    uploaded: z.int().describe('New or changed files uploaded'),
    skipped: z.int().describe('Files already in the bucket'),
    missing: z.int().describe('Files that were not on disk'),
    bytesUploaded: z.int(),
    error: z.string().nullable(),
  })
  .meta({ id: 'CloudBackupLastRunDto' });

const CloudBackupActiveRunSchema = z
  .object({
    operationId: z.string(),
    task: CloudBackupTaskSchema,
    state: CloudBackupRunStateSchema,
    phase: CloudBackupRunPhaseSchema,
    progress: z.number().meta({ format: 'double' }).describe('0 to 100'),
    uploaded: z.int(),
    skipped: z.int(),
    bytesUploaded: z.int(),
    checked: z.int().describe('verify: files checked so far'),
  })
  .meta({ id: 'CloudBackupActiveRunDto' });

const CloudBackupStatusSchema = z
  .object({
    configured: z.boolean().describe('A bucket is claimed and cloud backup is on'),
    target: CloudBackupTargetSettingSchema,
    managedAvailable: z
      .boolean()
      .describe('Frameleaf-managed storage can be chosen: this server is linked to Frameleaf Cloud'),
    endpoint: z.string().nullable(),
    region: z.string().nullable(),
    bucket: z.string().nullable(),
    instanceId: z.string().nullable(),
    claimedAt: z.string().nullable(),
    keyMode: CloudBackupKeyModeSchema.nullable(),
    keyFingerprint: z.string().nullable(),
    keyLoaded: z.boolean().describe('The key is available to this server; false in own-memory mode until unlocked'),
    lastRun: CloudBackupLastRunSchema.nullable(),
    lastSuccessAt: z.string().nullable(),
    lastManifestKey: z.string().nullable(),
    usage: z
      .object({ objects: z.int(), bytes: z.int() })
      .nullable()
      .describe('Unique files this server has in the bucket and their size'),
    activeRun: CloudBackupActiveRunSchema.nullable(),
    activeRestore: CloudBackupActiveRestoreSchema.nullable(),
    lastRestore: CloudBackupLastRestoreSchema.nullable(),
    lastVerify: CloudBackupLastVerifySchema.nullable(),
    lastPrune: CloudBackupLastPruneSchema.nullable(),
    managed: CloudBackupManagedSchema.nullable().describe('Frameleaf-managed storage only'),
    escrow: CloudBackupEscrowStatusSchema,
  })
  .meta({ id: 'CloudBackupStatusResponseDto' });

export class CloudBackupCheckDto extends createZodDto(CloudBackupCheckSchema) {}
export class CloudBackupCheckResponseDto extends createZodDto(CloudBackupCheckResponseSchema) {}
export class CloudBackupGeneratedKeyDto extends createZodDto(CloudBackupGeneratedKeySchema) {}
export class CloudBackupSetupDto extends createZodDto(CloudBackupSetupSchema) {}
export class CloudBackupUnlockDto extends createZodDto(CloudBackupUnlockSchema) {}
export class CloudBackupStatusResponseDto extends createZodDto(CloudBackupStatusSchema) {}
export class CloudBackupVerifyDto extends createZodDto(CloudBackupVerifySchema) {}
export class CloudBackupPruneDto extends createZodDto(CloudBackupPruneSchema) {}
export class CloudBackupEscrowDto extends createZodDto(CloudBackupEscrowSchema) {}
export class CloudBackupRestoreDto extends createZodDto(CloudBackupRestoreSchema) {}
export class CloudBackupManifestItemsDto extends createZodDto(CloudBackupManifestItemsSchema) {}
export class CloudBackupManifestAlbumsDto extends createZodDto(CloudBackupManifestAlbumsSchema) {}
export class CloudBackupManifestAlbumsResponseDto extends createZodDto(CloudBackupManifestAlbumsResponseSchema) {}
export class CloudBackupManifestsResponseDto extends createZodDto(CloudBackupManifestsResponseSchema) {}
export class CloudBackupManifestItemsResponseDto extends createZodDto(CloudBackupManifestItemsResponseSchema) {}
export type CloudBackupS3 = z.infer<typeof CloudBackupS3Schema>;
export type CloudBackupManifestItem = z.infer<typeof CloudBackupManifestItemSchema>;
export type CloudBackupManifestAlbum = z.infer<typeof CloudBackupManifestAlbumSchema>;
export type CloudBackupRunState = z.infer<typeof CloudBackupRunStateSchema>;
