import {
  AnalyticsCameraKind,
  AnalyticsGrain,
  AnalyticsMetadataField,
  AnalyticsMeasurementScope,
  AnalyticsRange,
  AnalyticsScopeKind,
  AnalyticsSeriesId,
  AnalyticsSeriesOwner,
  AnalyticsState,
  AnalyticsUnit,
  AnalyticsView,
  type AnalyticsReportResponseDto,
} from '@immich/sdk';

/** A small, hand-checked analytics report for specs (FL-79). */
export const analyticsReportFixture = (
  overrides: Partial<AnalyticsReportResponseDto> = {},
): AnalyticsReportResponseDto => ({
  scope: 'all',
  scopeKind: AnalyticsScopeKind.Host,
  scopeLabel: '',
  range: AnalyticsRange.$90Days,
  from: '2026-09-13',
  through: '2026-09-19',
  generatedAt: '2026-09-19T12:00:00.000Z',
  definitions: [
    {
      id: AnalyticsSeriesId.ProcessingEstimatedCostUsd,
      unit: AnalyticsUnit.Usd,
      grain: AnalyticsGrain.Day,
      source: 'machine-learning request accounting; not a bill',
      owner: AnalyticsSeriesOwner.Processing,
      scopes: [AnalyticsScopeKind.Host],
      measurementScope: AnalyticsMeasurementScope.Host,
      collected: false,
      estimate: true,
      available: true,
    },
  ],
  summary: {
    items: 100,
    photos: 90,
    videos: 10,
    raw: 5,
    files: 104,
    unmeasuredFiles: 1,
    logicalBytes: 10_000,
    uploadedLogicalBytes: 7000,
    externalLogicalBytes: 3000,
    physicalBytes: 8000,
    uploadedPhysicalBytes: 5000,
    externalPhysicalBytes: 3000,
    savedBytes: 2000,
    duplicateReferences: 4,
  },
  host: {
    state: AnalyticsState.Measured,
    observedAt: '2026-09-19T12:00:00.000Z',
    volumeUsedBytes: 600_000,
    capacityBytes: 1_000_000,
    freeBytes: 350_000,
  },
  history: {
    state: AnalyticsState.Measured,
    lastObservedAt: '2026-09-19T00:05:00.000Z',
    staleAfterHours: 36,
    dayRetentionDays: 120,
    weekRetentionDays: 800,
  },
  series: [
    {
      key: '2026-09-07',
      from: '2026-09-13',
      through: '2026-09-13',
      partial: true,
      photos: 0,
      videos: 0,
      completed: 0,
      failed: 0,
      items: null,
      logicalBytes: null,
      physicalBytes: null,
      observedAt: null,
    },
    {
      key: '2026-09-14',
      from: '2026-09-14',
      through: '2026-09-19',
      partial: true,
      photos: 3,
      videos: 1,
      completed: 9,
      failed: 1,
      items: 100,
      logicalBytes: 10_000,
      physicalBytes: 8000,
      observedAt: '2026-09-19T00:05:00.000Z',
    },
  ],
  days: [
    { date: '2026-09-13', captured: 0, uploaded: 0 },
    { date: '2026-09-14', captured: 0, uploaded: 0 },
    { date: '2026-09-15', captured: 2, uploaded: 0 },
    { date: '2026-09-16', captured: 0, uploaded: 0 },
    { date: '2026-09-17', captured: 0, uploaded: 0 },
    { date: '2026-09-18', captured: 5, uploaded: 4 },
    { date: '2026-09-19', captured: 0, uploaded: 0 },
  ],
  cameras: [
    { name: 'Apple iPhone 16 Pro', kind: AnalyticsCameraKind.Model, count: 80 },
    { name: null, kind: AnalyticsCameraKind.Unknown, count: 20 },
  ],
  metadata: [
    { field: AnalyticsMetadataField.CaptureDate, present: 98, missing: 2, total: 100 },
    { field: AnalyticsMetadataField.Location, present: 60, missing: 40, total: 100 },
    { field: AnalyticsMetadataField.CameraModel, present: 80, missing: 20, total: 100 },
    { field: AnalyticsMetadataField.AiDescription, present: 40, missing: 60, total: 100 },
    { field: AnalyticsMetadataField.Checksum, present: 100, missing: 0, total: 100 },
  ],
  views: [
    { view: AnalyticsView.Timeline, photos: 70, videos: 8, total: 78, overlaps: false },
    { view: AnalyticsView.Favorites, photos: 12, videos: 2, total: 14, overlaps: true },
    { view: AnalyticsView.Archive, photos: 15, videos: 1, total: 16, overlaps: false },
    { view: AnalyticsView.Trash, photos: 5, videos: 1, total: 6, overlaps: false },
  ],
  albums: {
    total: 3,
    owned: 3,
    shared: 1,
    ownedShared: 1,
    notShared: 2,
    unlisted: 1,
    albums: [
      { id: 'a1', name: 'Summer in the Rockies', ownerName: 'Taylor', owned: true, shared: true },
      { id: 'a2', name: 'Winter afternoons', ownerName: 'Taylor', owned: true, shared: false },
    ],
  },
  processing: {
    available: true,
    attempts: 10,
    completed: 9,
    failed: 1,
    durationMs: 1000,
    estimatedCostUsd: 0.0123,
    costedAttempts: 6,
    uncostedAttempts: 4,
  },
  ...overrides,
});
