import {
  AnalyticsCameraKind,
  AnalyticsFocalLengthDtoKey,
  AnalyticsGrain,
  AnalyticsMetadataField,
  AnalyticsMeasurementScope,
  AnalyticsNamedCountKind,
  AnalyticsOrientationDtoKey,
  AnalyticsPhotoFormatDtoKey,
  AnalyticsRange,
  AnalyticsScopeKind,
  AnalyticsSeriesId,
  AnalyticsSeriesOwner,
  AnalyticsState,
  AnalyticsUnit,
  AnalyticsVideoResolutionDtoKey,
  AnalyticsView,
  type AnalyticsInsightsDto,
  type AnalyticsReportResponseDto,
} from '@immich/sdk';

/** Punchcard counts for the fixture: Monday 9 am is the peak. Adds up to 100. */
const PUNCH: Record<string, number> = { '1:9': 50, '6:18': 30, '7:10': 20 };

/**
 * The dashboard insights of the fixture report. With `hiddenItems` 0 every breakdown adds up to
 * the summary's 100 items (90 photos, 10 videos); the owner's own scope, so people and places are in.
 */
export const analyticsInsightsFixture = (overrides: Partial<AnalyticsInsightsDto> = {}): AnalyticsInsightsDto => ({
  hiddenItems: 0,
  capturesByYear: [
    { year: 2019, count: 10 },
    { year: 2024, count: 40 },
    { year: 2026, count: 50 },
  ],
  punchcard: Array.from({ length: 168 }, (_, index) => {
    const weekday = Math.floor(index / 24) + 1;
    const hour = index % 24;
    return { weekday, hour, count: PUNCH[`${weekday}:${hour}`] ?? 0 };
  }),
  lenses: [
    { name: 'iPhone 16 Pro back camera', kind: AnalyticsNamedCountKind.Named, count: 60 },
    { name: null, kind: AnalyticsNamedCountKind.Other, count: 10 },
    { name: null, kind: AnalyticsNamedCountKind.Unknown, count: 30 },
  ],
  focalLengths: [
    { key: AnalyticsFocalLengthDtoKey.$016, count: 5 },
    { key: AnalyticsFocalLengthDtoKey.$1728, count: 50 },
    { key: AnalyticsFocalLengthDtoKey.$2940, count: 10 },
    { key: AnalyticsFocalLengthDtoKey.$4170, count: 5 },
    { key: AnalyticsFocalLengthDtoKey.$71135, count: 0 },
    { key: AnalyticsFocalLengthDtoKey.$136300, count: 0 },
    { key: AnalyticsFocalLengthDtoKey.$301, count: 0 },
    { key: AnalyticsFocalLengthDtoKey.Unknown, count: 30 },
  ],
  photoFormats: [
    { key: AnalyticsPhotoFormatDtoKey.Heic, count: 60 },
    { key: AnalyticsPhotoFormatDtoKey.Jpeg, count: 20 },
    { key: AnalyticsPhotoFormatDtoKey.Raw, count: 5 },
    { key: AnalyticsPhotoFormatDtoKey.Png, count: 3 },
    { key: AnalyticsPhotoFormatDtoKey.Other, count: 2 },
  ],
  videoResolutions: [
    { key: AnalyticsVideoResolutionDtoKey.$4K, count: 4 },
    { key: AnalyticsVideoResolutionDtoKey.$1080P, count: 5 },
    { key: AnalyticsVideoResolutionDtoKey.$720P, count: 0 },
    { key: AnalyticsVideoResolutionDtoKey.Sd, count: 0 },
    { key: AnalyticsVideoResolutionDtoKey.Unknown, count: 1 },
  ],
  orientation: [
    { key: AnalyticsOrientationDtoKey.Landscape, count: 50 },
    { key: AnalyticsOrientationDtoKey.Portrait, count: 40 },
    { key: AnalyticsOrientationDtoKey.Square, count: 5 },
    { key: AnalyticsOrientationDtoKey.Panorama, count: 2 },
    { key: AnalyticsOrientationDtoKey.Unknown, count: 3 },
  ],
  livePhotos: 12,
  hdr: { probedVideos: 8, hdrVideos: 3, dolbyVisionVideos: 1 },
  coverage: { facesChecked: 90, searchIndexed: 95 },
  peopleAndPlaces: {
    faces: 70,
    itemsWithFaces: 40,
    itemsWithoutFaces: 60,
    namedPeople: 3,
    pets: 1,
    topPeople: [
      { id: 'person-emma', name: 'Emma', count: 25 },
      { id: 'person-jamie', name: 'Jamie', count: 15 },
    ],
    geotagged: 60,
    countries: 2,
    cities: 3,
    places: [
      { name: 'Lisbon', kind: AnalyticsNamedCountKind.Named, count: 20 },
      { name: 'Banff', kind: AnalyticsNamedCountKind.Named, count: 30 },
      { name: null, kind: AnalyticsNamedCountKind.Other, count: 10 },
      { name: null, kind: AnalyticsNamedCountKind.Unknown, count: 40 },
    ],
  },
  records: {
    oldestCapture: { date: '2019-06-14', name: 'IMG_0001.JPG' },
    largestFile: { bytes: 3 * 1024 ** 3, name: 'Recital.mov' },
    longestVideo: { durationMs: 6_130_000, name: 'Recital.mov' },
    videoDurationMs: 7_200_000,
    videoHours: 2,
  },
  ...overrides,
});

/** A small, hand-checked analytics report for specs (FL-79). */
export const analyticsReportFixture = (
  overrides: Partial<AnalyticsReportResponseDto> = {},
): AnalyticsReportResponseDto => ({
  scope: 'all',
  scopeKind: AnalyticsScopeKind.Host,
  scopeLabel: '',
  range: AnalyticsRange.$90Days,
  from: '2026-09-13',
  through: '2026-09-19',
  generatedAt: '2026-09-19T12:00:00.000Z',
  definitions: [
    {
      id: AnalyticsSeriesId.ProcessingEstimatedCostUsd,
      unit: AnalyticsUnit.Usd,
      grain: AnalyticsGrain.Day,
      source: 'machine-learning request accounting; not a bill',
      owner: AnalyticsSeriesOwner.Processing,
      scopes: [AnalyticsScopeKind.Host],
      measurementScope: AnalyticsMeasurementScope.Host,
      collected: false,
      estimate: true,
      available: true,
    },
  ],
  summary: {
    items: 100,
    photos: 90,
    videos: 10,
    raw: 5,
    files: 104,
    unmeasuredFiles: 1,
    logicalBytes: 10_000,
    uploadedLogicalBytes: 7000,
    externalLogicalBytes: 3000,
    physicalBytes: 8000,
    uploadedPhysicalBytes: 5000,
    externalPhysicalBytes: 3000,
    savedBytes: 2000,
    duplicateReferences: 4,
  },
  host: {
    state: AnalyticsState.Measured,
    observedAt: '2026-09-19T12:00:00.000Z',
    volumeUsedBytes: 600_000,
    capacityBytes: 1_000_000,
    freeBytes: 350_000,
  },
  history: {
    state: AnalyticsState.Measured,
    lastObservedAt: '2026-09-19T00:05:00.000Z',
    staleAfterHours: 36,
    dayRetentionDays: 120,
    weekRetentionDays: 800,
  },
  series: [
    {
      key: '2026-09-07',
      from: '2026-09-13',
      through: '2026-09-13',
      partial: true,
      photos: 0,
      videos: 0,
      completed: 0,
      failed: 0,
      items: null,
      logicalBytes: null,
      physicalBytes: null,
      observedAt: null,
    },
    {
      key: '2026-09-14',
      from: '2026-09-14',
      through: '2026-09-19',
      partial: true,
      photos: 3,
      videos: 1,
      completed: 9,
      failed: 1,
      items: 100,
      logicalBytes: 10_000,
      physicalBytes: 8000,
      observedAt: '2026-09-19T00:05:00.000Z',
    },
  ],
  days: [
    { date: '2026-09-13', captured: 0, uploaded: 0 },
    { date: '2026-09-14', captured: 0, uploaded: 0 },
    { date: '2026-09-15', captured: 2, uploaded: 0 },
    { date: '2026-09-16', captured: 0, uploaded: 0 },
    { date: '2026-09-17', captured: 0, uploaded: 0 },
    { date: '2026-09-18', captured: 5, uploaded: 4 },
    { date: '2026-09-19', captured: 0, uploaded: 0 },
  ],
  cameras: [
    { name: 'Apple iPhone 16 Pro', kind: AnalyticsCameraKind.Model, count: 80 },
    { name: null, kind: AnalyticsCameraKind.Unknown, count: 20 },
  ],
  metadata: [
    { field: AnalyticsMetadataField.CaptureDate, present: 98, missing: 2, total: 100 },
    { field: AnalyticsMetadataField.Location, present: 60, missing: 40, total: 100 },
    { field: AnalyticsMetadataField.CameraModel, present: 80, missing: 20, total: 100 },
    { field: AnalyticsMetadataField.AiDescription, present: 40, missing: 60, total: 100 },
    { field: AnalyticsMetadataField.Checksum, present: 100, missing: 0, total: 100 },
  ],
  views: [
    { view: AnalyticsView.Timeline, photos: 70, videos: 8, total: 78, overlaps: false },
    { view: AnalyticsView.Favorites, photos: 12, videos: 2, total: 14, overlaps: true },
    { view: AnalyticsView.Archive, photos: 15, videos: 1, total: 16, overlaps: false },
    { view: AnalyticsView.Trash, photos: 5, videos: 1, total: 6, overlaps: false },
  ],
  albums: {
    total: 3,
    owned: 3,
    shared: 1,
    ownedShared: 1,
    notShared: 2,
    unlisted: 1,
    albums: [
      { id: 'a1', name: 'Summer in the Rockies', ownerName: 'Taylor', owned: true, shared: true },
      { id: 'a2', name: 'Winter afternoons', ownerName: 'Taylor', owned: true, shared: false },
    ],
  },
  processing: {
    available: true,
    attempts: 10,
    completed: 9,
    failed: 1,
    durationMs: 1000,
    estimatedCostUsd: 0.0123,
    costedAttempts: 6,
    uncostedAttempts: 4,
  },
  insights: analyticsInsightsFixture(),
  ...overrides,
});
