// Generated with the FL-71 settings coverage scan and reviewed by hand; see settings-coverage.spec.ts.
// Each row names where one administrator setting (a leaf of AdminConfigDto) is edited, as a code
// token that must appear in that file. Patterns use `*` for one path segment.
export type SettingsLeafKind =
  /** An ordinary control on a settings page. */
  | 'control'
  /** A write-only credential, replaced or cleared in its credential dialog (FL-67), never a draft value. */
  | 'credential'
  /** The read-only "stored" flag of a credential. */
  | 'credential-state'
  /** Fixed by server policy and shown as a locked row. */
  | 'policy'
  /** Written by the server itself; kept out of the draft. */
  | 'server-managed'
  /** Set by a resource action (a consent step), not a form field. */
  | 'resource-action'
  /** Part of the save protocol (a revision check), not a setting. */
  | 'protocol';

export type SettingsLeafCoverage = { pattern: string; kind: SettingsLeafKind; file: string; evidence: string };

export const SETTINGS_LEAF_COVERAGE: readonly SettingsLeafCoverage[] = Object.freeze([
  {
    pattern: 'analytics.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/LoggingSettings.svelte',
    evidence: 'analytics.enabled',
  },
  {
    pattern: 'analytics.historyDays',
    kind: 'control',
    file: 'src/routes/admin/system-settings/LoggingSettings.svelte',
    evidence: 'analytics.historyDays',
  },
  {
    pattern: 'backup.database.cronExpression',
    kind: 'control',
    file: 'src/routes/admin/system-settings/BackupSettings.svelte',
    evidence: 'database.cronExpression',
  },
  {
    pattern: 'backup.database.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/BackupSettings.svelte',
    evidence: 'database.enabled',
  },
  {
    pattern: 'backup.database.keepLastAmount',
    kind: 'control',
    file: 'src/routes/admin/system-settings/BackupSettings.svelte',
    evidence: 'database.keepLastAmount',
  },
  {
    pattern: 'ffmpeg.accel',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.accel',
  },
  {
    pattern: 'ffmpeg.accelDecode',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.accelDecode',
  },
  {
    pattern: 'ffmpeg.acceptedAudioCodecs',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.acceptedAudioCodecs',
  },
  {
    pattern: 'ffmpeg.acceptedContainers',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.acceptedContainers',
  },
  {
    pattern: 'ffmpeg.acceptedVideoCodecs',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.acceptedVideoCodecs',
  },
  {
    pattern: 'ffmpeg.bframes',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.bframes',
  },
  {
    pattern: 'ffmpeg.cqMode',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.cqMode',
  },
  {
    pattern: 'ffmpeg.crf',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.crf',
  },
  {
    pattern: 'ffmpeg.gopSize',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.gopSize',
  },
  {
    pattern: 'ffmpeg.maxBitrate',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.maxBitrate',
  },
  {
    pattern: 'ffmpeg.preferredHwDevice',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.preferredHwDevice',
  },
  {
    pattern: 'ffmpeg.preset',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.preset',
  },
  {
    pattern: 'ffmpeg.realtime.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'realtime.enabled',
  },
  {
    pattern: 'ffmpeg.realtime.resolutions',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'realtime.resolutions',
  },
  {
    pattern: 'ffmpeg.realtime.videoCodecs',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'realtime.videoCodecs',
  },
  {
    pattern: 'ffmpeg.refs',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.refs',
  },
  {
    pattern: 'ffmpeg.targetAudioCodec',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.targetAudioCodec',
  },
  {
    pattern: 'ffmpeg.targetResolution',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.targetResolution',
  },
  {
    pattern: 'ffmpeg.targetVideoCodec',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.targetVideoCodec',
  },
  {
    pattern: 'ffmpeg.temporalAQ',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.temporalAQ',
  },
  {
    pattern: 'ffmpeg.threads',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.threads',
  },
  {
    pattern: 'ffmpeg.tonemap',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.tonemap',
  },
  {
    pattern: 'ffmpeg.transcode',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.transcode',
  },
  {
    pattern: 'ffmpeg.twoPass',
    kind: 'control',
    file: 'src/routes/admin/system-settings/FFmpegSettings.svelte',
    evidence: 'ffmpeg.twoPass',
  },
  {
    pattern: 'image.colorspace',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ImageSettings.svelte',
    evidence: 'image.colorspace',
  },
  {
    pattern: 'image.enhancedRaw.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ImageSettings.svelte',
    evidence: 'enhancedRaw?.enabled',
  },
  {
    pattern: 'image.extractEmbedded',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ImageSettings.svelte',
    evidence: 'image.extractEmbedded',
  },
  {
    pattern: 'image.fullsize.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ImageSettings.svelte',
    evidence: 'fullsize.enabled',
  },
  {
    pattern: 'image.fullsize.format',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ImageSettings.svelte',
    evidence: 'fullsize.format',
  },
  {
    pattern: 'image.fullsize.progressive',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ImageSettings.svelte',
    evidence: 'fullsize.progressive',
  },
  {
    pattern: 'image.fullsize.quality',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ImageSettings.svelte',
    evidence: 'fullsize.quality',
  },
  {
    pattern: 'image.preview.format',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ImageSettings.svelte',
    evidence: 'preview.format',
  },
  {
    pattern: 'image.preview.progressive',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ImageSettings.svelte',
    evidence: 'preview.progressive',
  },
  {
    pattern: 'image.preview.quality',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ImageSettings.svelte',
    evidence: 'preview.quality',
  },
  {
    pattern: 'image.preview.size',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ImageSettings.svelte',
    evidence: 'preview.size',
  },
  {
    pattern: 'image.thumbnail.format',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ImageSettings.svelte',
    evidence: 'thumbnail.format',
  },
  {
    pattern: 'image.thumbnail.progressive',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ImageSettings.svelte',
    evidence: 'thumbnail.progressive',
  },
  {
    pattern: 'image.thumbnail.quality',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ImageSettings.svelte',
    evidence: 'thumbnail.quality',
  },
  {
    pattern: 'image.thumbnail.size',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ImageSettings.svelte',
    evidence: 'thumbnail.size',
  },
  {
    pattern: 'integrityChecks.checksumFiles.cronExpression',
    kind: 'control',
    file: 'src/routes/admin/system-settings/IntegrityChecksSettings.svelte',
    evidence: 'checksumFiles.cronExpression',
  },
  {
    pattern: 'integrityChecks.checksumFiles.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/IntegrityChecksSettings.svelte',
    evidence: 'checksumFiles.enabled',
  },
  {
    pattern: 'integrityChecks.checksumFiles.percentageLimit',
    kind: 'control',
    file: 'src/routes/admin/system-settings/IntegrityChecksSettings.svelte',
    evidence: 'checksumFiles.percentageLimit',
  },
  {
    pattern: 'integrityChecks.checksumFiles.timeLimit',
    kind: 'control',
    file: 'src/routes/admin/system-settings/IntegrityChecksSettings.svelte',
    evidence: 'checksumFiles.timeLimit',
  },
  {
    pattern: 'integrityChecks.missingFiles.cronExpression',
    kind: 'control',
    file: 'src/routes/admin/system-settings/IntegrityChecksSettings.svelte',
    evidence: 'missingFiles.cronExpression',
  },
  {
    pattern: 'integrityChecks.missingFiles.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/IntegrityChecksSettings.svelte',
    evidence: 'missingFiles.enabled',
  },
  {
    pattern: 'integrityChecks.untrackedFiles.cronExpression',
    kind: 'control',
    file: 'src/routes/admin/system-settings/IntegrityChecksSettings.svelte',
    evidence: 'untrackedFiles.cronExpression',
  },
  {
    pattern: 'integrityChecks.untrackedFiles.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/IntegrityChecksSettings.svelte',
    evidence: 'untrackedFiles.enabled',
  },
  {
    pattern: 'job.*.concurrency',
    kind: 'control',
    file: 'src/lib/components/frameleaf/jobs/JobsConcurrencyDialog.svelte',
    evidence: '?.concurrency',
  },
  {
    pattern: 'library.scan.cronExpression',
    kind: 'control',
    file: 'src/routes/admin/system-settings/LibrarySettings.svelte',
    evidence: 'scan.cronExpression',
  },
  {
    pattern: 'library.scan.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/LibrarySettings.svelte',
    evidence: 'scan.enabled',
  },
  {
    pattern: 'library.watch.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/LibrarySettings.svelte',
    evidence: 'watch.enabled',
  },
  {
    pattern: 'localFeatures.askSearch.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/SearchLabelsSection.svelte',
    evidence: 'askSearch.enabled',
  },
  {
    pattern: 'localFeatures.askSearch.maxResults',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/SearchLabelsSection.svelte',
    evidence: 'askSearch.maxResults',
  },
  {
    pattern: 'logging.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/LoggingSettings.svelte',
    evidence: 'logging.enabled',
  },
  {
    pattern: 'logging.level',
    kind: 'control',
    file: 'src/routes/admin/system-settings/LoggingSettings.svelte',
    evidence: 'logging.level',
  },
  {
    pattern: 'machineLearning.availabilityChecks.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/AvailabilityChecksSection.svelte',
    evidence: 'availabilityChecks.enabled',
  },
  {
    pattern: 'machineLearning.availabilityChecks.interval',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/AvailabilityChecksSection.svelte',
    evidence: 'availabilityChecks.interval',
  },
  {
    pattern: 'machineLearning.availabilityChecks.timeout',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/AvailabilityChecksSection.svelte',
    evidence: 'availabilityChecks.timeout',
  },
  {
    pattern: 'machineLearning.clip.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/DuplicateDetectionSection.svelte',
    evidence: 'clip.enabled',
  },
  {
    pattern: 'machineLearning.clip.modelName',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/SmartSearchSection.svelte',
    evidence: 'clip.modelName',
  },
  {
    pattern: 'machineLearning.clip.zeroShotTagging.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/SearchLabelsSection.svelte',
    evidence: 'zeroShotTagging.enabled',
  },
  {
    pattern: 'machineLearning.clip.zeroShotTagging.maxTags',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/SearchLabelsSection.svelte',
    evidence: 'zeroShotTagging.maxTags',
  },
  {
    pattern: 'machineLearning.clip.zeroShotTagging.minSimilarity',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/SearchLabelsSection.svelte',
    evidence: 'zeroShotTagging.minSimilarity',
  },
  {
    pattern: 'machineLearning.duplicateDetection.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/DuplicateDetectionSection.svelte',
    evidence: 'duplicateDetection.enabled',
  },
  {
    pattern: 'machineLearning.duplicateDetection.enhancedVideo.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/DuplicateDetectionSection.svelte',
    evidence: 'enhancedVideo.enabled',
  },
  {
    pattern: 'machineLearning.duplicateDetection.enhancedVideo.frameCount',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/DuplicateDetectionSection.svelte',
    evidence: 'enhancedVideo.frameCount',
  },
  {
    pattern: 'machineLearning.duplicateDetection.enhancedVideo.maxDistance',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/DuplicateDetectionSection.svelte',
    evidence: 'enhancedVideo.maxDistance',
  },
  {
    pattern: 'machineLearning.duplicateDetection.enhancedVideo.minMatchingFrames',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/DuplicateDetectionSection.svelte',
    evidence: 'enhancedVideo.minMatchingFrames',
  },
  {
    pattern: 'machineLearning.duplicateDetection.maxDistance',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/DuplicateDetectionSection.svelte',
    evidence: 'duplicateDetection.maxDistance',
  },
  {
    pattern: 'machineLearning.duplicateDetection.preferOriginalFormat',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/DuplicateDetectionSection.svelte',
    evidence: 'duplicateDetection.preferOriginalFormat',
  },
  {
    pattern: 'machineLearning.enabled',
    kind: 'control',
    file: 'src/lib/components/admin-page/settings/machine-learning/RunPodPanel.svelte',
    evidence: 'machineLearning.enabled',
  },
  {
    pattern: 'machineLearning.facialRecognition.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/FacialRecognitionSection.svelte',
    evidence: 'facialRecognition.enabled',
  },
  {
    pattern: 'machineLearning.facialRecognition.maxDistance',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/FacialRecognitionSection.svelte',
    evidence: 'facialRecognition.maxDistance',
  },
  {
    pattern: 'machineLearning.facialRecognition.minFaces',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/FacialRecognitionSection.svelte',
    evidence: 'facialRecognition.minFaces',
  },
  {
    pattern: 'machineLearning.facialRecognition.minScore',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/FacialRecognitionSection.svelte',
    evidence: 'facialRecognition.minScore',
  },
  {
    pattern: 'machineLearning.facialRecognition.modelName',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/FacialRecognitionSection.svelte',
    evidence: 'facialRecognition.modelName',
  },
  {
    pattern: 'machineLearning.imageDescription.acceleration',
    kind: 'control',
    file: 'src/routes/admin/system-settings/MachineLearningSettings.svelte',
    evidence: 'imageDescription.acceleration',
  },
  {
    pattern: 'machineLearning.imageDescription.device',
    kind: 'control',
    file: 'src/routes/admin/system-settings/MachineLearningSettings.svelte',
    evidence: 'imageDescription.device',
  },
  {
    pattern: 'machineLearning.imageDescription.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/ImageDescriptionPromptSection.svelte',
    evidence: 'imageDescription.enabled',
  },
  {
    pattern: 'machineLearning.imageDescription.fallbackModelName',
    kind: 'control',
    file: 'src/routes/admin/system-settings/MachineLearningSettings.svelte',
    evidence: 'imageDescription.fallbackModelName',
  },
  {
    pattern: 'machineLearning.imageDescription.lastConfigChangeAt',
    kind: 'server-managed',
    file: 'src/lib/frameleaf/system-config-draft.ts',
    evidence: 'machineLearning.imageDescription.lastConfigChangeAt',
  },
  {
    pattern: 'machineLearning.imageDescription.modelName',
    kind: 'control',
    file: 'src/routes/admin/system-settings/MachineLearningSettings.svelte',
    evidence: 'imageDescription.modelName',
  },
  {
    pattern: 'machineLearning.imageDescription.pendingRequeueAt',
    kind: 'server-managed',
    file: 'src/lib/frameleaf/system-config-draft.ts',
    evidence: 'machineLearning.imageDescription.pendingRequeueAt',
  },
  {
    pattern: 'machineLearning.imageDescription.prompt.advanced.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/ImageDescriptionPromptSection.svelte',
    evidence: 'advanced?.enabled',
  },
  {
    pattern: 'machineLearning.imageDescription.prompt.advanced.placeholderValidation',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/ImageDescriptionPromptSection.svelte',
    evidence: 'advanced?.placeholderValidation',
  },
  {
    pattern: 'machineLearning.imageDescription.prompt.advanced.rawPromptTemplate',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/ImageDescriptionPromptSection.svelte',
    evidence: 'advanced?.rawPromptTemplate',
  },
  {
    pattern: 'machineLearning.imageDescription.prompt.customInstructions',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/ImageDescriptionPromptSection.svelte',
    evidence: 'prompt?.customInstructions',
  },
  {
    pattern: 'machineLearning.imageDescription.prompt.customVocabulary',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/ImageDescriptionPromptSection.svelte',
    evidence: 'prompt?.customVocabulary',
  },
  {
    pattern: 'machineLearning.imageDescription.prompt.forbiddenInferences',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/ImageDescriptionPromptSection.svelte',
    evidence: 'prompt?.forbiddenInferences',
  },
  {
    pattern: 'machineLearning.imageDescription.prompt.identityInjection.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/ImageDescriptionPromptSection.svelte',
    evidence: 'identityInjection?.enabled',
  },
  {
    pattern: 'machineLearning.imageDescription.prompt.identityInjection.maxNames',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/ImageDescriptionPromptSection.svelte',
    evidence: 'identityInjection?.maxNames',
  },
  {
    pattern: 'machineLearning.imageDescription.prompt.identityInjection.minFaceConfidence',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/ImageDescriptionPromptSection.svelte',
    evidence: 'identityInjection?.minFaceConfidence',
  },
  {
    pattern: 'machineLearning.imageDescription.prompt.lookFor',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/ImageDescriptionPromptSection.svelte',
    evidence: 'prompt?.lookFor',
  },
  {
    pattern: 'machineLearning.imageDescription.prompt.medicalIndicators',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/ImageDescriptionPromptSection.svelte',
    evidence: 'prompt?.medicalIndicators',
  },
  {
    pattern: 'machineLearning.imageDescription.prompt.nsfwIndicators',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/ImageDescriptionPromptSection.svelte',
    evidence: 'prompt?.nsfwIndicators',
  },
  {
    pattern: 'machineLearning.imageDescription.prompt.sentenceCountTarget',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/ImageDescriptionPromptSection.svelte',
    evidence: 'prompt?.sentenceCountTarget',
  },
  {
    pattern: 'machineLearning.imageDescription.prompt.style',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/ImageDescriptionPromptSection.svelte',
    evidence: 'prompt?.style',
  },
  {
    pattern: 'machineLearning.nsfwDetection.device',
    kind: 'control',
    file: 'src/routes/admin/system-settings/MachineLearningSettings.svelte',
    evidence: 'nsfwDetection.device',
  },
  {
    pattern: 'machineLearning.nsfwDetection.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/NsfwDetectionSection.svelte',
    evidence: 'nsfwDetection.enabled',
  },
  {
    pattern: 'machineLearning.nsfwDetection.hideFromLibrary',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/NsfwDetectionSection.svelte',
    evidence: 'nsfwDetection.hideFromLibrary',
  },
  {
    pattern: 'machineLearning.nsfwDetection.modelName',
    kind: 'control',
    file: 'src/routes/admin/system-settings/MachineLearningSettings.svelte',
    evidence: 'nsfwDetection.modelName',
  },
  {
    pattern: 'machineLearning.nsfwDetection.threshold',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/NsfwDetectionSection.svelte',
    evidence: 'nsfwDetection.threshold',
  },
  {
    pattern: 'machineLearning.ocr.documentFields',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/OcrSection.svelte',
    evidence: 'ocr.documentFields',
  },
  {
    pattern: 'machineLearning.ocr.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/OcrSection.svelte',
    evidence: 'ocr.enabled',
  },
  {
    pattern: 'machineLearning.ocr.maxResolution',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/OcrSection.svelte',
    evidence: 'ocr.maxResolution',
  },
  {
    pattern: 'machineLearning.ocr.minDetectionScore',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/OcrSection.svelte',
    evidence: 'ocr.minDetectionScore',
  },
  {
    pattern: 'machineLearning.ocr.minRecognitionScore',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/OcrSection.svelte',
    evidence: 'ocr.minRecognitionScore',
  },
  {
    pattern: 'machineLearning.ocr.modelName',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/OcrSection.svelte',
    evidence: 'ocr.modelName',
  },
  {
    pattern: 'machineLearning.runpod.apiKey',
    kind: 'credential',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'ConfigCredential.RunpodApiKey',
  },
  {
    pattern: 'machineLearning.runpod.apiKeyConfigured',
    kind: 'credential-state',
    file: 'src/lib/frameleaf/credentials.ts',
    evidence: 'runpod.apiKeyConfigured',
  },
  {
    pattern: 'machineLearning.runpod.autoBackfillOnLaunch',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpod.autoBackfillOnLaunch',
  },
  {
    pattern: 'machineLearning.runpod.autoStopEnabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpod.autoStopEnabled',
  },
  {
    pattern: 'machineLearning.runpod.autoStopGraceMinutes',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpod.autoStopGraceMinutes',
  },
  {
    pattern: 'machineLearning.runpod.containerDiskGb',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpod.containerDiskGb',
  },
  {
    pattern: 'machineLearning.runpod.dataPrivacyAcknowledged',
    kind: 'resource-action',
    file: 'src/lib/components/admin-page/settings/machine-learning/RunPodPanel.svelte',
    evidence: 'provisionRunPodPod',
  },
  {
    pattern: 'machineLearning.runpod.defaultGpuTypeId',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpod.defaultGpuTypeId',
  },
  {
    pattern: 'machineLearning.runpod.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpod.enabled',
  },
  {
    pattern: 'machineLearning.runpod.hfToken',
    kind: 'credential',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'ConfigCredential.HuggingfaceToken',
  },
  {
    pattern: 'machineLearning.runpod.hfTokenConfigured',
    kind: 'credential-state',
    file: 'src/lib/frameleaf/credentials.ts',
    evidence: 'runpod.hfTokenConfigured',
  },
  {
    pattern: 'machineLearning.runpod.imageName',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpod.imageName',
  },
  {
    pattern: 'machineLearning.runpod.maxRuntimeHours',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpod.maxRuntimeHours',
  },
  {
    pattern: 'machineLearning.runpod.mode',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpod.mode',
  },
  {
    pattern: 'machineLearning.runpod.provisionTimeoutMinutes',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpod.provisionTimeoutMinutes',
  },
  {
    pattern: 'machineLearning.runpod.serverless.executionTimeoutMs',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpodServerless.executionTimeoutMs',
  },
  {
    pattern: 'machineLearning.runpod.serverless.gpuTypeIds',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpodServerless.gpuTypeIds',
  },
  {
    pattern: 'machineLearning.runpod.serverless.idleTimeoutSeconds',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpodServerless.idleTimeoutSeconds',
  },
  {
    pattern: 'machineLearning.runpod.serverless.scalerType',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpodServerless.scalerType',
  },
  {
    pattern: 'machineLearning.runpod.serverless.scalerValue',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpodServerless.scalerValue',
  },
  {
    pattern: 'machineLearning.runpod.serverless.workersMax',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpodServerless.workersMax',
  },
  {
    pattern: 'machineLearning.runpod.serverless.workersMin',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpodServerless.workersMin',
  },
  {
    pattern: 'machineLearning.runpod.volumeGb',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/RunPodSection.svelte',
    evidence: 'runpod.volumeGb',
  },
  {
    pattern: 'machineLearning.urls',
    kind: 'control',
    file: 'src/routes/admin/system-settings/machine-learning/MlUrlsSection.svelte',
    evidence: 'workingConfig.urls[i]',
  },
  {
    pattern: 'map.darkStyle',
    kind: 'control',
    file: 'src/routes/admin/system-settings/MapSettings.svelte',
    evidence: 'map.darkStyle',
  },
  {
    pattern: 'map.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/MapSettings.svelte',
    evidence: 'map.enabled',
  },
  {
    pattern: 'map.lightStyle',
    kind: 'control',
    file: 'src/routes/admin/system-settings/MapSettings.svelte',
    evidence: 'map.lightStyle',
  },
  {
    pattern: 'metadata.faces.import',
    kind: 'control',
    file: 'src/routes/admin/system-settings/MetadataSettings.svelte',
    evidence: 'faces.import',
  },
  {
    pattern: 'newVersionCheck.channel',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NewVersionCheckSettings.svelte',
    evidence: 'newVersionCheck.channel',
  },
  {
    pattern: 'newVersionCheck.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NewVersionCheckSettings.svelte',
    evidence: 'newVersionCheck.enabled',
  },
  {
    pattern: 'nightlyTasks.clusterNewFaces',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NightlyTasksSettings.svelte',
    evidence: 'nightlyTasks.clusterNewFaces',
  },
  {
    pattern: 'nightlyTasks.databaseCleanup',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NightlyTasksSettings.svelte',
    evidence: 'nightlyTasks.databaseCleanup',
  },
  {
    pattern: 'nightlyTasks.generateMemories',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NightlyTasksSettings.svelte',
    evidence: 'nightlyTasks.generateMemories',
  },
  {
    pattern: 'nightlyTasks.missingThumbnails',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NightlyTasksSettings.svelte',
    evidence: 'nightlyTasks.missingThumbnails',
  },
  {
    pattern: 'nightlyTasks.startTime',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NightlyTasksSettings.svelte',
    evidence: 'nightlyTasks.startTime',
  },
  {
    pattern: 'nightlyTasks.syncQuotaUsage',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NightlyTasksSettings.svelte',
    evidence: 'nightlyTasks.syncQuotaUsage',
  },
  {
    pattern: 'notifications.smtp.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NotificationSettings.svelte',
    evidence: 'smtp.enabled',
  },
  {
    pattern: 'notifications.smtp.from',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NotificationSettings.svelte',
    evidence: 'smtp.from',
  },
  {
    pattern: 'notifications.smtp.replyTo',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NotificationSettings.svelte',
    evidence: 'smtp.replyTo',
  },
  {
    pattern: 'notifications.smtp.transport.host',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NotificationSettings.svelte',
    evidence: 'transport.host',
  },
  {
    pattern: 'notifications.smtp.transport.ignoreCert',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NotificationSettings.svelte',
    evidence: 'transport.ignoreCert',
  },
  {
    pattern: 'notifications.smtp.transport.password',
    kind: 'credential',
    file: 'src/routes/admin/system-settings/NotificationSettings.svelte',
    evidence: 'ConfigCredential.SmtpPassword',
  },
  {
    pattern: 'notifications.smtp.transport.passwordConfigured',
    kind: 'credential-state',
    file: 'src/lib/frameleaf/credentials.ts',
    evidence: 'transport.passwordConfigured',
  },
  {
    pattern: 'notifications.smtp.transport.port',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NotificationSettings.svelte',
    evidence: 'transport.port',
  },
  {
    pattern: 'notifications.smtp.transport.secure',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NotificationSettings.svelte',
    evidence: 'transport.secure',
  },
  {
    pattern: 'notifications.smtp.transport.username',
    kind: 'control',
    file: 'src/routes/admin/system-settings/NotificationSettings.svelte',
    evidence: 'transport.username',
  },
  {
    pattern: 'oauth.accountManagementUrl',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.accountManagementUrl',
  },
  {
    pattern: 'oauth.allowInsecureRequests',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.allowInsecureRequests',
  },
  {
    pattern: 'oauth.autoLaunch',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.autoLaunch',
  },
  {
    pattern: 'oauth.autoRegister',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.autoRegister',
  },
  {
    pattern: 'oauth.buttonText',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.buttonText',
  },
  {
    pattern: 'oauth.clientId',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.clientId',
  },
  {
    pattern: 'oauth.clientSecret',
    kind: 'credential',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'ConfigCredential.OauthClientSecret',
  },
  {
    pattern: 'oauth.clientSecretConfigured',
    kind: 'credential-state',
    file: 'src/lib/frameleaf/credentials.ts',
    evidence: 'oauth.clientSecretConfigured',
  },
  {
    pattern: 'oauth.defaultStorageQuota',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.defaultStorageQuota',
  },
  {
    pattern: 'oauth.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.enabled',
  },
  {
    pattern: 'oauth.endSessionEndpoint',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.endSessionEndpoint',
  },
  {
    pattern: 'oauth.issuerUrl',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.issuerUrl',
  },
  {
    pattern: 'oauth.mobileOverrideEnabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.mobileOverrideEnabled',
  },
  {
    pattern: 'oauth.mobileRedirectUri',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.mobileRedirectUri',
  },
  {
    pattern: 'oauth.profileSigningAlgorithm',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.profileSigningAlgorithm',
  },
  {
    pattern: 'oauth.prompt',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.prompt',
  },
  {
    pattern: 'oauth.roleClaim',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.roleClaim',
  },
  {
    pattern: 'oauth.scope',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.scope',
  },
  {
    pattern: 'oauth.signingAlgorithm',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.signingAlgorithm',
  },
  {
    pattern: 'oauth.storageLabelClaim',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.storageLabelClaim',
  },
  {
    pattern: 'oauth.storageQuotaClaim',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.storageQuotaClaim',
  },
  {
    pattern: 'oauth.timeout',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.timeout',
  },
  {
    pattern: 'oauth.tokenEndpointAuthMethod',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'oauth.tokenEndpointAuthMethod',
  },
  {
    pattern: 'passwordLogin.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/AuthSettings.svelte',
    evidence: 'passwordLogin.enabled',
  },
  {
    pattern: 'physicalDeduplication.enabled',
    kind: 'control',
    file: 'src/lib/components/admin-settings/StorageTemplateSettings.svelte',
    evidence: 'physicalDeduplication.enabled',
  },
  {
    pattern: 'physicalDeduplication.masterUserId',
    kind: 'control',
    file: 'src/lib/components/admin-settings/StorageTemplateSettings.svelte',
    evidence: 'physicalDeduplication.masterUserId',
  },
  {
    pattern: 'reverseGeocoding.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/MapSettings.svelte',
    evidence: 'reverseGeocoding.enabled',
  },
  {
    pattern: 'server.externalDomain',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ServerSettings.svelte',
    evidence: 'server.externalDomain',
  },
  {
    pattern: 'server.loginPageMessage',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ServerSettings.svelte',
    evidence: 'server.loginPageMessage',
  },
  {
    pattern: 'server.name',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ServerSettings.svelte',
    evidence: 'server.name',
  },
  {
    pattern: 'server.publicUsers',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ServerSettings.svelte',
    evidence: 'server.publicUsers',
  },
  {
    pattern: 'smartAlbums.builtIn.*.clipQueries',
    kind: 'control',
    file: 'src/routes/admin/system-settings/SmartAlbumsSettings.svelte',
    evidence: 'getKind(k).clipQueries',
  },
  {
    pattern: 'smartAlbums.builtIn.*.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/SmartAlbumsSettings.svelte',
    evidence: 'kindConfig.enabled',
  },
  {
    pattern: 'smartAlbums.builtIn.*.name',
    kind: 'control',
    file: 'src/routes/admin/system-settings/SmartAlbumsSettings.svelte',
    evidence: 'kindConfig.name',
  },
  {
    pattern: 'smartAlbums.builtIn.*.tagTriggers',
    kind: 'control',
    file: 'src/routes/admin/system-settings/SmartAlbumsSettings.svelte',
    evidence: 'getKind(k).tagTriggers',
  },
  {
    pattern: 'smartAlbums.builtIn.*.threshold',
    kind: 'control',
    file: 'src/routes/admin/system-settings/SmartAlbumsSettings.svelte',
    evidence: 'kindConfig.threshold',
  },
  {
    pattern: 'smartAlbums.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/SmartAlbumsSettings.svelte',
    evidence: 'smartAlbums.enabled',
  },
  {
    pattern: 'smartAlbums.rules.defaultAction',
    kind: 'control',
    file: 'src/routes/admin/system-settings/SmartAlbumsSettings.svelte',
    evidence: 'rules.defaultAction',
  },
  {
    pattern: 'smartAlbums.rules.visualCategories',
    kind: 'control',
    file: 'src/routes/admin/system-settings/SmartAlbumsSettings.svelte',
    evidence: 'rules.visualCategories',
  },
  {
    pattern: 'storageTemplate.enabled',
    kind: 'control',
    file: 'src/lib/components/admin-settings/StorageTemplateSettings.svelte',
    evidence: 'storageTemplate.enabled',
  },
  {
    pattern: 'storageTemplate.hashVerificationEnabled',
    kind: 'control',
    file: 'src/lib/components/admin-settings/StorageTemplateSettings.svelte',
    evidence: 'storageTemplate.hashVerificationEnabled',
  },
  {
    pattern: 'storageTemplate.template',
    kind: 'control',
    file: 'src/lib/components/admin-settings/StorageTemplateSettings.svelte',
    evidence: 'storageTemplate.template',
  },
  {
    pattern: 'templates.email.*',
    kind: 'control',
    file: 'src/routes/admin/system-settings/TemplateSettings.svelte',
    evidence: 'config.templates.email[templateKey]',
  },
  {
    pattern: 'theme.customCss',
    kind: 'control',
    file: 'src/routes/admin/system-settings/ThemeSettings.svelte',
    evidence: 'theme.customCss',
  },
  {
    pattern: 'trash.days',
    kind: 'control',
    file: 'src/routes/admin/system-settings/TrashSettings.svelte',
    evidence: 'trash.days',
  },
  {
    pattern: 'trash.enabled',
    kind: 'control',
    file: 'src/routes/admin/system-settings/TrashSettings.svelte',
    evidence: 'trash.enabled',
  },
  {
    pattern: 'user.deleteDelay',
    kind: 'control',
    file: 'src/routes/admin/system-settings/UserSettings.svelte',
    evidence: 'user.deleteDelay',
  },
]);

/** The same for every personal preference (a leaf of UserPreferencesUpdateDto), FL-67/FL-71. */
export const PREFERENCE_LEAF_COVERAGE: readonly SettingsLeafCoverage[] = Object.freeze([
  {
    pattern: 'albums.defaultAssetOrder',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'albums.defaultAssetOrder',
  },
  {
    pattern: 'avatar.color',
    kind: 'control',
    file: 'src/lib/components/frameleaf/access/ProfileSection.svelte',
    evidence: 'userUpdateMeDto: { avatarColor }',
  },
  {
    pattern: 'cast.adminDisabled',
    kind: 'control',
    file: 'src/lib/components/frameleaf/AccountPreferencesEditor.svelte',
    evidence: 'cast.adminDisabled',
  },
  {
    pattern: 'cast.gCastEnabled',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'cast.gCastEnabled',
  },
  {
    pattern: 'download.archiveSize',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/DownloadSettings.svelte',
    evidence: 'download.archiveSize',
  },
  {
    pattern: 'download.includeEmbeddedVideos',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/DownloadSettings.svelte',
    evidence: 'download.includeEmbeddedVideos',
  },
  {
    pattern: 'emailNotifications.albumInvite',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/NotificationsSettings.svelte',
    evidence: 'emailNotifications.albumInvite',
  },
  {
    pattern: 'emailNotifications.albumUpdate',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/NotificationsSettings.svelte',
    evidence: 'emailNotifications.albumUpdate',
  },
  {
    pattern: 'emailNotifications.enabled',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/NotificationsSettings.svelte',
    evidence: 'emailNotifications.enabled',
  },
  {
    pattern: 'expectedRevision',
    kind: 'protocol',
    file: 'src/lib/frameleaf/account-preferences.ts',
    evidence: 'expectedRevision',
  },
  {
    pattern: 'folders.enabled',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'folders.enabled',
  },
  {
    pattern: 'folders.sidebarWeb',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'folders.sidebarWeb',
  },
  {
    pattern: 'memories.duration',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'memories.duration',
  },
  {
    pattern: 'memories.enabled',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'memories.enabled',
  },
  {
    pattern: 'memories.sidebarWeb',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'memories.sidebarWeb',
  },
  {
    pattern: 'people.enabled',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'people.enabled',
  },
  {
    pattern: 'people.minimumFaces',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'people.minimumFaces',
  },
  {
    pattern: 'people.sidebarWeb',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'people.sidebarWeb',
  },
  {
    pattern: 'privacy.suppression.personIds',
    kind: 'control',
    file: 'src/lib/components/frameleaf/access/LockedRulesPanel.svelte',
    evidence: "toggle('personIds'",
  },
  {
    pattern: 'privacy.suppression.petIds',
    kind: 'control',
    file: 'src/lib/components/frameleaf/access/LockedRulesPanel.svelte',
    evidence: 'draft.petIds',
  },
  {
    pattern: 'privacy.suppression.scope',
    kind: 'control',
    file: 'src/lib/components/frameleaf/access/LockedRulesPanel.svelte',
    evidence: 'bind:value={draft.scope}',
  },
  {
    pattern: 'privacy.suppression.tagIds',
    kind: 'control',
    file: 'src/lib/components/frameleaf/access/LockedRulesPanel.svelte',
    evidence: "toggle('tagIds'",
  },
  {
    pattern: 'purchase.hideBuyButtonUntil',
    kind: 'control',
    file: 'src/lib/components/frameleaf/AccountPreferencesEditor.svelte',
    evidence: 'purchase.hideBuyButtonUntil',
  },
  {
    pattern: 'purchase.showSupportBadge',
    kind: 'control',
    file: 'src/lib/components/frameleaf/access/SupporterSection.svelte',
    evidence: 'showSupportBadge',
  },
  {
    pattern: 'ratings.enabled',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'ratings.enabled',
  },
  {
    pattern: 'recentlyAdded.sidebarWeb',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'recentlyAdded.sidebarWeb',
  },
  {
    pattern: 'savedSearches',
    kind: 'control',
    file: 'src/lib/components/frameleaf/RailSavedSearches.svelte',
    evidence: 'savedSearches',
  },
  {
    pattern: 'sharedLinks.enabled',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'sharedLinks.enabled',
  },
  {
    pattern: 'sharedLinks.sidebarWeb',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'sharedLinks.sidebarWeb',
  },
  {
    pattern: 'tags.enabled',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'tags.enabled',
  },
  {
    pattern: 'tags.sidebarWeb',
    kind: 'control',
    file: 'src/routes/(user)/user-settings/FeatureSettings.svelte',
    evidence: 'tags.sidebarWeb',
  },
]);
