import { faker } from '@faker-js/faker';
import { expect, test, type Page } from '@playwright/test';
import { setupBaseMockApiRoutes } from 'src/ui/mock-network/base-network.js';
import {
  CloudBackupMockState,
  GENERATED_KEY,
  setupCloudBackupMockApiRoutes,
} from 'src/ui/mock-network/cloud-backup-network.js';
import { CloudMockState, setupCloudMockApiRoutes } from 'src/ui/mock-network/cloud-network.js';

/**
 * Settings → Frameleaf Cloud → Cloud backup (FL-160) against a mocked server: after the bucket is checked,
 * the setup dialog asks how the encryption key is kept before anything is claimed; an own key must be
 * downloaded, and saved elsewhere, before Continue is enabled, and never keeping it on the server needs the
 * typed acknowledgement; a generated key shows the recovery kit once and needs it saved.
 */
const backupPage = '/user-settings?area=cloud&section=cloud-backup';

const fillBucket = async (page: Page) => {
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Storage address').fill('https://s3.eu-central-2.wasabisys.test');
  await dialog.getByLabel('Bucket', { exact: true }).fill('family-backup');
  await dialog.getByLabel('Access key ID').fill('AKIAEXAMPLE');
  await dialog.getByLabel('Secret access key').fill('secret-example');
  await expect(dialog.getByRole('button', { name: 'Continue' })).toBeDisabled();
  await dialog.getByRole('button', { name: 'Check bucket' }).click();
  await expect(dialog.getByText(/The provider accepted and returned a test file/)).toBeVisible();
  await dialog.getByRole('button', { name: 'Continue' }).click();
};

test.describe.configure({ mode: 'parallel' });
test.describe('Frameleaf Cloud backup setup', () => {
  let cloud: CloudMockState;
  let backup: CloudBackupMockState;

  test.beforeEach(async ({ context }) => {
    await setupBaseMockApiRoutes(context, faker.string.uuid());
    cloud = { state: 'linked', requests: [] };
    await setupCloudMockApiRoutes(context, cloud);
    backup = { configured: false, keyMode: null, requests: [] };
    await setupCloudBackupMockApiRoutes(context, backup);
  });

  test('your own key must be downloaded before continuing, and never keeping it needs "I understand"', async ({
    page,
  }) => {
    await page.goto(backupPage);
    await expect(page.getByText('Cloud backup is not set up')).toBeVisible();
    await page.getByRole('button', { name: 'Set up cloud backup' }).click();
    const dialog = page.getByRole('dialog');
    // Frameleaf-managed storage is not offered until Frameleaf Cloud provides it
    await expect(dialog.getByRole('radio', { name: /Frameleaf-managed storage/ })).toBeDisabled();
    await fillBucket(page);

    // the key choice, before anything is claimed: a generated key is preselected
    await expect(dialog.getByRole('radio', { name: /Generate a key for me/ })).toBeChecked();
    await dialog.getByRole('radio', { name: /I’ll maintain my own key/ }).check();
    const next = dialog.getByRole('button', { name: 'Continue' });
    await expect(next).toBeDisabled();
    await expect(dialog.getByText('Download the key file to continue.')).toBeVisible();
    await expect(dialog.getByRole('checkbox', { name: /somewhere other than this server/ })).toBeDisabled();

    const download = page.waitForEvent('download');
    await dialog.getByRole('button', { name: 'Download key file' }).click();
    const downloaded = await download;
    expect(downloaded.suggestedFilename()).toMatch(/^frameleaf-backup-key-[\dA-F]{4}-[\dA-F]{4}\.json$/);
    await expect(next).toBeDisabled();
    await dialog.getByRole('checkbox', { name: /somewhere other than this server/ }).check();
    await expect(next).toBeEnabled();

    // no copy on this server: the typed acknowledgement
    await dialog.getByRole('switch', { name: 'Keep a copy on this server' }).click();
    await expect(next).toBeDisabled();
    await dialog.getByLabel(/Type “I understand”/).fill('I understand');
    await expect(next).toBeEnabled();
    await next.click();

    await expect(dialog.getByText('family-backup')).toBeVisible();
    await dialog.getByRole('button', { name: 'Claim bucket' }).click();
    await expect(dialog.getByText('Bucket claimed for this server.')).toBeVisible();
    const setup = backup.requests.find(({ path }) => path === 'admin/cloud/backup/setup');
    expect(setup?.body).toMatchObject({
      target: 'byo-s3',
      keyMode: 'own-memory',
      acknowledgement: 'I understand',
      s3: { endpoint: 'https://s3.eu-central-2.wasabisys.test', bucket: 'family-backup' },
    });
    expect((setup?.body as { key: string }).key).toMatch(/^[\d+/A-Za-z]{43}=$/);
    // an own key is never generated by the server
    expect(backup.requests.some(({ path }) => path === 'admin/cloud/backup/key')).toBe(false);

    await dialog.getByRole('button', { name: 'Finish setup' }).click();
    await expect(page.getByText('Your own bucket')).toBeVisible();
    await expect(page.getByText('Your own key, never saved')).toBeVisible();
  });

  test('a generated key shows the recovery kit once and needs it saved before claiming', async ({ page }) => {
    await page.goto(backupPage);
    await page.getByRole('button', { name: 'Set up cloud backup' }).click();
    const dialog = page.getByRole('dialog');
    await fillBucket(page);

    await dialog.getByRole('button', { name: 'Continue' }).click();
    await expect(dialog.getByText('This kit is shown once')).toBeVisible();
    await expect(dialog.getByTestId('recovery-kit')).toContainText(GENERATED_KEY.recoveryCode);
    await expect(dialog.getByTestId('recovery-kit')).toContainText(GENERATED_KEY.fingerprint);
    const next = dialog.getByRole('button', { name: 'Continue' });
    await expect(next).toBeDisabled();
    await dialog.getByRole('checkbox', { name: 'I saved or printed the recovery kit.' }).check();
    await next.click();

    await dialog.getByRole('button', { name: 'Claim bucket' }).click();
    await expect(dialog.getByText('Bucket claimed for this server.')).toBeVisible();
    const setup = backup.requests.find(({ path }) => path === 'admin/cloud/backup/setup');
    expect(setup?.body).toMatchObject({ keyMode: 'server', key: GENERATED_KEY.key });
  });
});
