import { Mocked, vitest } from 'vitest';
import { AssetRepository } from 'src/repositories/asset.repository.js';
import { RepositoryInterface } from 'src/types.js';

export const newAssetRepositoryMock = (): Mocked<RepositoryInterface<AssetRepository>> => {
  return {
    create: vitest.fn(),
    createAll: vitest.fn(),
    upsertExif: vitest.fn(),
    updateAllExif: vitest.fn(),
    clearLocation: vitest.fn(),
    updateDateTimeOriginal: vitest.fn().mockResolvedValue([]),
    setDateTimeOriginal: vitest.fn(),
    unlockProperties: vitest.fn().mockResolvedValue([]),
    upsertJobStatus: vitest.fn(),
    getForCopy: vitest.fn(),
    getByDayOfYear: vitest.fn(),
    getByIds: vitest.fn().mockResolvedValue([]),
    getByIdsWithAllRelationsButStacks: vitest.fn().mockResolvedValue([]),
    getById: vitest.fn(),
    getByChecksum: vitest.fn(),
    getByChecksums: vitest.fn(),
    getUploadAssetIdByChecksum: vitest.fn(),
    getLivePhotoCount: vitest.fn(),
    getLibraryAssetCount: vitest.fn(),
    updateAll: vitest.fn(),
    getByLibraryIdAndOriginalPath: vitest.fn(),
    deleteAll: vitest.fn(),
    update: vitest.fn(),
    remove: vitest.fn(),
    findLivePhotoMatch: vitest.fn(),
    getStatistics: vitest.fn(),
    getCalendarHeatmap: vitest.fn(),
    getTimeBucket: vitest.fn(),
    getTimelineOrdered: vitest.fn(),
    getTimeBuckets: vitest.fn(),
    getTimelineHighlights: vitest.fn(),
    getAssetIdByCity: vitest.fn(),
    getRecentlyCreatedAssetIds: vitest.fn(),
    getNsfwAssetIds: vitest.fn().mockResolvedValue(new Set()),
    getHiddenContentAssetIds: vitest.fn().mockResolvedValue(new Set()),
    getLockedAssetIds: vitest.fn().mockResolvedValue(new Set()),
    getLockReasons: vitest.fn().mockResolvedValue([]),
    getUnlockedDetectionIds: vitest.fn().mockResolvedValue([]),
    getStackSiblingIds: vitest.fn().mockResolvedValue([]),
    lock: vitest.fn().mockResolvedValue([]),
    lockGroupRows: vitest.fn().mockResolvedValue(undefined),
    lockGroupMembers: vitest.fn().mockResolvedValue([]),
    findLockGroupIds: vitest.fn().mockResolvedValue([]),
    unlock: vitest.fn().mockResolvedValue([]),
    upsertFile: vitest.fn(),
    upsertFiles: vitest.fn(),
    deleteFile: vitest.fn(),
    deleteFiles: vitest.fn(),
    detectOfflineExternalAssets: vitest.fn(),
    filterNewExternalAssetPaths: vitest.fn(),
    updateByLibraryId: vitest.fn(),
    getFileSamples: vitest.fn(),
    getMetadata: vitest.fn(),
    getMetadataByKey: vitest.fn(),
    upsertMetadata: vitest.fn(),
    updateIsNsfw: vitest.fn(),
    upsertBulkMetadata: vitest.fn(),
    deleteMetadataByKey: vitest.fn(),
    deleteBulkMetadata: vitest.fn(),
    getForOriginal: vitest.fn(),
    getForOriginals: vitest.fn(),
    getForThumbnail: vitest.fn(),
    getForVideo: vitest.fn(),
    getForEdit: vitest.fn(),
    getForOcr: vitest.fn(),
    getForMetadataExtractionTags: vitest.fn(),
    getForFaces: vitest.fn(),
    getForUpdateTags: vitest.fn(),
    getDescriptionStats: vitest.fn(),
    getEventStoryCandidates: vitest.fn(),
    getYearInReviewCandidates: vitest.fn(),
  };
};
