name: Docs build
"on":
  workflow_dispatch: null
  pull_request:
    branches:
      - fork/main
  push:
    branches:
      - fork/main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  build:
    name: Docs Build
    permissions:
      contents: read
    if: ${{ github.repository == 'Frameleaf/frameleaf-app' }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Run install
        run: pnpm install --frozen-lockfile
      - name: Check formatting
        run: pnpm format
      - name: Run build
        run: pnpm build
    timeout-minutes: 60
