# Dart analysis needs no upstream bot or licensed metrics-service credentials.
name: Static Code Analysis
'on':
  workflow_dispatch: null
  pull_request:
    branches:
      - fork/main
  push:
    branches:
      - fork/main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  mobile-dart-analyze:
    name: Run Dart Code Analysis
    if: ${{ github.repository == 'Frameleaf/frameleaf-app' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Setup Mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea
        with:
          github_token: ${{ github.token }}
          working_directory: ./mobile
          install_args: --locked
          version: 2026.7.12
      - name: Install translation codegen dependencies
        working-directory: .
        run: pnpm -w install --frozen-lockfile
      - name: Install dependencies
        run: mise run //mobile:install:ci
      - name: Install dependencies for UI package
        run: flutter pub get --enforce-lockfile
        working-directory: ./mobile/packages/ui
      - name: Perform codegen
        run: mise run //mobile:codegen
      - name: Run analyze
        run: dart analyze --fatal-infos
      - name: Run format
        run: mise run //mobile:format
    timeout-minutes: 60
